### ISSUE TITLE
DevOps - Cross-Platform

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#1046]
# DevOps - Cross-Platform

## Objective
- [ ] Make sure our ops code runs on Unix AND Windows.

## Tasks
- [ ] Implement a CLI in nodejs to replace the bash scripts
- [ ] Implement more tooling to make our life easier

**Comment by Jackseed** [comment]
Same issue as #640, I close the old one

**Comment by lsenta** [comment]
- [ ] port the package.json with env management
- [ ] port the ops/*.sh scripts
- [ ] port the firebase.json -> predeploy

**Comment by lsenta** [comment]
```
ts-node blockframes.ts build delivery
ts-node blockframes.ts deploy secrets
ts-node blockframes.ts deploy demos
ts-node blockframes.ts deploy functions
```

**Comment by lsenta** [comment]
- [ ] parse argv
- [ ] call system scripts `ng build --env=${params}`

**Comment by fritzschoff** [comment]
@Jackseed can we close this issue?

**Comment by george43g** [comment]
Dupe of #3082 - Let's make sure requirements covered in this issue have also been resolved.

**Comment by george43g** [comment]
Issue has been completed - closing now
