### ISSUE TITLE
Tests E2E - Reusability & Refactor

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#1047]
# Tests E2E - Reusability & Refactor

## Objective
- [x] Make sure we can reuse the e2e testing code among applications
- [x] Simplify & Strengthen the page objects code

## Tasks
- [x] Turn the e2e page objects code into a library that can be shared among every apps
- [x]  Get rid of test ids, pages ids, etc that diverged from the original intent

**Comment by lsenta** [comment]
Giving up turning this into a global library ala `@blockframes/e2e`, there's an issue with:

- cypress reusing typescript configurations. This was fixed in 8.2.0 https://github.com/nrwl/nx/issues/883

- BUT I haven't managed to update correctly the angular / cypress / etc configuration, I'm getting loads and loads of errors that looks like incompat' between angular packages.

Related:
https://github.com/nrwl/nx/issues/1597
https://github.com/angular/angular-cli/issues/15290
https://stackoverflow.com/questions/56647865/invalid-rule-result-instance-of-class-promise

Ideally we should be able to access the `@blockframes/e2e` library, for this we need an updated version of the ng / nx / cypress combo (>8.2.0).

For now we'll use relative import, more fragile but working.

**Comment by GrandSchtroumpf** [comment]
I've done some quick tests and this config seems to work (I've got some issues with env and functions because my workspace is not up-to-date):
> remove `node_modules`

```json
{
  "dependencies": {
    "@angular/animations": "^8.2.10",
    "@angular/cdk": "^8.2.3",
    "@angular/common": "^8.2.10",
    "@angular/compiler": "^8.2.10",
    "@angular/core": "^8.2.10",
    "@angular/fire": "^5.1.1",
    "@angular/flex-layout": "^8.0.0-beta.27",
    "@angular/forms": "^8.2.10",
    "@angular/material": "^8.2.3",
    "@angular/platform-browser": "^8.2.10",
    "@angular/platform-browser-dynamic": "^8.2.10",
    "@angular/router": "^8.2.10",
    "@angular/service-worker": "^8.2.10",
    "@datorama/akita": "^4.10.8",
    "@ethersproject/abi": "^5.0.0-beta.139",
    "@ethersproject/abstract-provider": "^5.0.0-beta.133",
    "@ethersproject/abstract-signer": "^5.0.0-beta.134",
    "@ethersproject/address": "^5.0.0-beta.130",
    "@ethersproject/bignumber": "^5.0.0-beta.132",
    "@ethersproject/bytes": "^5.0.0-beta.131",
    "@ethersproject/contracts": "^5.0.0-beta.139",
    "@ethersproject/hash": "^5.0.0-beta.130",
    "@ethersproject/hdnode": "^5.0.0-beta.132",
    "@ethersproject/keccak256": "^5.0.0-beta.129",
    "@ethersproject/providers": "^5.0.0-beta.143",
    "@ethersproject/signing-key": "^5.0.0-beta.131",
    "@ethersproject/strings": "^5.0.0-beta.132",
    "@ethersproject/wallet": "^5.0.0-beta.132",
    "@fullpage/angular-fullpage": "0.0.14",
    "@google-cloud/pubsub": "^1.1.2",
    "@google-cloud/storage": "^3.3.1",
    "@ngmodule/material-carousel": "^0.5.1",
    "@ngrx/effects": "8.4.0",
    "@ngrx/router-store": "8.4.0",
    "@ngrx/store": "8.4.0",
    "@nrwl/angular": "8.6.0",
    "@schematics/angular": "^8.3.9",
    "@sendgrid/mail": "^6.4.0",
    "@types/sendgrid": "^4.3.0",
    "akita-ng-fire": "^1.5.0",
    "algoliasearch": "^3.35.1",
    "core-js": "^3.2.1",
    "ethereum-blockies-base64": "^1.0.2",
    "express": "4.17.1",
    "firebase": "^7.2.0",
    "firebase-admin": "^8.6.0",
    "firebase-functions": "^3.3.0",
    "generate-password": "^1.4.2",
    "hammerjs": "^2.0.8",
    "line-reader": "^0.4.0",
    "lodash": "^4.17.15",
    "ngx-mat-select-search": "^1.8.0",
    "node-gyp": "^6.0.0",
    "npm": "^6.12.0",
    "pdfmake": "^0.1.60",
    "punycode": "^2.1.1",
    "request": "^2.88.0",
    "rxjs": "~6.5.3",
    "saturn-datepicker": "^8.0.1",
    "tmp": "0.1.0",
    "xlsx": "^0.15.1",
    "zone.js": "^0.10.2"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^0.803.9",
    "@angular-devkit/build-ng-packagr": "~0.803.9",
    "@angular/cli": "8.3.9",
    "@angular/compiler-cli": "^8.2.10",
    "@angular/language-service": "^8.2.10",
    "@angularclass/hmr": "^2.1.3",
    "@datorama/akita-ng-router-store": "^3.1.4",
    "@datorama/akita-ngdevtools": "^3.0.2",
    "@ngrx/schematics": "8.4.0",
    "@ngrx/store-devtools": "8.4.0",
    "@nrwl/cypress": "8.6.0",
    "@nrwl/express": "8.6.0",
    "@nrwl/jest": "8.6.0",
    "@nrwl/node": "8.6.0",
    "@nrwl/workspace": "8.6.0",
    "@types/algoliasearch": "^3.34.3",
    "@types/express": "4.17.1",
    "@types/jest": "24.0.18",
    "@types/jquery": "3.3.31",
    "@types/line-reader": "0.0.28",
    "@types/lodash": "^4.14.144",
    "@types/node": "~12.7.12",
    "@types/pdfmake": "^0.1.8",
    "@types/tmp": "0.1.0",
    "akita-schematics": "^2.0.0",
    "codelyzer": "~5.1.2",
    "concurrently": "^5.0.0",
    "cypress": "^3.4.1",
    "dotenv": "8.1.0",
    "ethereum-waffle": "^2.1.0",
    "husky": "^3.0.8",
    "jest": "24.9.0",
    "jest-preset-angular": "7.1.1",
    "ng-packagr": "^5.6.1",
    "openzeppelin-solidity": "^2.2.0",
    "pdfkit": "^0.10.0",
    "prettier": "1.18.2",
    "pwmetrics": "^4.2.2",
    "ts-node": "~8.4.1",
    "tsickle": "0.37.0",
    "tslib": "^1.10.0",
    "tslint": "~5.20.0",
    "typescript": "^3.5.3",
    "webpack-bundle-analyzer": "^3.5.2"
  },
}
```
