### ISSUE TITLE
Address form fields

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#1126]
## Description
We need to have an address with the good format: street address / Zip code / City / Country + State / Province when it's relevant.

## Objectives
- [ ] Research on formating the fields
- [ ] Update data model
- [ ] Create the form fields accordingly
- [ ] Implement it on the pages:
       - [ ] Create your organization #1120
       - [ ] Edit my org #1101
- [ ] Search for `#1126` into code
