### ISSUE TITLE
Excel Sheet updates

### ISSUE THREAD

**Issue by phpgeekfr** [blockframes/blockframes#1562]
Movies: 
- [x]  Original release (movie.salesInfo.originalRelease) excel should be updated to match model (country + media of originCountryRelease date)
- [ ] Once Max terminated MovieVersionInfo update, update excel import accordingly #1411 
- [x] Be able to handle various Premiere Types (world, market ...)
- [x] rename Production Companie(s) into Stake Holders
- [ ] rating: missing system, country, value [, reason] + rename to `ratings` and use ';' and ','
- [x] European Qualification (Yes or No) can be merge with certifications
- [x] Key Assets (max 3 sentences, use semicolon as separator) => this is only one sentence now
- [ ] missing country in column `Stakeholders (name, role)`
- [ ] missing logo in column `Festival Prizes (Festival name, Year, Selection/Prize, Premiere)` 
- [x] principal cast add role (currently forced to `actor`) May need to split in two columns: crew & cast (CF Anastasiia) #1603 

Contracts:
- [x]  use currency in staticModels `eur` => `euro` => not a big deal
- [x]  when setting child and parents contract Id add information about sub-licensors needed or not
- [x] for our internal use/ developers tests, we should put `OrgId` of `licensors` & `licensee` #1397 
- [x] fix circular issues contract.model & contract-version.model
- [x] check if contract import is OK

Commons:
- [ ] check `#1562` in code comments
- [ ] update `movie.main.stakeholders` after @GrandSchtroumpf  updates
