### ISSUE TITLE
Note TODO to get bigquery & analytics in ci / staging / prod

### ISSUE THREAD

**Issue by laurentsenta** [blockframes/blockframes#1627]
- [x] test account services
  - [x] locally: check that it's "data viewer" "job viewer" (try locally)
           we just need the 2 roles: BigQuery Job User and bigQuery Data viewer
  - [x] on ci and through firebase functions: update the functions' appspot account
           I have to wait that the table analytics be created to be sure (with test)
- [x] update staging env file: with app Id
- [x] update staging env file: with measurement id (analytics)
     - [x] Check with Max
- [x] update ci & staging & prod service account roles
     - [x] Bump Laurent with the correct roles and service accounts
- [x] do the same for CI
- [x] do the same updates for prod:
  - [x] update env file: with app Id
  - [x] update env file: with measurement id (analytics)

**Comment by Jackseed** [comment]
Done
