### ISSUE TITLE
Query summary

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#1748]
- [x] Movie Page - Sales tab #1552  (same as deal list) 
- [ ] Movie Page - Film Details tab #1624 (new query, contracts created by Max with tunnel page 9 #1419)
- [ ] Tunnel Page Summary #1747 (same as Film Details Tab above)
- [x] Film List #1549 (new one, takes tricks already made for other queries)

**Comment by Jackseed** [comment]
Done, other queries are not used anymore
