### ISSUE TITLE
Title page - last fixes

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#1923]
## UI 
[Marketplace Activity tab](https://app.zeplin.io/project/5ca741b3ed21e79faa266664/screen/5e26d365922d4d961b4b0435)
[Film Details tab](https://app.zeplin.io/project/5ca741b3ed21e79faa266664/screen/5e26d4eae6a7365468f53e91)
[Sales tab](https://app.zeplin.io/project/5ca741b3ed21e79faa266664/screen/5e26d5fc683ce156ce01990b)

### Header
- [x] Rename tab "Sales" to "Marketplace Activity" 
- [x] Rename tab "Avails" to "Sales" 
- [x] If there is no information for the header, don't display anything - not null
![image.png](https://images.zenhubusercontent.com/5c6a89ac8de1b31d5443ab99/4eba0396-61c2-401f-b574-675586f6127a)
- [x] Remove the "View Sales Reports" button
### Details tab
- [x] Add a first capital letter to Content Type > "Short" not "short"
- [ ] Show release date with MM/DD/YYY #2113 
I don't understand how you got this, the date in salesInfo.originalRelease.date is a string, not a timestamps
![image](https://user-images.githubusercontent.com/14964443/74610823-f2913180-50f6-11ea-8ada-a18de0b7f207.png)
- [x] Remove "Mandatory" in the key value Production Status Mandatory
- [ ] Freshness: display the enum value not key
![image](https://user-images.githubusercontent.com/14964443/74610891-82cf7680-50f7-11ea-9946-82bc5b2f6cbe.png)
- [x] Main Information with capital I
- [x] Running Time: add " min" after the number
- [ ] Festival: #2113
  - [ ] add a "s" Festivals 
  - [x] remove the space before the coma
![image](https://user-images.githubusercontent.com/14964443/74610921-cfb34d00-50f7-11ea-997a-30b8aa76d00b.png)
  - [ ] add a space after the coma for premieres, put a capital letter and add Premiere after so it make something like this in the example:
Cannes, Selection, 2020, International Premiere, Market Premiere, World Premiere, National Premiere
- only one festival is shown even if there is 2 or more, we need to display all by going on a new line or separate them with "|"
- [ ] Co-Production Company & Production Company:
  -  [x] "()" to remove when there is no country
![image](https://user-images.githubusercontent.com/14964443/74611637-e78dcf80-50fd-11ea-91cc-1fe95020df85.png)
  - [ ] only one is showed, if more, they should be displayed all by going on a new line or separate them with "|"
- [ ] Box office: #2113
  - [x] the key should use the territory label (an not slug) + "Box Office"
  - [ ] only one box office is shown, not all the elements from the array
  - [ ] if easy, when "Box office in $" we should display the box office value with $ pipe; same with euros and when it's # Entrances add "Entrances" after the value
For example here:
![image](https://user-images.githubusercontent.com/14964443/74611982-38eb8e00-5101-11ea-82cc-f7d03bafa5a6.png)
it becomes:
Antigua and Barbuda Box Office €10,000
France Box Office 10,000 Entrances
China Box Office $100,000
- [ ] Rating: all elements from the array should be displayed
- [ ] Film Review: nothing is displayed, all elements from the array should be displayed
- [ ] Versions are not displayed
![image](https://user-images.githubusercontent.com/14964443/74612356-f1ff9780-5104-11ea-9440-dfcce0742a09.png)
- [x] Rename Images "Promotional Images"
- [x] Rename Movie Poster for "Poster"
- [x] Rename Still Photos to "Stills"
- [x] capital L to Files & Links
- [x] Add Scenario on "Files & Links" + name of the original file
- [ ] Presentation deck should show the name of the original file #2113 
![image](https://user-images.githubusercontent.com/14964443/74612579-c41b5280-5106-11ea-8689-a2904d418661.png)

### Sales tab (ex Avails)
- [ ] Tab broken
- [ ] Remove the map
- [ ] Keep only the table if #1552 is done, or implement it

**Comment by Jackseed** [comment]
completed with #2113
