### ISSUE TITLE
Marie's prod feedback (DASHBOARD)

### ISSUE THREAD

**Issue by maltmayer** [blockframes/blockframes#2105]
- [ ] The "Dashboard" Page and "My Titles" take a lot of time to load, even with only 2 films. #2111 
- [ ] On the Film Page, in the "Film Details" tab : in "Content Type", replace "Movie" by "Feature film". #2112
- [ ] On the "Organization page", there's a cropper problem on the logo. When you want to change it, it appears completely off to the left, not centered. A big part of the image appears outside of the cropper. @jenna1k 
![image](https://user-images.githubusercontent.com/55785823/75674407-3d798000-5c85-11ea-9ab7-4c3129fd8b13.png)
- [ ] Loading problem on the Film Page, the "Marketplace Activity" cards (with the graphs) take time to appear. So it looks weird for a few seconds. #2111
![image](https://user-images.githubusercontent.com/55785823/75674432-49654200-5c85-11ea-9256-bba76b5ba50b.png)
