### ISSUE TITLE
Automatic testing

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#2313]
## Testing objects
- [ ] User
  - [x] Create an account and go on organization home page
  - [x] Verify that we cannot create an account with the wrong fields (email, name, surname, password)
  - [ ] Verify the account/profil/view: CRUD of Contact information, profile image +
  - [ ] Verify that the user can change his password ++
  - [ ] Verify that emails are sent to the user and admin ++
- [ ] Org
  - [x] Create a new account and go on find organization page
  - [ ] Verify the flow of find organization ++
     Create a user, send an invitation to an org, re-connect with a corresponding user, check member page, accept the invitation, re-connect with the first user to verify if he can access to the app  [manual test]
  - [x] Can't create an organization without fill fields correctly 
  - [x] Create an organization with minimum field (just move on congratulation page, doesn't verify if the user can navigate to the app after accept his org, admin panel ?) + 
  - [x] Create an organization with all fields (just move on congratulation page, doesn't verify if the user can navigate to the app after accept his org, admin panel ?) +
  - [ ] Organization CRUD (update fields in view/org) +  
  - [ ] Members: verify the list of members and add a new member, re-connect on this new user, test identity page and try to have access to the app ++ [manual testing]
  - [ ] Remove member, change authorization, test authorization +   (Cant remove or change permission - 07/24)

- [ ] Movie tunnel
[Corresponding issue #3419]
  - [x] Test every fields of main information
  - [x] Test every fields of storyline
  - [x] Test every fields of credits
  - [x] Test every fields of budget, quotas, critic
  - [x] Test every fields of technical information
  - [ ] Test every fields of promotional images ++    [TODO - need to add]
  - [x] Test every fields of files & links
  - [x] Test every fields of chain of titles
  - [x] Test every fields of valuation
  - [ ] Test every link on the navbar on the left ++
  - [x] Type only required fields, submit the movie, verify the title of the movie is saved on movie view (film details), verify that the movie exists and the title is good in titles list, verify the title in movie activity
    - [ ] Test trigger notification : [Member created a new movie - check notification is sent]
    - [ ] Be sure that the list of required fields is good ++
    - [ ] Verify all the information on movie view (details) +
  - [ ] After type all fields in each test, save the movie, reload the page, and verify that fields are pre-filled correctly. This also verifies that the fields are correctly saved in firestore ++
  - [ ] Verify for each test that the summary page has all the information +
 - [ ] Verify the movie submit flow: when creating a film without submit, movie has a status 'Draft' on movie list, when click on submit on the summary page, movie form is blocked (in implementation), status is 'Submitted' on movie list and click on the movie navigates to the page view instead of the form, C8 admin receives a notification, when C8 admin accepts the movie, the status is updated on the movie list and the movie is available on marketplace, if the movie is refused, the form is accessible again ++

- [x] Wishlist
  - [x] Add movie, remove movie, verify heart icon, verify wishlist from marketplace home, search, and movie view
- [ ] Deal list
   - [ ] Add some scenarios.. [Hugo] - skipped?

**Catalog Marketplace**
   - [ ] Verify the deal creation flow: when a sale is created from cart > create an offer > submit, the deal should be created on the deal list, status submitted (marketplace) and a notification triggered to the central org, the contract should appear on the deal list of the central org but not on the deal list of the sellers (dashboard), on the admin panel the contract can be accepted, while it's still submitted (and not accepted), the deal list from marketplace should redirect to the deal view, not the deal form and the deal form is blocked (not implemented), when the contract is accepted by the admin, the contract status switch to 'in negotiation' and the contract is display on the deal list dashboard of the sellers who have a movie included in the contract and a notification is triggered to inform them  
[manual test]
Check if there is a document for this..

- [ ] Deal view - in negotiation - check   :  (- in catalog marketplace if deal is created)
   - [ ] Verify that the deal view is in negotiation state (both marketplace & dashboard) ++ 
   - [ ] Verify that the deal view display only the titles of the deal owned by the seller org (dashboard) ++
   - [ ] Verify the version history - 
   - [ ] Verify that the deal view display all the titles of the deal (marketplace) ++ 
   - [ ] Verify the validation of a deal by a seller (dashboard, not implemented yet)
   - [ ] Verify the validation process of all the sellers (marketplace, not implemented yet)
- [ ] Deal view - accepted 
   - [ ] Verify that the deal view is in accepted state (both marketplace & dashboard) ++ 
   - [ ] Verify the payment monitoring process (both marketplace & dashboard + admin, not implemented yet)   

- [ ] Contract tunnel 
  -  [x] Test fields Event & period, Contract Currency, Your Selection, Offer a total Package Price, payment upon event, PAYMENT TERM, save and reload.
  - [ ] Test fields license start date, license end date, periodic payments, other. Save and reload ++
  - [ ] Your selection doesn't seem to be working properly ++
  - [ ] Test fields of exploitation rights. Save and reload ++
  - [ ] Test the summary page -
  - [ ] Submit contract and verify that the contract exists on offers and deals page ++
  - [ ] Verify that the notification is triggered on the central org
  - [ ] Connect to a seller account that owns 1 of the movie of the deal and check that there is NOT the deal in his list ++++ 
  - [ ] When the tunnel is saved and not submit, verify that the contract is in the deal list (marketplace), draft status and when clicks on the deal, leads to the tunnel, verify that the deal is only in marketplace and not dashboard (on 1 seller that owns a film of the deal) while the status is draft

- [ ] Filters (Search Page)
  - [ ] Check that all the movies expected are here ++ **(Festival)**
  - [ ] Try the more important filters of Title Media (defined this list) and verify that the list of movies is updated + **(Festival)**
  - [ ] Try the others filters of Avails and verify that the list of movies is updated -
  - [ ] Try the more important filters of Avails (defined this list) and verify that the list of movies is updated +
  - [ ] Try the others filters of Title Media and verify that the list of movies is updated - **(Festival)**
- [ ] Search bar **(Festival)**
  - [ ] Check that all the movies expected are here ++
  - [ ] Try 2 or 3 differents names and verify that the list of movies is updated +

- [ ] Cart 
  - [ ] After created an avails, test move to wishlist and remove title buttons, add an other exploitation right -
  - [ ] Create an offer and verify that fields of contract tunnel are pre-filled correctly ++
- [ ] Movie list (which movie list ?)
  - [ ] Verify that the list is good (only movie of movie.ids of orgs)

- [ ] Stats
  - [ ] Verify that dashboard home is working (page views, add to wishlist, clicks promo elements). We can verify that a number is present but not if it is good
  - [ ] Verify the titles list page is working well with a number in view stat

- [ ] Movie view - details
  - [ ] Verify the more important information (banner info) +
  - [ ] Verify information contained in this page for a complete movie -
- [ ] Movie view - avails
  - [ ] Verify the avails filters are working (scenario written @Jackseed )
  - [ ] Create an avails, select a territory, add to selection, go on selection page and verify that the avails exists in the cart ++

- [ ] Bank Server
  - [ ] Do a point with PL

- [ ] Excel import -- check this.
  - [ ] Do a point with Bruce
  - [ ] Verify that we can import movies (with good and not good excel, test mandatory fields)  ++
  - [ ] Verify that we can import deals (with good and not good excel, test mandatory fields) ++ (admin only)
  - [ ] Verify that we can import contracts (with good and not good excel, test mandatory fields)  ++ (admin only)
