### ISSUE TITLE
Editorialization - Title categories

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#2314]
## Context 
One of the best ways to sell library films is to gather them by category related to news or general mood (death of someone, Christmas, Halloween,...) . 

## Description
Categories will be created by our sale team using the admin panel, updated frequently, and showcased in marketplace homepage. 
Only part of the selection may be showcased on the homepage, the user should be able to see all of them on the title list. A button "See all" should lead to /search page with a pre-loaded search corresponding to the category. 

## Next steps: 
- [ ] Data model: Do we create a new parameter or use keywords, new collection? 
- [ ] Implementation: Add to the admin panel a way to add keyword/category to many titles at once 
- [ ] UI: choose a format to display the movies inside a category and a category on homepage
