### ISSUE TITLE
Beautify Movie Page Header

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#2316]
## Description
We want a beautiful movie page that can be used throughout the apps. We also want to re-cut the page into smaller components.  

## UI 
[Wireframes](https://www.figma.com/file/j6QCVEIFmarhgA2q9oKkXi/Buyer-Marketplace-pre-tests?node-id=89%3A0)

## Next steps
Huge amount of work:
- [ ] Define the movie page layout (video banner, movie details, movie tabs,...)
- [ ] Define the title components (different way to display the components, well size it with Mathilde & Anastasiia + list where the data come from)
- [ ] Prioritize the components
