### ISSUE TITLE
Dynamic Homepage

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#2334]
## Description
We would like the marketplace homepage to become a way to discover films by genres, categories, sales agent, box office and so on and not all the movies at once. 
For this to be effective and not too redundant, we need to break the visual rythme by using different formats to display the films. 

## Next steps
- [ ] Define the different formats and ratios we want to use (horizontal, vertical,...)
- [ ] What the assets used (banner, stills, poster, new?)
- [ ] Think of re-usable way to filter movie list (card, rectangle, circle,...)
- [ ] Create components

## UI
[Wireframes](https://www.figma.com/file/j6QCVEIFmarhgA2q9oKkXi/Buyer-Marketplace-pre-tests?node-id=1%3A434)
![image](https://user-images.githubusercontent.com/14964443/74661456-4bfd6d00-5198-11ea-8ac2-ca553784795a.png)
