### ISSUE TITLE
Buyer Preferences / Profile

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#2338]
## Description
Buyers usually use the same filters for things like
- genres
- budget range
- territories 
- medias
- TV specs (#broadcast, catch up,..).

We want to offer them a way to save these settings so the title list is automatically filtered with it. 
For now this settings will be per user but in near future they could also be share with the org. 

## Next steps
- [ ] UX: work on wireframes
- [ ] Data: make a proposition on how to store this settings 
- [ ] Component: look at what we can re-use / what needs to be created

## UI
(**WIP**) [Wireframes](https://www.figma.com/file/j6QCVEIFmarhgA2q9oKkXi/Buyer-Marketplace-pre-tests?node-id=273%3A0)
