### ISSUE TITLE
Include Comments to Contracts

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#2339]
## Description 
Parties may have custom comments to add to the contract. 

## Next steps
- [ ] Data: add a comment parameter 
- [ ] UI: update screens with a comment section
- [ ] Dev: look for a reusable text component for contract
