### ISSUE TITLE
Asking prices 

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#2348]
## Description
Allow the buyer to ask the seller for a price on a distribution deal.
Two side of the functionality:
- on buyer side, we need to update the component used in the cart to display an asking price button + result 
This also demands an update of the cart page so the buyer can select which titles he/she wants to add to the contract he will create as an offer so a title waiting for an asking price may stay on the cart waiting for it, while making another offer with other titles. 
- on seller side, we will use a new notification to allow the seller to give a price.

## Next steps
- [ ] UI: make screens update to include asking price + proposition for notification
- [ ] Dev: work with UI to be sure that the updates are possible
- [ ] Data: we surely need to update our model

## UI
(**WIP**) [Wireframes](https://www.figma.com/file/j6QCVEIFmarhgA2q9oKkXi/Buyer-Marketplace-pre-tests?node-id=356%3A6151)
