### ISSUE TITLE
[Archipel Content] Title by tile package price repartition

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#2457]
Our Mandate with right holders has evolved and plans 4 possibilities for the price repartition title by title of the package that need to be done through the application:
- [x] The buyer splits the price by himself - already done
- [ ] The buyer adds a ranking to films from A to F, A being the stronger, price is split  automatically prorata basis of the ranking (A: 6 points, B: 5,... F:1) - needs to be done #2459
- [ ] The buyer asks a price to the seller for specific exploitation rights - needs to be done #2348 
- [ ] The price is split automatically based on the ratings of the titles set at the import (from A to F) - partially done #2459

**Comment by Jackseed** [comment]
Outdated
