### ISSUE TITLE
Implement reusable components into catalog

### ISSUE THREAD

**Issue by GrandSchtroumpf** [blockframes/blockframes#2535]
# Same folder structure
Use the same folder structure & naming convention than in festival.

# Reusable components
When creating the festival app most of the component have been build to be reused, but they haven't been implemented into the catalog app. We should do it:

- [x] Inviation list
- [x] Notification list
- [x] Marketplace layout
- [x] Dashboard layout
- [x] Movie list (search): Update the input in the header
- [x] Create a unique page for notification list in their own lib
- [x] Create a unique page for invitation list in their own lib

# Same page path
Make sure the path for each page is the same in catalog & festival. Be careful with "s" at the end or not.

# Edit e2e tests
Make sure that tests are up to date after this cleaning
