### ISSUE TITLE
[Festival] Last fixes for V0 release

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#2570]
### Marketplace Homepage
- [x] Take the 3 same sections as Content with same filters & carousel
![image.png](https://images.zenhubusercontent.com/5c6a89ac8de1b31d5443ab99/28cc104b-db9d-4dd5-8a75-8e20872ed7c1)
- [x] Update the links from the carousel film pictures: c/o/marketplace/title/titleId
- [x] Update the texts (coming, ask @Jackseed)
- [x] Use the new banner image from Mathilde (used [here](https://projects.invisionapp.com/d/main#/console/19607961/413916192/preview))

### Invitations 
- [x] Copy the notification page when empty, replacing "notifications" with "invitations" in the text
![image.png](https://images.zenhubusercontent.com/5c6a89ac8de1b31d5443ab99/f1b1ca00-8def-4513-95a0-f2659ee34283)

### Marketplace All Titles
- [x] Rename Seller filter "Sales Agents" and move it as first filter (will done by #2566)

### Marketplace Wishlist
- [x] Replace the link from the wishlist films to: c/o/marketplace/title/titleId

### Marketplace Title page
- [x] Implement new header component #2352 following this UI for [data](https://projects.invisionapp.com/d/main#/console/19607961/409953096/preview) 
- [x] Copy the main info tab from Archipel Content
- [x] Add some margins to the Main info cards

### Marketplace org list
- [x] Display only the orgs with access to dasbhoard 

### Marketplace public org page
- [x] Add a mailto: org contact email address on the "Get in touch" CTA and use good style 
![image.png](https://images.zenhubusercontent.com/5c6a89ac8de1b31d5443ab99/9ddb582f-e894-4a62-a683-029b6600ad54)
- [x] Switch "Contacts" tab to 2nd position and "Screening Agenda" to 3rd
- [x] Rename Contacts "Contact"
- [x] Rename "Screenings Agenda" to "Screening Schedule"

### Dashboard homepage
- [x] Change the link for the "+" button to c/o/dashboard/import

### Dashboard import
- [x] implement the same page as Content using #2245 excel

### Dashboard My Titles
- [x] Remove the tabs and display titles anytime
- [x] Rename "New Movie +" to "Import Movies +" and change link to c/o/dashboard/import
- [x] Remove the columns Sales, Total Gross Receipts
- [x] Add the columns in that order, after # View: 
- Director(s) name (First + last)
- Production Status
- [x] Change the link from the movie item in the list to the view instead of the form

### Dashboard Activity Feed (+ Marketplace ?)
- [x] Remove "Offers and Deals" tab

### Dashboard Navbar
- [x] Remove the search bar 

### Title page
- [x] Copy the Content dashboard page
- [x] Remove Marketplace Activity tab
- [x] Remove all the links to the form

**Comment by fritzschoff** [comment]
**marketplace orgs** ref #2539 we have to wait for the data model to be ready

**Comment by fritzschoff** [comment]
```
Dashboard Activity Feed (+ Marketplace ?)
 Remove "Offers and Deals" tab
```
I guess it is already removed? @Jackseed
