### ISSUE TITLE
Be able to select image format and to crop images (like meetup does for example)

### ISSUE THREAD

**Issue by phpgeekfr** [blockframes/blockframes#287]

**Comment by Mussuranae** [comment]
- [ ] User profile picture
- [ ] Organization picture

**Comment by phpgeekfr** [comment]
Assigning this issue to @jenna1k . Have fun ;)

**Comment by Jackseed** [comment]
Implement it on 3 pages:
       - [ ] Account creation page #1104 
       - [ ] Create your org page #1120 
       - [ ] My profile page #1100

**Comment by Jackseed** [comment]
- [ ] Keep the default images for org logo & user picture while there is no image uploaded & saved by the user

**Comment by Jackseed** [comment]
Done ! > closed
