### ISSUE TITLE
Movie update - Epic

### ISSUE THREAD

**Issue by GrandSchtroumpf** [blockframes/blockframes#2956]
link to [feature branch](https://github.com/blockframes/blockframes/tree/feature/movie-form)
link to [main PR](https://github.com/blockframes/blockframes/pull/3406)

# Movie Form Pages
Create an issue for each page of the movie form following [the documentation of Anastasiia](https://docs.google.com/spreadsheets/d/1z4FFNABgDyRGgD5AQZf-ebWbA_m-7hlueFMCVUuk2fI/edit#gid=1003782809): 
- [x] Lobby 
- [x] [Production status](https://github.com/blockframes/blockframes/issues/3387)
- [x] [Main](https://github.com/blockframes/blockframes/issues/3147)
- [x] [Storyline](https://github.com/blockframes/blockframes/issues/3183)
- [x] [Production](https://github.com/blockframes/blockframes/issues/3184)
- [x] [Artistic Team](https://github.com/blockframes/blockframes/issues/3187)
- [x] [Awards](https://github.com/blockframes/blockframes/issues/3193)
- [x] [Additional](https://github.com/blockframes/blockframes/issues/3194)
- [x] [Technical](https://github.com/blockframes/blockframes/issues/3196)
- [x] [Materials](https://github.com/blockframes/blockframes/issues/3198)
- [x] Promotion
- [ ] Summary

# Model/forms
- [ ] [Update form static value](https://github.com/blockframes/blockframes/issues/3478) > frozen for now

# Movie View Pages
After implementation of the new movie form and merge of the feature branch, movie views will have to be updated. First create dedicated issues for these pages and then implement it.
- [ ] Dashboard view
- [ ] Marketplace view

# Merge
[Time to merge to develop ;)](https://github.com/blockframes/blockframes/issues/3596)

# Tests
After each update, e2e tests should be updated accordingly
- [ ] [Movie form](https://github.com/blockframes/blockframes/issues/3419)
- [ ] Dashboard view
- [ ] Marketplace view

# Debug

# Issue structure
Use the Component issue template to structure the issue.
Specify in which production state / app the page should be used.
For each field, specify the component to use [following this documentation](https://www.notion.so/cascade8/How-the-type-defines-the-component-5973724c1beb4a23bbd5f742da0b6246#e3afc819cc0a49c78c968fae8012f68d).
Open a discussion on slack when the expected component doesn't match current data-model.
Once done, add a link to the issue in this one.

**Comment by joanofdart** [comment]
Issue Main - #3141

**Comment by GrandSchtroumpf** [comment]
Let's keep it open as a reference of all the issues.
