### ISSUE TITLE
Media Lib global issue

### ISSUE THREAD

**Issue by pldespaigne** [blockframes/blockframes#3084]
This issue is for tracking the global state of the Media lib.

<details>
  <summary>

Old closed issues

  </summary>

 - [x] finish UploadWidget #3002 
 - [x] finish & merge already opened PR about form #3038 
 - [x] small UX imporvement : adding original file names fro cropped images to the upload widget #3110 
 - [x] create a `libs/media` #3085
 - [x] handle every media type #3088
 - [x] refactor the backend onUpload & onDelete storage functions #3109
 - [x] refactor the movie model to remove arrays #3179
 - [x] Refactor poter & banner #3239
 - [x] Extract medias from Movie/Org/User forms #3229
 - [x] Create a HostedMediaFormList #3230
 - [x] Migration script #3096
 - [x] Test & merge back #3195
 - [x] unit test the `media.service` #3087
----------------------
</details>

-
- [ ] handle media download (like for the excel import) #3091 
-
- [ ] Storage Rules #3188
- [x] Storage Ops #3282 
-
- [x] Transition to ImgIx #3283 
- [x] Clean Movie Medias #3291

### Bugs
- [x] Fix upload widget #3267 
- [x] form re-submit bug #3327 

<details>
  <summary>Don't open me</summary>
  <img src="https://thumbs.gfycat.com/MisguidedPreciousIguanodon-max-1mb.gif" /><br>
   I've told you
</details>

**Comment by pldespaigne** [comment]
Closing because this master issue is not useful anymore
- Storage Rules #3188 is still in progress
- Images Excel import #3091 is frozen for now
