### ISSUE TITLE
Big Media Refcatoring

### ISSUE THREAD

**Issue by pldespaigne** [blockframes/blockframes#3197]
This issue is just a group of the following issues :

- [x] handle every media type #3088
- [x] refactor the backend onUpload & onDelete storage functions #3109
- [x] refactor the movie model to remove arrays #3179

link to master issue #3084
