### ISSUE TITLE
Debug release 1.8

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#3412]
## Dashboard homepage
- [x] Update the message when the user has no movie, there are 2 cases:
1. Case when the org has really no movie on the festival app (they could have some on another app). To check that, search for `storeConfig.appAccess.festival: true` inside the movies included into org `movieIds`. If there is none, then display the same message as the screenshot (= don't change a thing):
![image](https://user-images.githubusercontent.com/14964443/88951428-3e472a00-d296-11ea-8036-b942b4ba02f5.png)
2. Case when the org has created draft movies on the festival app, but none are validated. To check that, search for `storeConfig.appAccess.festival: true` inside the movies included into org `movieIds` and then verify `storeConfig.status`, if there is at least 1 film with `appAccess: festival` to `true` but none of them have a `storeConfig.status` to `accepted`, then change the message for:
Title: "You have no title on the marketplace yet."
Subtitle: "As long as you have no title to display, your organization will not appear on the marketplace. To import titles, you can either add several titles at once through bulk import, or just one at a time by filling in the platform's form. N.B.: Only submitted projects will appear on the marketplace, not drafts. "
**adding a line break after each sentence on subtitle**

## Marketplace homepage
- [x] **See comment from RemcoSimonides**. The section "Featured Sales Agents", don't display ALL the sales agents, use the same query used in `/c/o/marketplace/organization`, i.e. sales agents that have at least 1 film published on the marketplace:
- org with `appAccess.festival.dashboard: true`
&& 
- movieIds including at least 1 movie with `storeConfig.appAccess.festival: true` && `storeConfig.status: accepted`
![image](https://user-images.githubusercontent.com/14964443/88957223-d9440200-d29e-11ea-87e6-fcca3f4333d7.png)

- [x] @RemcoSimonides There is a missing background image to add:
![image](https://user-images.githubusercontent.com/14964443/88954305-78b2c600-d29a-11ea-9d5c-cbf0ade44102.png)
vs [Invision](https://projects.invisionapp.com/d/main?origin=v7#/console/19607961/413926229/preview?scrollOffset=4187.77783203125)
![image](https://user-images.githubusercontent.com/14964443/88954286-6cc70400-d29a-11ea-8860-e2c884aa000c.png)
**/!\ Beware Safari, don't forget the fallback** 

### Featured seller component
- [x] Add the right padding/margin between logo and org name + org films:
![image](https://user-images.githubusercontent.com/14964443/88955591-66398c00-d29c-11ea-91f1-f514cdacb927.png)
vs
![image](https://user-images.githubusercontent.com/14964443/88955336-122ea780-d29c-11ea-8f9b-7cb7b878aca4.png)
- [x] @RemcoSimonides  Use the correct number of films on the featured seller component 
here 
![image](https://user-images.githubusercontent.com/14964443/88955723-98e38480-d29c-11ea-99c2-73016a23be02.png)
and here 
![image](https://user-images.githubusercontent.com/14964443/88955732-9d0fa200-d29c-11ea-880b-fe172e059bc1.png)
It should count all the films from the org `movieIds` with these parameters:
- `storeConfig.appAccess.festival: true`
&&
- `storeConfig.status: accepted`
- [x] Unfortunately comment that component for now, until #3413 is done

## Footer
- [x] Remove (or debug) "Contact us" from the footer and please warn the person who implemented it that it doesn't work (it's always removed then added again, then..)

## Wishlist
- [x] Buggy wishlist with user bdelorme+users-1411@cascade8.com / blockframes on https://staging.archipelmarket.com/c/o/marketplace/wishlist, generating that error on Sentry: https://sentry.io/organizations/cascade-8/issues/1813066880/?referrer=slack
![image](https://user-images.githubusercontent.com/14964443/88958919-71db8180-d2a1-11ea-9f2d-6496f985e263.png)

- [x] When you go from org public page on marketplace (e.g. `/c/o/marketplace/organization/e1VXeusNJK6pb8kmVnUn/title`) and then on wishlist only the films from that sales agents + included in your wishlist are visible.
Here with same user as above after going to Pulsar:
![image](https://user-images.githubusercontent.com/14964443/89102185-fa276700-d406-11ea-991c-5a61ec6c34c1.png)

## Public org list (`/c/o/marketplace/organization`)
- [x] @RemcoSimonides  Use the correct number of films on the featured seller component (#3308 )
It should count all the films from the org `movieIds` with these parameters:
- `storeConfig.appAccess.festival: true`
&&
- `storeConfig.status: accepted`

### Filters
- [x] Add same right padding than left padding on a filter so the text should be alway inside the button, centered and with space between text & borders
![image](https://user-images.githubusercontent.com/14964443/88959817-e5ca5980-d2a2-11ea-8fbd-1b4eb9f4e7a8.png)
- [x] When hovering the filters, add a background to the arrows so the user may see it
![image](https://user-images.githubusercontent.com/14964443/88960041-32159980-d2a3-11ea-9b4a-280d4dfe273c.png)
use the same as on marketplace homepage:
![image](https://user-images.githubusercontent.com/14964443/88960061-3d68c500-d2a3-11ea-867f-31a44b66a63f.png)
- [x] Add color to the filter when it's selected so the user understands what is active (check with @stephanie-cascade8 what's better)
- [x] Add a tooltip to this button "Clear all filters", check with @stephanie-cascade8 if this icon is the correct one - (Remco: Added Tooltip to the button #3456 , waiting for Stephanie to submit new icon for button)
![image](https://user-images.githubusercontent.com/14964443/88960414-bd8f2a80-d2a3-11ea-97df-77b38e1c561f.png)

### App search bar
- [x] @RemcoSimonides - see PR #3461 for more info - On top of #3355, top search bar that should appear when you scroll down doesn't appear if you do this flow:
1. go on all films
2. go on a public org page (e.g. `c/o/marketplace/organization/GdFUevWIifjk6VEYgfCT/title`)
3. go back on the page all films. Don't know why but the 2 look linked...
![image](https://user-images.githubusercontent.com/14964443/89102416-4378b600-d409-11ea-8686-de556688ba15.png)

### **Safari**
- [x] The top banner looks like missing a fallback, it's blank on Safari 
![image](https://user-images.githubusercontent.com/14964443/89102267-cbf65700-d407-11ea-8158-c485d823b6cd.png)
- [x] Maybe the same bug but when you scroll down, the filters has no background on Safari
![image](https://user-images.githubusercontent.com/14964443/89102307-1f68a500-d408-11ea-8531-4a513a9825b4.png)

## Marketplace film page
- [x] Film banner takes too much height, we should at least see the tabs below without scrolling down. Check with @stephanie-cascade8 the correct height
- [x] Black to transparent overlay is missing on this banner too
![image](https://user-images.githubusercontent.com/14964443/89102242-673afc80-d407-11ea-950d-81033ef746b5.png)

## Invitations
- [x] Add 3 dots when the text is too long (more than 100 characters) 
- [x] The invitation status is missing (pending / accepted / refused)
![image](https://user-images.githubusercontent.com/14964443/89102072-ff37e680-d405-11ea-94e6-7fa1cf160753.png)

## Imgix
- [x] Remove the "enhancement" filter (@pldespaigne knows ;))

**Comment by RemcoSimonides** [comment]
Regarding the first to do of Marketplace Homepage about only showing organizations with at least 1 accepted movie; 
It is quite a lot of work for a small fix to implement this because there are some changes needed to the data model in order to implement this efficiently; namely movie needs to contain an array of organization ids so then this query can be used; `movieService.valueChanges(ref => ref.where('orgs', 'array-contains', orgId).where('status', '==', 'accepted'));`

**Comment by pldespaigne** [comment]
That ☝️  seems overly complicated, we can probably make a tiny simple change to the data model or just use algolia instead

**Comment by Jackseed** [comment]
@RemcoSimonides the query asked is something already implemented on the public organization list (`/c/o/marketplace/organization`).
Can you have a look and update me on whether it's possible to do the same filter on marketplace homepage or not ?

**Comment by phpgeekfr** [comment]
> Regarding the first to do of Marketplace Homepage about only showing organizations with at least 1 accepted movie;
> It is quite a lot of work for a small fix to implement this because there are some changes needed to the data model in order to implement this efficiently; namely movie needs to contain an array of organization ids so then this query can be used; `movieService.valueChanges(ref => ref.where('orgs', 'array-contains', orgId).where('status', '==', 'accepted'));`

I was not able to find the existing issues about this, so I created a new one : 
https://github.com/blockframes/blockframes/issues/3498

**Comment by Jackseed** [comment]
Some new stuff found on prod, not sure if it's still there but it should.
### Invitations
- [ ] On dashboard, when you receive an invitation to an event which is not yours and click on the more details button, the user is redirected to the dashboard view of the event as it was his/her own. It should redirect to the marketplace event view instead.
To avoid too many use cases every invitations (even for your events) should redirect to the marketplace view of the event.
Here the dashboard event view: 
<img width="1431" alt="Capture d’écran 2020-08-20 à 15 37 18" src="https://user-images.githubusercontent.com/14964443/90778988-9acdc000-e2fd-11ea-98f4-0b5b74fc34ba.png">

### Marketplace movie page
- [ ] Looks like artistic crew data doesn't show up even if it's filled in
<img width="1055" alt="Capture d’écran 2020-08-20 à 15 14 16" src="https://user-images.githubusercontent.com/14964443/90779203-d6688a00-e2fd-11ea-8f6d-d9e92214ced7.png">

**Comment by xmano** [comment]
### Adding a section for missing images and labels

#### In multiple import (https://staging.archipelmarket.com/c/o/dashboard/import)
![image](https://user-images.githubusercontent.com/8731418/90789077-16426800-e324-11ea-8ba5-ed495034f7d4.png)

**Comment by RemcoSimonides** [comment]
After accepting an invitation to an event from someone else (same organisation), I received a notification that I accepted the invitation. Isn't the expected behavior to send the notification to the person who sent it?

![image](https://user-images.githubusercontent.com/27687382/90790029-de2d2c00-e307-11ea-8dde-9c8b52ceec3a.png)

**Comment by Jackseed** [comment]
> * [ ]  After accepting an invitation to an event from someone else (same organisation), I received a notification that I accepted the invitation. Isn't the expected behavior to send the notification to the person who sent it?
> 
> ![image](https://user-images.githubusercontent.com/27687382/90790029-de2d2c00-e307-11ea-8dde-9c8b52ceec3a.png)

If it's same organisation that's the intended behaviour, the notification of acceptation / refusal of an event is sent organization-wide since it could be many persons monitoring the same event

**Comment by Jackseed** [comment]
- [ ] Blank page on safari after connexion on archipelmarket 
I got this linked sentry error: https://sentry.io/organizations/cascade-8/issues/1850762573/?project=1540126&referrer=slack
![Capture d’écran 2020-08-20 à 18 20 43](https://user-images.githubusercontent.com/14964443/90798552-5dbff880-e312-11ea-890d-6a949ee51342.png)

**Comment by Jackseed** [comment]
- [ ] Empty wishlist with user bdelorme+users-392@cascade8.com 
It works with user bdelorme+users-565@cascade8.com
Linked sentry error: https://sentry.io/organizations/cascade-8/issues/1813066880/?referrer=slack
![Capture d’écran 2020-08-20 à 18 26 40](https://user-images.githubusercontent.com/14964443/90798818-b68f9100-e312-11ea-8bd2-d4e39915b0c6.png)
![Capture d’écran 2020-08-20 à 18 28 27](https://user-images.githubusercontent.com/14964443/90799022-f8203c00-e312-11ea-9f64-71a76afe6f72.png)

**Comment by Jackseed** [comment]
- [ ] Screening list (https://staging.archipelmarket.com/c/o/marketplace/event) displaying nothing while there are 3 events created 
![Capture d’écran 2020-08-20 à 18 32 28](https://user-images.githubusercontent.com/14964443/90799448-85639080-e313-11ea-8f3e-49d27dc19922.png)

![Capture d’écran 2020-08-20 à 18 31 26](https://user-images.githubusercontent.com/14964443/90799404-7a106500-e313-11ea-83a5-02d7fbd2a7a1.png)

**Comment by Jackseed** [comment]
- [ ] Links from invitations (https://staging.archipelmarket.com/c/o/marketplace/invitations) lead to a blank page while the same link used from the calendar (https://staging.archipelmarket.com/c/o/marketplace/event/calendar) is working ... oO
Got this error from sentry: https://sentry.io/organizations/cascade-8/issues/1850787071/?project=1540126&referrer=slack
![Capture d’écran 2020-08-20 à 18 35 23](https://user-images.githubusercontent.com/14964443/90799731-f0ad6280-e313-11ea-94e9-daedb8f90cb3.png)

**Comment by Jackseed** [comment]
- [ ] Can't import excel for films (https://staging.archipelmarket.com/c/o/dashboard/import), I got the message "Your file is ready, it will be uploaded when you click on "Save"." but no save button and "Start import" is disabled
![Capture d’écran 2020-08-20 à 18 40 07](https://user-images.githubusercontent.com/14964443/90800254-b8f2ea80-e314-11ea-9ea9-39ce3458f224.png)

**Comment by Jackseed** [comment]
- [ ] Wrong invitation when a user request to join an organization:
- "Go to event" action should be renamed "More details" to be generic 
- "Go to event" action should redirect to https://staging.archipelmarket.com/c/o/organization/e1VXeusNJK6pb8kmVnUn/view/members when it's an invitation for organization and to https://staging.archipelmarket.com/c/o/dashboard/event/gST9ZDOPoWoYBuXUeVEW/edit when it's an event (and you are the organizer receiving a request)
![Capture d’écran 2020-08-20 à 18 42 42](https://user-images.githubusercontent.com/14964443/90800872-84336300-e315-11ea-8451-8f2228e4fb74.png)

**Comment by Jackseed** [comment]
- [ ] Acceptation to an org email doesn't display org name properly; it's working as intended when sending the request
![Capture d’écran 2020-08-20 à 18 54 04](https://user-images.githubusercontent.com/14964443/90801772-9f52a280-e316-11ea-8ed7-59a528c1c13a.png)
![Capture d’écran 2020-08-20 à 18 53 40](https://user-images.githubusercontent.com/14964443/90801792-a4175680-e316-11ea-869a-9a49bf1e3b99.png)

**Comment by maltmayer** [comment]
- [ ] IFCIC logo is down on the landing page
![image](https://user-images.githubusercontent.com/55785823/91036359-79274e00-e607-11ea-9b15-a7516e946692.png)

**Comment by Jackseed** [comment]
- [ ] Calendar icon from marketplace navbar doesn't work on Safari

**Comment by Jackseed** [comment]
- [ ] Profile image not updating on the navbar nor https://staging.archipelmarket.com/c/o/marketplace/organization/sLchj1Ib4Cxhwr0ZBW4m/member
![Capture d’écran 2020-08-25 à 18 53 06](https://user-images.githubusercontent.com/14964443/91204393-5038b300-e704-11ea-82a1-286e7c21fa12.png)

**Comment by Jackseed** [comment]
> * [x]  Can't import excel for films (https://staging.archipelmarket.com/c/o/dashboard/import), I got the message "Your file is ready, it will be uploaded when you click on "Save"." but no save button and "Start import" is disabled
>   ![Capture d’écran 2020-08-20 à 18 40 07](https://user-images.githubusercontent.com/14964443/90800254-b8f2ea80-e314-11ea-9ea9-39ce3458f224.png)

I still face this issue 
![Capture d’écran 2020-08-25 à 18 58 56](https://user-images.githubusercontent.com/14964443/91204945-0b614c00-e705-11ea-92f8-ede6f547ae75.png)

**Comment by Jackseed** [comment]
- [ ] Marketplace homepage: verify the "in production" caroussel: it's not displayed on staging but it is on prod and draft films are displayed > it should be only accepted films here

**Comment by Jackseed** [comment]
- [ ] User request to join an org not displaying correctly
![Capture d’écran 2020-08-25 à 19 04 55](https://user-images.githubusercontent.com/14964443/91205475-eae5c180-e705-11ea-80cf-d2831124aa97.png)

**Comment by RemcoSimonides** [comment]
> * [ ]  Marketplace homepage: verify the "in production" caroussel: it's not displayed on staging but it is on prod and draft films are displayed > it should be only accepted films here

Movies shown in the carousel "in production" (and all other sections) indeed only shows accepted movies. And only when there are minimally 4 movies in this state.

**Comment by RemcoSimonides** [comment]
> * [ ]  Profile image not updating on the navbar nor https://staging.archipelmarket.com/c/o/marketplace/organization/sLchj1Ib4Cxhwr0ZBW4m/member
Seems to be working for me on; staging and local on Safari 11, Safari 13, Brave. What special did you do here Vincent?

**Comment by phpgeekfr** [comment]
- [ ] changing user role within org does not work on CRM app 
![image](https://user-images.githubusercontent.com/1194344/91300229-3a2dff80-e7a3-11ea-81ac-fc8019fa8ce2.png)
![image](https://user-images.githubusercontent.com/1194344/91300259-444ffe00-e7a3-11ea-9afd-b7c959021699.png)

**Comment by RemcoSimonides** [comment]
Issues related to older versions of Safari continue here: https://github.com/blockframes/blockframes/issues/3580
