### ISSUE TITLE
Release 1.8 - Epic

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#3470]
# Context
Release 1.8 will include a cleaning script for the existing data, imgix implementation and a bunch of new components (featured sellers, filters on all films page,..).
The new components are already implemented, the cleaning script is being finished and tested and some bugs are still there to be fixed. 
This epic will gather the related issues to be completed before a complete release. 

**Release is planned for Wednesday 26th 9:30am.**

# Next steps
- [x] [Cleaning script ](https://github.com/blockframes/blockframes/issues/3066)
- [ ] [Debug already listed bugs](https://github.com/blockframes/blockframes/issues/3412)
- [ ] [Greenlight existing e2e tests](https://github.com/blockframes/blockframes/issues/3300)
- [ ] [E2E Regression : tests fail due to change in database entries](https://github.com/blockframes/blockframes/issues/3496)
- [ ] [add unit tests to build-and-test ci process](https://github.com/blockframes/blockframes/issues/3569)
- [x] [Staging tests](https://github.com/blockframes/blockframes/issues/3480)
- [x] Last debug if necesseary 
- [x] Release

Other issues:
- [ ] [Change initialization of unit test methods ](https://github.com/blockframes/blockframes/issues/3479)
- [x] [[STAGING] Cannot navigate to some pages on crm app ](https://github.com/blockframes/blockframes/issues/3390)
- [ ] [remove syncUsers patch that checks for dupe user emails in backend-ops ](https://github.com/blockframes/blockframes/issues/3514)
- [ ] [Optimize "clear and restore" DB process ](https://github.com/blockframes/blockframes/issues/3512)
- [x] [changing user role within org does not work on CRM app ](https://github.com/blockframes/blockframes/issues/3552)
- [x] [Force deletion/update of firestore indexe when pushing to production / staging](https://github.com/blockframes/blockframes/issues/3561)
- [x] [do not remove outdated invitations to events](https://github.com/blockframes/blockframes/issues/3564)
