### ISSUE TITLE
Media Financiers - Foundations

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#3589]

**Comment by GrandSchtroumpf** [comment]
# Marketplace

## Home
- [ ] : Add a `<ng-content></ng-content>` for the action on the movie-card
- [ ] : Add "cinema investing guide" in assets
- [ ] : Don't do the query on directors

## Movie List
- [ ] : Create a filter with social Goal

## Organization List
- [ ] : Create a filter with country

## Movie view
- [ ] : Add Project funding below the router-outlet
- [ ] : "Invest in this project" link the movie/:movieId/partner" page
- [ ] : Use standard main page
- [ ] : Partner page: "Get recoupment estimates" -> send a mail
