### ISSUE TITLE
DevOps Summary Issue

### ISSUE THREAD

**Issue by george43g** [blockframes/blockframes#3601]
## Devops Task Tracker
The purpose of this issue is to keep track of DevOps related tasks that need to be completed, and upcoming PRs.

Each task will have an associated priority, use case and ETA. The tasks should also be ranked and prioritised, and segmented by long-term, short-term, small and large. A "quick" task should be able to fit in one PR or day.

**Task Name (or #Issue/#PR) - Description - Time Estimate - Purpose/Use (why?)** 
_(try to fit on one line)_

A low priority task is not done while there are higher priority tasks available, or it is moved into the high priority queue once it is more urgent. Bigger tasks can be broken down into smaller ones over time before they are moved into the PR queue (agenda).

---

# Agenda (PRs)

- [ ] Plan PRs - create this issue - 1hr - to keep track of work/PRs
- [ ] Merge #3588, #3595 - fix any remaining issues - 1hr - to refactor code for simplicity/reliability
- [ ] #3583, #3598 - update Notion documentation - 30mins - to provide additional info requested
- [ ] Present this - devops issue summary - 1hr - for collaboration with management

## Quick & High Priority

- [ ] #3583, #3598 - update Notion documentation - 30mins - to provide additional info requested
- [ ] #3188 - update storage rules - 30m-2h - to keep data secure

## Long & High Priority

- [ ] Improve Backup System - 4-8h - to make backups secure and reliable
- [ ] improve release/deploy process - ? - to make deploys less error prone & automated
- [ ] #2531 - move production resources to europe - 2-3h - comply with regulations & improve speed
- [ ] #3076 - clear out old devops issue - 10m - cleanup
- [ ] Firebase Functions - organise/refactor backend-functions & `skipInMaintenance` - 10h - reduce technical debt

## Quick & Low Priority

- [ ] #3258, #3245 - move daily db backup away from zapier - 30m - to reduce points of failure
- [ ] #3075 - make env simpler & easier - 4h - to reduce errors and simplify dev setup
- [ ] #3162 - utilizing gsutil for storage/firestore xfers/backups
- [ ] #3162, #3471, #3512 - factoring out firestore backup/restore or removing jsonl
- [ ] Serve e2e - configure serve command for e2e tests in angular.json - 10m - easier testing
- [ ] #3162- only store latest storage backup
- [ ] Git-cz - implement conventional changelog & `semantic-release` - more meaningful git commits & changelog 
- [ ] #3569 - add unit tests to build-and-test ci process - 1h - to catch more bugs
- [ ] #3514 - remove syncUsers dupe check - 5m - clean code

## Long & Low Priority

- [ ] #3529 - cypress plugins to fetch fixture data and authenticate users - 4hrs - to make e2e testing more robust
- [ ] Improve angular.json - more scripts/commands and update old ones (eg: unit testing) - 2h - easier development
- [ ] #3162 - improve anon-db script/new format - 4h - for better golden data
- [ ] #1452 - better integrate firestore emulator - ? - aid in faster development devX
