### ISSUE TITLE
[Meetings] Video conference 

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#3608]
_link to master issue #3639_

## Issues

- [x] Get Twilio Access Token #3754
- [x] Setup Twilio API Key and Configuration #3755 (@pldespaigne)
- [ ] Seller joins a Meeting #3756
- [ ] Buyer joins a Meeting #3757
- [ ] Visualise participants in the Meeting #3758

---
# Business section
## Context
Video conference will enable sales agents to meet with buyers in order to showcase their new films and trailers. Most of the time meetings will gather 2 people but it could go up to 5 to 10 in some cases. 

This feature is integrated with other already existing ones, and new to come:
- All users have a calendar filled with their org events (meetings & screenings);
- Only sales agents can create an event (dashboard side of the app);
- Sales agents can invite existing or new users to an event, only invited users can access the url `/c/o/marketplace/event/eventId/session` on time and date for private events;
- Currently meetings use an external link for people to gather and talk.

New ones:
- Meeting events should offer in-app video conference on `/c/o/marketplace/event/eventId/session`;
- Meetings also enable users to showcase video, images and pdf displayed **directly** on each user browser or at least buyer browser (directly meaning not with a share screen feature to avoid bad screening quality)

## Objective
This issue is about creating in-app video conference for users.

## User scenarios 
1. Creation of a meeting
_Sales agent_
- a sales agent user connects to her/his dashboard
- s/he clicks on "My events"
- selects the correct time and date on her/his calendar 
- selects Meeting as event type
- clicks on More details 
- adds all the corresponding info to the event form > a video call link `/c/o/marketplace/event/eventId/session` should be automatically created and displayed on the "Link to a video call" input for s/he to share
- adds her/his guest email addresse(s)
- clicks on send invitation
- clicks on save the event

2. Acceptation of a meeting
_Invited Buyer_
- a buyer user receives an invitation email
- if s/he doesn't have an account, s/he receives credentials to create it > creation flow
- if s/he already has an account, the links redirects to the marketplace
- s/he connects
- has a pending invitation on navbar
- clicks on invitation
- accepts / refuses the invitation
- if s/he accepts, the event is added to her/his calendar
- off-app: adds the event to her/his calendar

3. Meeting
_Attendees_
- on correct time and date, attendees connect to the plateform
- click on calendar
- click on the event 
- redirect to the event view
- click on "Start the meeting" CTA
- redirect to the event session 
- visio conference is launched 
- the session should stay open for a minimum of the calendar duration of the meeting and stays open as long as there is someone connected to the session. 

## Usage of the feature
The feature will be mainly use on desktop web browser, especially Chrome and Safari. A call should last between 30min to 1h, including 10 to 20min of video sharing. Most meetings will host a pdf document for the sales agent to show its new film line-up.

**Comment by GrandSchtroumpf** [comment]
# Technical section

## Select the software
- [ ] : Select the right software that can run on a modern browser (IE excluded). Ex: [Twilio Video](https://www.twilio.com/video), [Jisti](https://jitsi.org/) , vanilla WebRTC, ...
- [ ] : Solution selected should work across the world without the need of a VPN (P2P solutions can be blocked in some countries).
- [ ] : Solution selected should be used by every developer in the team (avoid licenses with expensive price / dev).
- [ ] : Create a PoC, using a simple angular application & a firebase project, that demonstrates how the solution works.

## Design
- [ ] : Describe your solution to the design team for them to understand how it can be integrated in the app.
- [ ] : Review design to validate it can be implemented.

## Integration inside Blockframes
- [ ] : **Datamodel**: update the data model of the meeting "event" document to store the room reference for the call.
- [ ] : **Security**: using the "invitation" document, only invited users should be able to access the room (you might need to mint a token for that).
- [ ] : **Coud Function** : If any token need to be minted, do it under the app "backend-functions".
- [ ] : **Component**: Create a component in the "media" library that wrap the video tag & take care of the logic.
- [ ] : **Page**: Create a new page on "festival" app, section "dashboard/event" to host a meeting event.
- [ ] : **App**: Integrate this component inside the "festival" app section dashboard & marketplace.

## Test
- [ ] : Write E2E test that open an RTC connection using your solution.
- [ ] : If any backend code is required, unit test it.

## Documentation
- [ ] : Write an article on our notion group to explain how to integrate this solution with the rest of the team.
