### ISSUE TITLE
Festival Team Master Issue

### ISSUE THREAD

**Issue by pldespaigne** [blockframes/blockframes#3639]
### Specific Issues To do
_You are encouraged to create your own issues and link them here_

### Future Improvements
- [ ] Meetings future improvements #4333

---

### Done
- [x] lots and lots of design fix (@RemcoSimonides)
- [x] Meeting Bug Tracker #4393 (@pldespaigne)
- [x] Meeting is over Page #4156 (@pldespaigne)
- [x] Session guard (@pldespaigne)
- [x] Request access to app (@RemcoSimonides)
- [x] Video Room (@pldespaigne)
- [x] Lobby video preview (@pldespaigne)
- [x] Improvements on upload heavy file on storage #3831 (@phpgeekfr)
- [x] Check Invitations & Notifications #3958 (@RemcoSimonides)
- [x] Integrate Org file Upload in the app #3943 (@RemcoSimonides & @pldespaigne)
- [x] Create JWPlayer component #3820 (@RemcoSimonides)
- [x] Implement pdf Viewer #4072 (@pldespaigne)
- [x] Add upload video to the movie form #3957 (@pldespaigne)
- [x] Rework the file selector component #3947 (@pldespaigne )
- [x] Add a Lobby page #3948 (@pldespaigne)
- [x] Full screen for Video & PDF #3945 (@pldespaigne)
- [x] Rework Media list select #3946 (@RemcoSimonides)
- [x] Remove meeting real-time shared state from the firestore #3748 (@pldespaigne)
- [x] Update Edit meeting form #3944 (@RemcoSimonides)
- [x] Create the video viewer #3688 (@pldespaigne)
- [x] Create the pdf viewer #3693 (@pldespaigne )
- [x] Create the image viewer #3760 (@pldespaigne )
- [x] Remove meeting from release 1.9 #3864 (@pldespaigne)
- [x] Create the Media Controls #3686 (@pldespaigne)
- [x] Upload film files to firebase storage for screenings #2586 (@phpgeekfr)
- [x] Update file selector with org level files #3727 (@pldespaigne)
- [x] Limit meeting to 9 persons #3752 (@pldespaigne)
- [x] Org Media Form #3678 (@phpgeekfr)
- [x] Create a meeting file list #3742 (@pldespaigne)
- [x] Create a file selector component #3672 (@pldespaigne)
- [x] Create or debug the meeting page that can be accessed by authorized users #3671 (@pldespaigne)
- [x] Secure storage with rules #3188 (@phpgeekfr)

link to DevOps issues #3601

**Comment by pldespaigne** [comment]
🎉
