### ISSUE TITLE
Edit Meeting Page

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#3677]
The user should be able to select/edit/delete a list of files to share during the meeting
- [x] Create a file selector component #3672 (@pldespaigne)
- [x] Limit meeting to 9 persons #3752 (@pldespaigne)
- [x] Update file selector with org level files #3727 (@pldespaigne)
- [x] Update Edit meeting form #3944 (@RemcoSimonides)
- [x] Rework the file selector component #3947 (@pldespaigne)

link to master issue #3639
