### ISSUE TITLE
Media Sharing

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#3679]
- [x] Create a meeting file list #3742
- [x] Create the Media Controls #3686 
- [x] Create the video viewer #3688
- [x] Create the pdf viewer #3693
- [x] Create the image viewer (just a static image, can implemented at root media viewer component level) #3760
- [x] Remove meeting real-time shared state from the firestore #3748 (@pldespaigne)
- [x] Rework Media list select #3946 (@RemcoSimonides)
- [x] Full screen for Video & PDF #3945 (@pldespaigne)
- [x] Check Invitations & Notifications #3958 (@RemcoSimonides)
- [x] Add a Lobby page #3948 (@pldespaigne)

link to master issue #3639
