### ISSUE TITLE
Meeting - TS - Get Twilio Access Token

### ISSUE THREAD

**Issue by OmarSebouai** [blockframes/blockframes#3754]
# ToDo

* [x] Edit .env template (sample.env)
* [x] Add Twilio SID, ApiKey and ApiSecret to environment
* [x] Create twilio.ts and add getAccessToken function
* [x] Verify if user belong to meeting before generating Twilio Token
* [x] Add twilio functions in main.ts
* [ ] Add Unit Test using Jist

# DoD
- Use Angular Material for components
- Use Cascade8 icons (available in code assets/icons)
- Unit Test using Jest
- Inline Documentation
- Feature documention in Notion
- Akita NgFire
- Deployment Test OK
- Unit Test using Jest
- Exception management and log using Sentry
- Inline Documentation
- Strong type, add security in rules, always callback
- Code follow Cascade8 Guidelines (see exemple)
- MR done

link to epic #3608
