### ISSUE TITLE
Meeting - US - Seller joins a Meeting

### ISSUE THREAD

**Issue by OmarSebouai** [blockframes/blockframes#3756]
# Statement

As a Seller, I want to join a Visio Call Meeting so that I can see the other Buyers.

# ToDo

* [ ] Request Twilio access token and join room
* [ ] Tields view is the default view
* [ ] Get all participants name and organization
* [ ] Add mock UI if user camera isn't activated (with Name + Firstname initials)
* [ ] Show translucent frame with Name/Lastname under participants
* [ ] Add component to dashboard

# Out of Scope
* Add Video Settings (link video settings ticket here)
* Add View switch button (link View Switch ticket here)
* Add Participants button (link Participants ticket here)

# DoD
- Use Angular Material for components
- Use Cascade8 icons (available in code assets/icons)
- Unit Test using Jest
- Inline Documentation
- Feature documention in Notion
- Akita NgFire
- Deployment Test OK
- Unit Test using Jest
- Exception management and log using Sentry
- Inline Documentation
- Strong type, add security in rules, always callback
- Code follow Cascade8 Guidelines (see exemple)
- MR done

link to epic #3608
