### ISSUE TITLE
Meeting - US - Buyer joins a Meeting

### ISSUE THREAD

**Issue by OmarSebouai** [blockframes/blockframes#3757]
# Statement

As a Buyer, I want to join a Visio Call Meeting so that I can see the other the Seller and the other Buyers.

# ToDo
* [ ] Request Twilio access token and join room
* [ ] Add View switch button (link View Switch ticket here)
* [ ] Vignette view is the default view (link Vignette view ticket)
* [ ] Add Video Settings (link video settings ticket here)
* [ ] Buyer Video Settings are rolled up by default

# Out of Scope
* Add Participants button (link Participants ticket here)
* Get participants name from DB (using Participant Identity)
* Add mock UI if user camera isn't activated (with Name + Firstname initials)

# DoD
- Use Angular Material for components
- Use Cascade8 icons (available in code assets/icons)
- Unit Test using Jest
- Inline Documentation
- Feature documention in Notion
- Akita NgFire
- Deployment Test OK
- Unit Test using Jest
- Exception management and log using Sentry
- Inline Documentation
- Strong type, add security in rules, always callback
- Code follow Cascade8 Guidelines (see exemple)
- MR done

link to epic #3608
