### ISSUE TITLE
Meeting - US - Visualise participants in the Meeting

### ISSUE THREAD

**Issue by OmarSebouai** [blockframes/blockframes#3758]
# Statement

As a User, I want to have a "participants" button so that I can see the list of participants

# ToDo
* [ ] Add a "participants" button
* [ ] Show/Hide a Side Panel
* [ ] Panel needs to be animated when showing/hiding
* [ ] Show participants names and organization

# DoD
- Use Angular Material for components
- Use Cascade8 icons (available in code assets/icons)
- Unit Test using Jest
- Inline Documentation
- Feature documention in Notion
- Akita NgFire
- Deployment Test OK
- Unit Test using Jest
- Exception management and log using Sentry
- Inline Documentation
- Strong type, add security in rules, always callback
- Code follow Cascade8 Guidelines (see exemple)
- MR done
# Open Questions
- Admin will be able to click on a cross on the right side of a participants name to kick him?
To validate with Anastasia
- Admin will be able to mute a participant?
- Admin will be able to deactivate a participant camera?

link to epic #3608

**Comment by fritzschoff** [comment]
still useful @pldespaigne ? Otherwise pls close
