### ISSUE TITLE
Meeting - US - Video Settings

### ISSUE THREAD

**Issue by OmarSebouai** [blockframes/blockframes#3759]
# Statement

As a User (Buyer or Seller), I want to be able to see my own settings, so that I can mute myself or turn the camera off or see how I look on my Camera.

# ToDo
* [ ] Create Video Settings view with Static Frame
* [ ] Add my own camera
* [ ] View can be minimized
* [ ] Add Camera button On/Off and functionality
* [ ] Add Microphone button On/Off and functionality
* [ ] Add mock UI if user camera isn't activated (with Name + Firstname initials)
* [ ] Seller Video Settings are shown by default and rolled up with 4+ participants

# Note
Subject to change, need to review the new UX from Anastasiia (regarding Task bar)

# DoD
- Use Angular Material for components
- Use Cascade8 icons (available in code assets/icons)
- Unit Test using Jest
- Inline Documentation
- Feature documention in Notion
- Akita NgFire
- Deployment Test OK
- Unit Test using Jest
- Exception management and log using Sentry
- Inline Documentation
- Strong type, add security in rules, always callback
- Code follow Cascade8 Guidelines (see exemple)
- MR done
