### ISSUE TITLE
Cross App issues

### ISSUE THREAD

**Issue by phpgeekfr** [blockframes/blockframes#3768]
This Epic is a list of cross app issues that the sanity team must take care of.

**Issues with priority:**

- [x] RGPD Updates #2403
- [x] Merge "Create or Find your Organization" step #3767

**Issues created but to prioritize:**

- [ ] Checking Sendgrid for better spam score #3773
- [x] create a cron to periodically clean /tmp dir on storage #3779
- [x] Image loading issue just after upload. #3780

**Issues not created yet / to organize :**

- Rework login flow
- Excel import to rework

**Comment by phpgeekfr** [comment]
Closing this epic. Let's create a new one if needed
