### ISSUE TITLE
Tests Summary Issue

### ISSUE THREAD

**Issue by phpgeekfr** [blockframes/blockframes#3782]
**Current sprint (xx) :**

- [ ] Review #4327 (Partly done and will add UT for cloud function - TODO)

- [ ] Feat : Integrate Sentry into our workflow #4014  ** - 13 **
- [o] MF Test - Message from investor to film fund #4138 **- 13**   R&D.. checking way to send emails in festival app contact page.

**Planned and prioritized:**
- [ ] write unit tests for devOps processes #3621
- [ ] Unit Test for Invitation Service #3415

**Enhancements:**
- [ ] E2E : Configuration issue when adding a new custom command #3676
- [ ] E2E for add user scenario #3093

**Comment by xmano** [comment]
## Festival App ##

- [ ] e2e test - Add a new member #3093
- [ ] e2e enhancement : Use app commands #4225

**Comment by xmano** [comment]
## Media Financiers App ##

- [ ] Message from investor to fund Media Financiers #4138

**Comment by Jackseed** [comment]
This epic is super useful. Also when you implement new test would be good to update the [notion article](https://www.notion.so/cascade8/E2E-Test-scenarios-e4e937051d264f98abe65fe3190bfbe9) so we keep track of what's covered or not
