### ISSUE TITLE
Identify new E2E and UT tests to create

### ISSUE THREAD

**Issue by phpgeekfr** [blockframes/blockframes#3956]
# Ideas
- [ ] need new tests for screenings 
- [ ] add new items to this list

# Email flow related
- [ ] Test sending of emails works

# Already created issues 
- [ ] e2e test - Add a new member #3093
- [ ] e2e enhancement : Use app commands #4225 
- [x] e2e test - Publish movie to market #4137
- [ ] test method to define - Message from investor to fund Media Financiers #4138

**Comment by xmano** [comment]
@phpgeekfr : Can you clarify on the new tests needed with scenarios?

If you are referring to older ways of testing, then all those scenarios have been considered in the refactored test.

**Comment by phpgeekfr** [comment]
@xmano I created this issue to gather all new tests we will have to build.  It will be improved with scenarios in the future but for now this is just a list of new tests to create when all the tests you are working on right now will be green

**Comment by xmano** [comment]
Identify all current tests and close this issue.

Going forward create new issue for new E2E / Unit-Test as needed.

**Comment by xmano** [comment]
We will use the EPIC to track the issues mentioned here. Also new E2E test requirements go to that EPIC with individual issues mentioned therein.

https://github.com/blockframes/blockframes/issues/3782
