### ISSUE TITLE
Notification settings

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#4046]
## Description
Users are overflowed with notifications. We shall give them a way to choose what notifications they want to receive and how (in-app and/or emails). 

### User settings
- Add a notification tab that enables the user to choose what to receive and how
### Data model
- Add a way to save user settings
### Notifications & invitations
- Send notifications & invitations through the right canal and only when it's enabled

## UI 
[Invision](https://projects.invisionapp.com/d/#/console/19607961/429010252/preview)
[Wireframes](https://www.figma.com/file/NigQKi1NqtSjGDzAVqkglw/%5B-Notifications-Settings-%5D?node-id=0%3A1)

## Data
Notifications & invitations are listed [here](https://docs.google.com/spreadsheets/d/1DCO2PH0HaSnt3y6DSPnIX6hXbGsaCw10tCR38gG8LyM/edit#gid=0)

### General specs
- A user should be able to select a receiving rule (either in-app, mail, or both) for all the notifications/invitations or on a case by case basis.

- Difference between invitations and notifications may be not clear for users so best would be to mix it in these pages. If that's not possible we shall update designs.

- A user should see notifications & invitations settings only for those s/he actually receives it means that the list should differ depending on:
1. Application
2. Section Marketplace / Dashboard
3. Org role (super admin / admin / member)

- Invitations need to be answered so in-app invitations should be enabled by default and can't be disabled, even with the 'general' rule on the settings header. Mail sending for invitations may be disabled.

### Detailed specs
1. Company Management Notifications (Cross-app, both Marketplace & Dashboard)
Receive notifications when:
- [x] (`requestFromUserToJoinOrgCreate`) A new user requests to join your organization:
Specs: cross-app, both Marketplace & Dashboard, for admin & super admin only, toggle by default and can't be disabled, in-app reception checked and can't be disabled
Tooltip: "This notification can't be disabled since you need to answer it."

- [x] (`memberAddedToOrg`) A new member joins your organization:
Specs: cross-app, both Marketplace & Dashboard, for every members

2. Content Management Notifications (Cross-app, Dashboard)
Receive notifications when:
- [x] (`movieSubmitted`) A title is successfully submitted for validation:
Specs: `catalog` and `financiers`, Dashboard, for every members
NB: this notification may be not implemented yet but then should be 
**No email template**

- [x] (`movieAccepted`) A title gets published to the marketplace:
Specs: cross-app, Dashboard, for every members
**No email template**

3. Event Management Notifications (`festival`, both Marketplace & Dashboard)
- [x] (`invitationToAttendScreeningCreated`) An organization invites you to a screening:
Specs: `festival`, both Marketplace & Dashboard, for every members, toggle by default and can't be disabled, in-app reception checked and can't be disabled
Tooltip: "This notification can't be disabled since you need to answer it."

- [x] (`invitationToAttendMeetingCreated`) A user invites you to a meeting:
Specs: `festival`, both Marketplace & Dashboard, for every members, toggle by default and can't be disabled, in-app reception checked and can't be disabled
Tooltip: "This notification can't be disabled since you need to answer it."

- [x] (`invitationToAttendEventUpdated`) A user answers your invitation to an event:
Specs: `festival`, Dashboard, for every members, enable/disable both acceptation & decline notifications for an event

- [x] (`requestToAttendEventCreated`) A user requests an access to an event you organize:
Specs: `festival`, Dashboard, for every members, toggle by default and can't be disabled, in-app reception checked and can't be disabled
Tooltip: "This notification can't be disabled since you need to answer it."

- [x] (`requestToAttendEventSent`) Your request to access an event has been sent:
Specs: `festival`,  both Marketplace & Dashboard, for every members
**Miss Sendgrid template for the user who asks access**

- [x] (`requestToAttendEventUpdated`) An organization answers your request to access an event:
Specs: `festival`,  both Marketplace & Dashboard, for every members, enable/disable both acceptation & decline notifications for a screening

- [x] (`oneDayReminder`) Reminder 24h before an event starts:
Specs: `festival`,  both Marketplace & Dashboard, for every members 

- [x] (`eventIsAboutToStart`) Reminder 15min (1h) before an event starts:
Specs: `festival`,  both Marketplace & Dashboard, for every members

**Comment by fritzschoff** [comment]
ref #2555

**Comment by maltmayer** [comment]
Here are the texts for the notifications :)

1. Company Management Notifications (Cross-app, both Marketplace & Dashboard)

- A new user requests to join your organization.
**FirstName LastName would like to join OrgName.**
Tooltip: "This notification can't be disabled as it requires an answer from you."

- A new member joins your organization:
**FirstName LastName joined OrgName.**

2. Content Management Notifications (Cross-app, Dashboard)

- A title is successfully submitted for validation:
**TitleName was successfully submitted.**

- A title gets published to the marketplace:
**TitleName was successfully published on the marketplace.**

3. Event Management Notifications (festival, both Marketplace & Dashboard)

- An organization invites you to a screening
**OrgName invited you to participate in EventName. (Startdate - EndDate)**
Tooltip: "This notification can't be disabled as it requires an answer from you."

- A user invites you to a meeting
**OrgName invited you to participate in EventName. (Startdate - EndDate)**
Tooltip: "This notification can't be disabled as it requires an answer from you."

- A user answers your invitation to an event:
**FirstName LastName accepted/declined your invitation to participate in EventName.**

- A user requests an access to an event you organize:
**FirstName LastName would like to attend EventName.**
Tooltip: "This notification can't be disabled as it requires an answer from you."

- Your request to access an event has been sent:
**Your request to attend EventName was successfully sent.**

An organization answers your request to access an event:
**orgName accepted/declined your request to attend EventName.**

Reminder 24h before an event starts:
**REMINDER - eventName is coming up tomorrow.**

Reminder 15min before an event starts:
**REMINDER - eventName will start in 15 minutes. Don't miss it!**

**Comment by Jackseed** [comment]
> Here are the texts for the notifications :)
> 
> 1. Company Management Notifications (Cross-app, both Marketplace & Dashboard)
> 
> * A new user requests to join your organization.
>   **FirstName LastName would like to join OrgName.**
>   Tooltip: "This notification can't be disabled as it requires an answer from you."
> * A new member joins your organization:
>   **FirstName LastName joined OrgName.**
> 
> 1. Content Management Notifications (Cross-app, Dashboard)
> 
> * A title is successfully submitted for validation:
>   **TitleName was successfully submitted.**
> * A title gets published to the marketplace:
>   **TitleName was successfully published on the marketplace.**
> 
> 1. Event Management Notifications (festival, both Marketplace & Dashboard)
> 
> * An organization invites you to a screening
>   **OrgName invited you to participate in EventName. (Startdate - EndDate)**
>   Tooltip: "This notification can't be disabled as it requires an answer from you."
> * A user invites you to a meeting
>   **OrgName invited you to participate in EventName. (Startdate - EndDate)**
>   Tooltip: "This notification can't be disabled as it requires an answer from you."
> * A user answers your invitation to an event:
>   **FirstName LastName accepted/declined your invitation to participate in EventName.**
> * A user requests an access to an event you organize:
>   **FirstName LastName would like to attend EventName.**
>   Tooltip: "This notification can't be disabled as it requires an answer from you."
> * Your request to access an event has been sent:
>   **Your request to attend EventName was successfully sent.**
> * An organization answers your request to access an event:
>   **orgName accepted/declined your request to attend EventName.**
> * Reminder 24h before an event starts:
>   **REMINDER - eventName is coming up tomorrow.**
> * Reminder 15min before an event starts:
>   **REMINDER - eventName will start in 15 minutes. Don't miss it!**

Re texts there is a misunderstanding, notification texts shouldn't change for now and need to be validated before

**Comment by phpgeekfr** [comment]
![image (3).png](https://images.zenhubusercontent.com/5c6e955fdecd2e3c69b6c1d2/78d85e63-5344-4300-aefa-6350d3e9bf95)

**Comment by phpgeekfr** [comment]
@Jackseed can you provide email text for notification type `memberRemovedFromOrg` ?

**Comment by phpgeekfr** [comment]
@Jackseed here the texts we need.
Cells marked `needed ?` should be discussed

| NotificationType                   | text email | text notification |
|------------------------------------|------------|-------------------|
| invitationFromUserToJoinOrgDecline | missing    | ok                |
| movieSubmitted                     | missing    | ok                |
| movieAccepted                      | missing    | ok                |
| requestToAttendEventSent                         | missing    | ok                |
| orgMemberUpdated (added)                         | ok         | ok                |
| orgMemberUpdated (removed)                       | missing    | ok                |
| requestToAttendEventUpdated (toOrg / accepted)   | ok         | ok                |
| requestToAttendEventUpdated (toOrg / refused)    | missing    | ok                |
| requestToAttendEventUpdated (toUser / accepted) | needed ?   | ok                |
| requestToAttendEventUpdated (toUser / refused)  | needed ?   | ok                |
| invitationToAttendEventUpdated (toOrg / accepted)  | missing    | ok                |
| invitationToAttendEventUpdated (toOrg / refused)   | missing    | ok                |
| invitationToAttendEventUpdated (toUser / accepted) | needed ?   | ok                |
| invitationToAttendEventUpdated (toUser / refused)  | needed ?   | ok                |
| invitationToAttendEventCreated                     | ok         | missing           |
| requestToAttendEventCreated                        | ok         | missing           |
| orgAppAccessChanged                                | ok         | missing           |

**Comment by Mussuranae** [comment]
Do we have to look at this issue also  #4710 For the unsubscribe button ?
It should unsubscribe completely the user for the email, like put its email into a "black list" for sendgrid or something like that ?

**Comment by Jackseed** [comment]
Yep @Mussuranae would be great if you can have a look.

**Comment by phpgeekfr** [comment]
Updated table: 

| NotificationType                   | text email | text notification | text notification |
| ------------------------------------ | ------------ | ------------------ | -------------------- |
| requestFromUserToJoinOrgDeclined | draft by Clélia    | ok                |
| invitationToJoinOrgDeclined | draft by Clélia    | ok                |
| movieSubmitted                     | draft by Clélia    | ok                |
| movieAccepted                      | draft by Clélia    | ok                |
| requestToAttendEventSent                         | draft by Clélia    | ok                |
| orgMemberUpdated (added)                         | ok         | ok                |
| orgMemberUpdated (removed)                       | draft by Clélia    | ok                |
| requestToAttendEventUpdated (toOrg / accepted)   | ok         | ok                |
| requestToAttendEventUpdated (toOrg / refused)    | draft by Clélia    | ok                |
| ~~requestToAttendEventUpdated (toUser / accepted)~~ | ~~needed ?~~   | ~~ok~~                |
| ~~requestToAttendEventUpdated (toUser / refused)~~  | ~~needed ?~~   | ~~ok~~                |
| ~~invitationToAttendEventUpdated (toOrg / accepted)~~  |  ~~needed ?~~   | ~~ok~~                |
| ~~invitationToAttendEventUpdated (toOrg / refused)~~   | ~~needed ?~~    | ~~ok~~                |
| invitationToAttendEventUpdated (toUser / accepted) | draft by Clélia   | ok                |
| invitationToAttendEventUpdated (toUser / refused)  | draft by Clélia  | ok                |
| invitationToAttendMeetingCreated                     | ok         | no need           |
| invitationToAttendScreeningCreated                     | ok         | no need           |
| requestToAttendEventCreated                        | ok         | no need           |
| orgAppAccessChanged                                | ok         | missing           |
| requestFromUserToJoinOrgCreate               | ok         | no need           |

**Comment by phpgeekfr** [comment]
I put this issue in `review Q&A` even if we still have some `TODO #4046` in the code because we only need to test everything and add missing variables to send to sendGrid if any

**Comment by phpgeekfr** [comment]
I reopen it given the last comment

**Comment by phpgeekfr** [comment]
this will be to handle during tests on staging

**Comment by fritzschoff** [comment]
ah sorry, was closing it from the road map. yea sure np.

**Comment by phpgeekfr** [comment]
again ? ^^

**Comment by fritzschoff** [comment]
haha

**Comment by Jackseed** [comment]
I'm currently updating emails:

| NotificationType                   | text email | text notification | text notification |
| ------------------------------------ | ------------ | ------------------ | -------------------- |
| requestFromUserToJoinOrgDeclined | ok    | ok                |
| invitationToJoinOrgDeclined | draft by Clélia    | ok                |
| movieSubmitted                     | draft by Clélia    | ok                |
| movieAccepted                      | draft by Clélia    | ok                |
| requestToAttendEventSent                         | draft by Clélia    | ok                |
| orgMemberUpdated (added)                         | ok         | ok                |
| orgMemberUpdated (removed)                       | draft by Clélia    | ok                |
| requestToAttendEventUpdated (toOrg / accepted)   | ok         | ok                |
| requestToAttendEventUpdated (toOrg / refused)    | draft by Clélia    | ok                |
| ~~requestToAttendEventUpdated (toUser / accepted)~~ | ~~needed ?~~   | ~~ok~~                |
| ~~requestToAttendEventUpdated (toUser / refused)~~  | ~~needed ?~~   | ~~ok~~                |
| ~~invitationToAttendEventUpdated (toOrg / accepted)~~  |  ~~needed ?~~   | ~~ok~~                |
| ~~invitationToAttendEventUpdated (toOrg / refused)~~   | ~~needed ?~~    | ~~ok~~                |
| invitationToAttendEventUpdated (toUser / accepted) | draft by Clélia   | ok                |
| invitationToAttendEventUpdated (toUser / refused)  | draft by Clélia  | ok                |
| invitationToAttendMeetingCreated                     | ok         | no need           |
| invitationToAttendScreeningCreated                     | ok         | no need           |
| requestToAttendEventCreated                        | ok         | no need           |
| orgAppAccessChanged                                | ok         | missing           |
| requestFromUserToJoinOrgCreate               | ok         | no need           |

**Comment by Jackseed** [comment]
@Mussuranae some requested changes for the release:
- [ ] We'll finally remove the line "An user declined your invitation to join your organization." from notification preferences as it can't happened 
- [ ] Text on notification preferences should be changed for Marie's writing here (noticed that there are some differences in titles and column names also): https://docs.google.com/spreadsheets/d/1DCO2PH0HaSnt3y6DSPnIX6hXbGsaCw10tCR38gG8LyM/edit#gid=2090761317
(2nd tab)
- [ ] A tooltip should be added after the text for notifications that can't be disabled. Tooltip text is "This notification can't be disabled as it requires an answer from you."

**Comment by Mussuranae** [comment]
>     * [ ]  for `requestToAttendEventSent` we'll need some more variables: event view url, event type, event session url, event start date, event start time, event end date, event end time
For this one, you can access start and end with the tag `event` (it gives you `id`, `title`, `start` and `end` variable). I will add the `type` of the event on it.

>     orgMemberUpdated (removed): need to add the user first name that received the email as variable
You can now use the `adminFirstName` variable.

**Comment by Jackseed** [comment]
perfect thanks!

**Comment by Mussuranae** [comment]
For the unsubscribe solution, you have 3 different tags :
- `{{{groupUnsubscribe}}}`
- `{{{preferenceUnsubscribe}}}`
- `{{{notificationPage}}}`

The first one will allow user to unsubscribe from sendgrid for all emails excepts criticals.
The second one will redirect the user to the **Sendgrid preferences**, he will see our from which group of email he can unsubscribe. Right now, he will see only the "all except critical" email group.
The last one redirect to our notification setting page on the platform. Be aware that you need to put `{{appUrl}}` before this tag, for example, you put a custom link on a word : `{{{appUrl}}}/{{{notificationPage}}}`.

**Comment by Jackseed** [comment]
- [ ] Send the full event object to all event emails:
d-1a7cc9ca846c4ae1b4e8cf8a76455cc5
d-ce3e57248a694cefacad49bc4c820078
d-07f5e3cc6796455097b6082c22568d9e
d-0c7bcb6e4a234ddc95ed74b9ecc433dc
d-8a9439a404cc4b51887e9dea44f7fbd7
d-5d014e60af4c431dbe7316369f41591e
d-df7b0a372b994a3090a48dc6cf17ba3e
d-b7ea357cfd41404e9ff82f8d75410079
d-4e36dd72f50d4e7e9ec738476efa84a9
d-113048f9990044bbb3c9431f9965f7b8

**Comment by Jackseed** [comment]
@Mussuranae sorry but I forgot other variables for `orgMemberUpdated (removed)` (d-9913537cf12a497c8959bee844ad0fb7): we also need orgName and org member settings url (/c/o/organization/orgId/view/members)
If that's too much for the release just tell me and I'll remove that info for now

**Comment by Jackseed** [comment]
- [ ] New variables needed also for `d-f84d8c5a70884316870ca4ef657e368f` we can do it without for the release but I note it here, we need also user first name & last name, org name and admin first name

**Comment by Mussuranae** [comment]
> Thanks @Mussuranae! What about critical emails, what should I link to for unsubscribe?
I would say the `preferenceUnsubscribe` from Sendgrid, this one will be mandatory, if you don't put it, we will have the little default sentence. And if we want to let user manage more in detail their preferences, the `notiicationPage` one also to redirect to our app

**Comment by Jackseed** [comment]
- [ ] New texts for notifications have been updated here https://docs.google.com/spreadsheets/d/1b1K7YfnquxnfCgGGPxIz5ZNIjr9eK_bUrRJqLvPYGIk/edit#gid=1590038159
Not necessary for the release but I add it here for the notif new look to be complete

**Comment by Jackseed** [comment]
- [ ] @Mussuranae `d-f84d8c5a70884316870ca4ef657e368f` is spawned for every new member in the org but in fact it would be better if it was used only when a user accepts an invitation to join an org. Is it possible? 
Cause here it's sent also for requests being accepted but we already have 3 mails related to requests, it's a bit too much

**Comment by Jackseed** [comment]
- [ ] Not necessary for the release but small improvement for Event request refused `d-4e36dd72f50d4e7e9ec738476efa84a9`, would be good to add a `pageUrl` that leads to the marketplace org view (/c/o/marketplace/organization/orgId/title) of the organizer org

**Comment by Jackseed** [comment]
- [ ] Also not necessary for the release, we need a more accurate variable for app access email, it shall give us the new app name that has been given during the update

**Comment by Jackseed** [comment]
I transferred last comments to #5356
