### ISSUE TITLE
Front / Back devs - Summary Issues

### ISSUE THREAD

**Issue by phpgeekfr** [blockframes/blockframes#4077]
**Current Sprint xx** 

- [ ] [CRM APP] Add more info to csv exports #3264 **13**
- [ ] we should use callbable functions to get the proper application used instead of guessing it with org id #2848 **13**
- [ ] add a consents collection to save users consents when creating or accessing documents #4327  **21**
