### ISSUE TITLE
Master Issue of sprint 37

### ISSUE THREAD

**Issue by fritzschoff** [blockframes/blockframes#4081]
- [x] Movie List: add minimum investment filter.
- [x] Check the UI from the app and validate with design. 
- [x] Favicon update
- [x] Icons for PWA
- [x] Add files images in the view page
- [x] Polishing the app
- [x] Check all anchor links
- [x] Update the color of the charts
