### ISSUE TITLE
[FESTIVAL] Update org creation

### ISSUE THREAD

**Issue by GrandSchtroumpf** [blockframes/blockframes#4220]
Currently org creation only support seller (appAccess[app].dashboard) & buyer (appAccess[app].marketplace) and it's the same for every application.
At the point we can either : 
- Define organization type that depends on the application.
- Define organization types agnostic of the app (seller, buyer, operator)

_In any case the UI & text will be different between application (ex: "seller" can be "Sales Agent" or "Partner")._

**Tasks**: 
- [ ] Define the organization types (agnostic or not of the app).
- [ ] Define how to query org based on type
- [ ] Define how to guard pages depending on the type.
- [ ] UX: Create the flow of organization creation.
- [ ] UI: Create a shell & define what changes for every app.
- [ ] Create the shell for the org creation
- [ ] Implement org creating in every app.
- [ ] Update data model.

**Comment by Jackseed** [comment]
Mission aborted
