### ISSUE TITLE
[MASTER] Festival feature

### ISSUE THREAD

**Issue by GrandSchtroumpf** [blockframes/blockframes#4223]
- [ ] #4220 Update org creation,
- [ ] #4221 Shell component per org
- [ ] #4222 Change the "dashboard / marketplace" structure to "seller / buyer / operator"
- [ ] Update every link in the application
- [ ] #4233 Create dynamic branding (theme, logo, images, filters)
- [ ] #4230 Create festival model, service & pages

**Comment by fritzschoff** [comment]
@Jackseed @GrandSchtroumpf is this issue on hold until we know more what we want about the festival app?

**Comment by GrandSchtroumpf** [comment]
For my part, I think we can close it. Maybe @Jackseed has a different opinion.

**Comment by Jackseed** [comment]
Let's close it and we'll open it back if that up again
