### ISSUE TITLE
Meeting Bug Tracker

### ISSUE THREAD

**Issue by pldespaigne** [blockframes/blockframes#4393]
General Bug Tracking issue for the whole Meeting features

- [x] clicking on the "quit meeting" button, then clicking on "cancel" still kill Twilio (even if the user stays on the session page)
- [x] pdf view for private documents doesn't work for buyers
- [x] when seller quit the meeting, buyers are redirected to lobby instead of the "meeting is over" page
- [ ] After disabling camera and muting microphone in the lobby page, I navigate to the session page and the camera and microphone are active again

_link to master issue #3639_

**Comment by pldespaigne** [comment]
Closing in favor of various per-release Sanity-Team issues
