### ISSUE TITLE
create custom form fields for specific uses

### ISSUE THREAD

**Issue by phpgeekfr** [blockframes/blockframes#442]
**todo**:
- [x] identify forms and inputs @phpgeekfr 
- [ ] create / update specific input components @Hugo-Hontans 
- [ ] replace existing form inputs with new ones @Hugo-Hontans 
- [ ] create/update specific validators @Hugo-Hontans  @phpgeekfr 
- [ ] design outputs @mathilde

**Comment by phpgeekfr** [comment]
Les different input types types:
- [ ] datepicker
- [ ] integer
- [ ] string
- [ ] password
- [ ] email
- [ ] password-confirm-group
- [ ] textarea
- [ ] select
- [ ] upload
- [ ] year
- [ ] multi select autocomplete (with search bar)
- [ ] "single" select autocomplete (with search bar)
- [ ] url
- [ ] mat chimp
- [ ] string autocomplete
- [ ] email autocomplete
- [ ] float
- [ ] mnemonic
- [ ] privatekey

**Comment by phpgeekfr** [comment]
## Screenshots
![movie-team](https://user-images.githubusercontent.com/1194344/59361058-8ec99400-8d31-11e9-972b-4477d42afd72.png)
![movie-story](https://user-images.githubusercontent.com/1194344/59361060-8ec99400-8d31-11e9-94b7-db4f12da55ba.png)
![movie-promo](https://user-images.githubusercontent.com/1194344/59361063-8ffac100-8d31-11e9-85e8-7fcfcb22a222.png)
![movie-new](https://user-images.githubusercontent.com/1194344/59361065-90935780-8d31-11e9-9114-e7abd8d5ba0a.png)
![movie-main-d](https://user-images.githubusercontent.com/1194344/59361066-90935780-8d31-11e9-9a03-829c524477ad.png)
![movie-main-c](https://user-images.githubusercontent.com/1194344/59361071-912bee00-8d31-11e9-83c5-fe5563ba8cff.png)
![movie-main-b](https://user-images.githubusercontent.com/1194344/59361072-91c48480-8d31-11e9-93ec-10c60ee08845.png)
![movie-main-a](https://user-images.githubusercontent.com/1194344/59361075-925d1b00-8d31-11e9-9c74-c25c82499cea.png)
![movie-teamwork](https://user-images.githubusercontent.com/1194344/59361077-92f5b180-8d31-11e9-9307-ce0d87f24b7e.png)
![org-add-member](https://user-images.githubusercontent.com/1194344/59361078-92f5b180-8d31-11e9-8044-c47df5b8074c.png)
![org-create](https://user-images.githubusercontent.com/1194344/59361080-938e4800-8d31-11e9-8694-2c710e0cc150.png)
![profile-delete](https://user-images.githubusercontent.com/1194344/59361081-9426de80-8d31-11e9-93c7-b32e291842b2.png)
![profile-form](https://user-images.githubusercontent.com/1194344/59361083-9426de80-8d31-11e9-9960-1e3523295e4e.png)
![template-new](https://user-images.githubusercontent.com/1194344/59361085-94bf7500-8d31-11e9-89a9-9bab9419bde5.png)
![template-save-new](https://user-images.githubusercontent.com/1194344/59361086-94bf7500-8d31-11e9-91ab-fcb1563c42ae.png)
![wallet-buy-eth](https://user-images.githubusercontent.com/1194344/59361087-94bf7500-8d31-11e9-894a-7516053c4661.png)
![wallet-import-a](https://user-images.githubusercontent.com/1194344/59361088-94bf7500-8d31-11e9-84e4-86dfef4fa771.png)
![wallet-import-b](https://user-images.githubusercontent.com/1194344/59361090-95580b80-8d31-11e9-80a4-cc7d42b61c74.png)
![wallet-import-c](https://user-images.githubusercontent.com/1194344/59361092-95580b80-8d31-11e9-862e-88f8c4a4c0de.png)
![wallet-password](https://user-images.githubusercontent.com/1194344/59361093-95f0a200-8d31-11e9-9524-c59ed615ce7d.png)
![wallet-password-confirm](https://user-images.githubusercontent.com/1194344/59361096-95f0a200-8d31-11e9-8286-2863ddea4149.png)
![delivery-sign](https://user-images.githubusercontent.com/1194344/59361097-96893880-8d31-11e9-9b63-17b1976a268c.png)
![delivery](https://user-images.githubusercontent.com/1194344/59361099-96893880-8d31-11e9-85e2-acdca52280df.png)
![material-edit-with-step](https://user-images.githubusercontent.com/1194344/59361100-9721cf00-8d31-11e9-83e3-0c421329ad60.png)
![material-edit](https://user-images.githubusercontent.com/1194344/59361101-97ba6580-8d31-11e9-8aa6-448b786bdfa9.png)
![login-logout](https://user-images.githubusercontent.com/1194344/59361104-98eb9280-8d31-11e9-9060-3fa070a7a140.png)


------------
## Single inputs

Date picker:
![datepicker](https://user-images.githubusercontent.com/1194344/59361056-8ec99400-8d31-11e9-9b27-c23f1ed21690.png)
Checkbox:
![checkbox](https://user-images.githubusercontent.com/1194344/59361057-8ec99400-8d31-11e9-91d0-0ac09c8f207b.png)
