### ISSUE TITLE
Post release bug list

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#4514]
### Meeting session
- [x] Full screen button doesn't work on Safari
![image](https://user-images.githubusercontent.com/14964443/101799825-e1456580-3b0c-11eb-8039-a02bd72ea75d.png)
- [ ] When clicking on an element that has already been shared, it should reset it. Here I clicked on the video already shared and it was still at then end of the video
PL : I'm not sure it's a good idea to do that, imo that would be bad UX, @2amarkina what is your thoughts on that ?

![image](https://user-images.githubusercontent.com/14964443/101798747-beff1800-3b0b-11eb-815f-6795e8300907.png)

### CRM
- [x] Remco: Make row in table clickable to navigate to edit page (instead of the edit icon as a column)
- [x] Remco: Disable sorting on certain columns (@remco did this in file explorer too)
- [x] Remco: For the upload of organization, if you choose `organizations` in the select after downloading your excel, it doesn't work and the spinner is turning forever
![image](https://user-images.githubusercontent.com/48033264/101754805-6ceed000-3ad4-11eb-8669-a456a29fbf01.png)
The upload works fine if we choose our type of document before uploading the excel.
- [x] There is no simulation for the user when we want to delete it. (Clélia)
![image](https://user-images.githubusercontent.com/48033264/101759087-729ae480-3ad9-11eb-8ebc-00a55daffced.png)
Functionality works fine !

### Notifications (Samir)
- [x] Change notification text triggered when movie status is turned to "accepted". Currently it's "Your project was successfully published on the marketplace."; should be instead: "[ Title name ] was successfully published on the Marketplace."

### Invitations (Samir)
- [x] Clicking on 'event name' or 'more details' leads to event marketplace page, 
but clicking on the event in calendar directly leads to the lobby of the meeting. They should all lead to the lobby page
- [x] Right align invitation status so they are aligned even if invitation text is not same size
![image](https://user-images.githubusercontent.com/14964443/101914929-3c3a9380-3bc5-11eb-8902-d855a5c6810e.png)

### Wishlist
- [ ] wish-list button can be hard to spot (@stephanie-cascade8 we need your advice here)
![image](https://user-images.githubusercontent.com/5858657/101618212-f5586c80-3a11-11eb-91a8-11cea0268026.png)

### MF Homepage (Clélia)
![image](https://user-images.githubusercontent.com/55785823/101918502-b8cf7100-3bc9-11eb-81f9-b252c665128b.png)
- [x] org logos are too big they should look like the ones on Archipel Market:
![image](https://user-images.githubusercontent.com/55785823/101918636-e1576b00-3bc9-11eb-9239-1f216e5ff636.png)

### Screening list
- [ ] ![Enregistrement de l’écran 2020-12-10 à 16 34 28 (1)](https://user-images.githubusercontent.com/55785823/101793711-6416f200-3b06-11eb-850b-461441e6137e.gif)
Public event approval process still weird. We shouldn't see the sentence about the org approval appear. Should directly go to the event page, without this kind of weird jump

### Movie filters
- [x] **_Remco_**: Remove "All languages" from Language & Version filter list
![image](https://user-images.githubusercontent.com/14964443/101780581-0202c080-3af7-11eb-8c9c-5a5ca9d0b6a4.png)
- [x] **_Remco_**: Budget filter not working on Safari (cf screenshot Brave on left vs Safari on right)
![image](https://user-images.githubusercontent.com/14964443/101785741-66c11980-3afd-11eb-99be-c5d452698417.png)
- [x] **_Remco_**: Change budget filter behaviour: we should reverse the way it works and go from right to left, starting at a maximum 20M$ budget and choosing till how much it goes down.
E.g. I go halfway from 20M to 10M and got all films that have budget range between 10M & 20M$
- [x] There is an "search-icon" missing in a search bar while scrolling 
Here : 
<img width="918" alt="Снимок экрана 2020-12-10 в 16 57 28" src="https://user-images.githubusercontent.com/55499036/101796228-02a45280-3b09-11eb-8fa7-ea6626cf5ef2.png">

Should be like : 
<img width="562" alt="Снимок экрана 2020-12-10 в 16 57 22" src="https://user-images.githubusercontent.com/55499036/101796254-089a3380-3b09-11eb-8150-be91e1a5269d.png">

### Dashboard homepage (Clélia)
![image](https://user-images.githubusercontent.com/55785823/101902509-0c829000-3bb3-11eb-9fc6-a68ee248bc51.png)
- [x] add capital letters: "View My Titles"

### Movie form
- [x] Add a line of text with the total amount for financing plan below financing plan and budget: 
- Below financing plan: "Your total financing plan is: {{movieCurrency}} {{totalFinancing}}" (formated with american style number)
- Below budget: "N.B. Your total financing plan is: {{movieCurrency}} {{totalFinancing}}" (formated with american style number)
- If financing plan has not been touched yet, instead of $0, display "N.B. Your total financing plan is: N/C"
![image](https://user-images.githubusercontent.com/14964443/101893804-8ad83580-3ba5-11eb-9284-9a0da8678a44.png)

- [x] Add a line of text the total amount of estimated budget below financing plan
- "N.B. Your total estimated budget is: {{movieCurrency}} {{totalBudget}}" (formated with american style number)
- If budget has not been touched yet, instead of $0, display "N.B. Your total estimated budget is: N/C"

- [x] From Louis: Name the last section "other" and put "cotingency, producers fees, OH fees" in (). Sorry Max I know I never got back to you on the matter. 
<img width="1437" alt="Capture d’écran 2020-12-11 à 15 49 18" src="https://user-images.githubusercontent.com/73707444/101917657-c9cbb280-3bc8-11eb-9738-8829522e62b4.png">

- [ ] Remove the arrows on the right since they allow to move/up down with 1$ = 1 click and here we're talking millions
PL : I don't think it's possible to remove the arrows since this is a browser native number input, however we can define a bigger step than $1 when the user clicks on the arrows

<img width="1417" alt="Capture d’écran 2020-12-11 à 15 54 00" src="https://user-images.githubusercontent.com/73707444/101918193-5e361500-3bc9-11eb-9c04-57c49eea5344.png">

- [x] Cast & Crew members filmographies don't appear on the bf table (it works on director)
![Cast Member](https://user-images.githubusercontent.com/14964443/101892717-06d17e00-3ba4-11eb-8cdc-aa372d6a3907.png)

- [x] For the list component, remove the last "-" (eg here "Oscar - Best Foreign Movie - 2021")
![Oscar Academy Awards Best Foreign Movie - 2021 -](https://user-images.githubusercontent.com/14964443/101892854-31bbd200-3ba4-11eb-9491-0fc471ac19de.png)

- [ ] If possible, remove "Funding Status" in the summary page as it's not editable from here anymore. It should stay on the dashboard movie view tab investment
![Investment conditions](https://user-images.githubusercontent.com/14964443/101893116-937c3c00-3ba4-11eb-97fc-a595d9883e09.png)

- [x]  page available materials: remove "All languages" from that list
![image](https://user-images.githubusercontent.com/14964443/101804204-a265de80-3b11-11eb-86d2-95a1f2a5d794.png)

### Landing page
- [x] In the "Want to learn more" section, limit the input to numbers after the "+" and to 3 digit max so that you can only put a country phone code and not the entire number  (Clélia)

<img width="1051" alt="Capture d’écran 2020-12-11 à 13 26 49" src="https://user-images.githubusercontent.com/73707444/101903999-756b0780-3bb5-11eb-98f5-5035d199d322.png">

### Org list

- [x] World shouldn't be on that list
![image](https://user-images.githubusercontent.com/14964443/101780075-58bbca80-3af6-11eb-867d-a697cd8de027.png)

/!\ Safari bugs only, works well on Brave:

- [ ] Got nothing on France while there are some
![image](https://user-images.githubusercontent.com/14964443/101780156-75580280-3af6-11eb-84b6-bece0cc28526.png)
![image](https://user-images.githubusercontent.com/14964443/101780246-94ef2b00-3af6-11eb-923e-7ff5417f1a50.png)

- [ ] Clear doesn't reload the whole list
![image](https://user-images.githubusercontent.com/14964443/101780202-856fe200-3af6-11eb-9330-846fabc85929.png)

### Dashboard movie view
- [x] tab production, remove the comma after the first production company, copro, distrib.. (Clélia)
![Production Information](https://user-images.githubusercontent.com/14964443/101895150-72691a80-3ba7-11eb-99e1-4cced073e49f.png)

- [x] tab artistic miss description for both cast & crew and crew role for crew; remove the last comma after "1 (2015) (Clélia)
![Artistic Team](https://user-images.githubusercontent.com/14964443/101895217-86148100-3ba7-11eb-8b9f-3a1b8bfa4f16.png)
Zeplin [here](https://app.zeplin.io/project/5ca741b3ed21e79faa266664/screen/5f4661c0e0b519853085cf7f)

- [x] Media Financiers: If possible to be app-specific there, above "Update funding status" a percentage of the current funding (eg "82% funded"). Round the number to be integer (Clélia)
![The Execution](https://user-images.githubusercontent.com/14964443/101895720-31253a80-3ba8-11eb-8287-b4478cbc5a74.png)

### MF Marketplace movie view (Clélia)
- [x] The currency is not asked/precise in the "Open discussion" CTA

<img width="609" alt="Capture d’écran 2020-12-11 à 15 19 30" src="https://user-images.githubusercontent.com/73707444/101914526-b61e4d00-3bc4-11eb-81b8-b679c087b98d.png">

**Comment by Mussuranae** [comment]
- [ ] For the public org list, at the moment I took the screenshot, there were only 16 users in the org and not 19.
![image](https://user-images.githubusercontent.com/48033264/102097223-ef092c80-3e25-11eb-99d1-75ee8019e602.png)

**Comment by RemcoSimonides** [comment]
@Jackseed This one is really hard and I wonder if it's worth the effort: The searchbar in the top bar is not using `<mat-input-field>` but a normal `<input>` with little css to make it look like material. Adding an icon in the placeholder of <input> will involve a lot more css trickery or I could add this '🔍' :) 
- [ ] There is an "search-icon" missing in a search bar while scrolling 
Here : 
<img width="918" alt="Снимок экрана 2020-12-10 в 16 57 28" src="https://user-images.githubusercontent.com/55499036/101796228-02a45280-3b09-11eb-8fa7-ea6626cf5ef2.png">

Should be like : 
<img width="562" alt="Снимок экрана 2020-12-10 в 16 57 22" src="https://user-images.githubusercontent.com/55499036/101796254-089a3380-3b09-11eb-8150-be91e1a5269d.png">

**Comment by Jackseed** [comment]
@RemcoSimonides the screenshot looks good we can go with what you suggest. If even your suggestion mess up with the code we can drop that icon

**Comment by phpgeekfr** [comment]
- [ ] Algolia autocomplete selects wrong value #4153

**Comment by Jackseed** [comment]
New ones from prod review:

- [ ] Excel import: change available version column to reflect the data model, it's now a yes/no toggle instead of a language array
<img width="119" alt="Available version(s)" src="https://user-images.githubusercontent.com/14964443/102607258-465e1400-4128-11eb-86a3-f472412aff3a.png">

- [ ] Find your org page (user creation flow) should look at all the orgs and not only the orgs from the current app

- [ ] Org cards on public org list marketplace count every movies (even draft) while it should be movies related to that app and validated 
<img width="191" alt="32 films in line-up" src="https://user-images.githubusercontent.com/14964443/102607417-8de4a000-4128-11eb-9f41-036ecbd26c6a.png">

- [ ] Logo and menu on navbar are too close from each other. [Here is the zeplin for that](https://app.zeplin.io/project/5fa1637022e6a88784fbb052/screen/5fa1814c2e50ba022de0c436)
<img width="257" alt="Archipel" src="https://user-images.githubusercontent.com/14964443/102607990-7b1e9b00-4129-11eb-9445-473713f07c08.png">

- [ ] Add some spacing before the text "There is no upcoming screening" and reduce the one between subtitle & image (check with @stephanie-cascade8 for the right ones, I can't find a zeplin for that)
<img width="950" alt="Screening List" src="https://user-images.githubusercontent.com/14964443/102608741-ace43180-412a-11eb-8725-2e7144d8ac9a.png">

**Comment by xmano** [comment]
Festival Screening Invitation E2E has couple of failures related to UI. 

After selecting "more details" in invitation notification, the navigation seems to go directly to screening session page. This breaks the test and I need to confirm if this is the new change. 

Going back from screening session, shows a modal with broken CSS:

![image](https://user-images.githubusercontent.com/8731418/103219239-2528cf00-4943-11eb-84b2-95f5241cf3b1.png)


Also see a snackbar message possibly to incorrect data, but it could be issue with my setup. so please check if it exists

```

error-logger.module.ts:15 Error: Unable to convert "undefined" into a date
    at toDate (format_date.ts:710)
    at formatDate (format_date.ts:66)
    at EventRangePipe.push.../../../libs/event/src/lib/pipes/event-range.pipe.ts.EventRangePipe.transform (event-range.pipe.ts:9)
    at pureFunction1Internal (core.js:24512)
    at Module.ɵɵpipeBind1 (core.js:24677)
    at ItemComponent_mat_list_item_0_ng_container_5_ng_container_1_ng_container_1_ng_template_2_Template (item.component.html:22)
    at executeTemplate (core.js:7303)
    at refreshView (core.js:7172)
    at refreshEmbeddedViews (core.js:8281)
    at refreshView (core.js:7196)

```

**Comment by Mussuranae** [comment]
I checked the issue with the mat-dialog confirm component. I see nothing wrong in the code. I imported an other component of Angular Material (mat-chip) to see if the chip would have the same visual issue, and with importing something else, it fixed the bug.... The dialog is working for me now.... :| 
@xmano For your second issue, no an user that isn't invited mustn't get the accept/refuse button but a `request access` button like in the picture. I haven't the problem, can you check again if your account hasn't an invitation pending ?
![image](https://user-images.githubusercontent.com/48033264/103406738-110bea00-4b5c-11eb-9861-149617923763.png)

**Comment by Jackseed** [comment]
Closing this, too old an issue
