### ISSUE TITLE
Sign up page refactoring

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#4932]
## Description
We'll try to facilitate the connexion flow by refactoring most of the sign up pages. They will be all merged into one page that will have many states to handle the different use cases. 

## UI 
Wireframes & flows are [here](https://www.figma.com/file/oUCgDCGJndPiVhel04GdIH/%5B-Archipel-Content-Renaissance-%5D?node-id=4%3A19). 
UI don't change regarding existing inputs, Zeplin not fully complete [here](https://app.zeplin.io/project/5f3100d317a0041be2ad99c4/screen/5f5b452671d0c977b84456ec)
![image.png](https://images.zenhubusercontent.com/5c6a89ac8de1b31d5443ab99/fb8a007a-2681-429c-8ace-90f53f7b351e)

## Acceptance criteria
- Every fields are mandatory

- [x] First name & last name fields
- same as existing ones on the sign up page
- always visible

- [x] Email field
- same as existing one 
- always visible
- when a user is redirected from an invitation email (both org & events) should be pre-filled

- [x] Company name
![image.png](https://images.zenhubusercontent.com/5c6a89ac8de1b31d5443ab99/349c43fb-60f7-4a1e-874c-2fe972cd0769)
- New field merging "find an org" & "create an org"
- Placeholder: Company Name
- Hint: Please join an existing company account or create a new one
- Autocomplete input using the org name list and org logo 
- Last choice of the list is "+ CREATE "{{USER_INPUT}}" COMPANY". When clicking on that choice, the org should not be created yet. 
- If the user doesn't select a choice, raises an error: "You have to select a choice from the list."
- If the user selects an existing org, the following org related fields are pre-filled
- when a user is redirected from an invitation to an org, company name & other org related fields should be pre-filled
- if a user selects a company and then change the name and clicks on create a new company, the other pre-filled inputs must be erased

- [x] Company's Activity
- same as existing "Activity" field on create an org
- Placeholder: Company's Activity
- select with org activity list
- should be pre-filled if the company exists

- [x] Company's Nationality 
- same as existing "Country" headquarters address in org settings page
- saved as country headquarters address
- autocomplete input with the country list (without world)
- should be pre-filled if the company exists

- [x] Marketplace | Dashboard 
![image](https://user-images.githubusercontent.com/14964443/107808949-b1177e80-6d6a-11eb-967c-72edebd340b5.png)
- toggle buttons text will be app-specific: 
AM: "Sales Agent" | "Buyer"
AC: "Seller" | "Buyer"
MF: "Partner" | "Investor"
- saved as the app-access for this app
- only one option can be chosen
- should be pre-filled if the company exists

- [x] Key / Pre-generated password
![image](https://user-images.githubusercontent.com/14964443/107809352-3a2eb580-6d6b-11eb-80ab-19dec46e62ac.png)
- same as existing "pre-generated password" input on identity page
- input visible only if the email address is linked to an invitation (org or events)
- placeholder: Key / Pre-generated password
- hint: "Check up your invitation mail to get the key / password."
- "Contact us" opens intercom

- [x] password & confirm password
- same as existing inputs

- [x] T&C and Privacy policy
- same as existing inputs

**Comment by phpgeekfr** [comment]
I tried to create a map of distinct auth flow  : 
![image](https://user-images.githubusercontent.com/1194344/108071392-f9ce8080-7065-11eb-8832-5998561e5181.png)

This lists the different cases we will have to handle
