### ISSUE TITLE
BUSINESS REVIEW (Marie)

### ISSUE THREAD

**Issue by maltmayer** [blockframes/blockframes#5261]
### DASHBOARD MOVIE FORM

- [x] Saved Other Video looks like there's information missing (@pldespaigne)
![image](https://user-images.githubusercontent.com/55785823/111512339-efc89c00-874f-11eb-8079-c0241cadab37.png)

- [x] **fixed by #5252** Behavior problem for the "To be determined" Running time status. Value should not be mandatory for this one as the value itself should be "To be determined". + it technically makes no sense as the value field disappears when you click on "To be determined" as Running time status. So we technically can't provide a value.
![image](https://user-images.githubusercontent.com/55785823/111512772-64033f80-8750-11eb-8f68-a5956a88592a.png)

- [x] **dedicated [issue](https://github.com/blockframes/blockframes/issues/5269)** I think this Festival list should be in alphabetical order
![image](https://user-images.githubusercontent.com/55785823/111513392-0cb19f00-8751-11eb-930e-4a88e6f37750.png)

- [x] **(dedicated [issue](https://github.com/blockframes/blockframes/issues/5268))** try to publish my movie vW8kyOnJKVafoKNG0vZr. It says movie online but the movie stays draft. It did that multiple times. Maybe it's just because I had multiple movie tunnel open? (need investigation @SamirTouira)
![image](https://user-images.githubusercontent.com/55785823/111509323-e68a0000-874c-11eb-92e0-7492c1622553.png)

### MARKETPLACE MOVIE VIEW
- [x] Some already existing films have image issues. This movie for example: 83mxbXLYfgzyRsfCcd9k. This one too: c8e3k3RhlE1oQK2RWMJ3 (need investigation @pldespaigne)
![image](https://user-images.githubusercontent.com/55785823/111508016-834b9e00-874b-11eb-8987-1d29369996c7.png)

- [x] Sales Pitch display issue for this movie 83mxbXLYfgzyRsfCcd9k and my test too: vW8kyOnJKVafoKNG0vZr. I think the video has a problem that may be why. The first one is an existing movie and the second one is a new test movie (I made the upload a few hours ago) (need investigation @pldespaigne)
![image](https://user-images.githubusercontent.com/55785823/111508715-4fbd4380-874c-11eb-8ee2-60d9fbb81336.png)
Same problem here 8eFrtbbyJo3JzEwFwJF5 and I got the following error message:
![image](https://user-images.githubusercontent.com/55785823/111514463-0ff95a80-8752-11eb-8bf6-ddbe4a872146.png)

- [x] Also have a display issue on the trailer of an existing film 8eFrtbbyJo3JzEwFwJF5 (need investigation @pldespaigne)
![image](https://user-images.githubusercontent.com/55785823/111514716-49ca6100-8752-11eb-9729-525589a95335.png)

- [x]  **dedicated [issue](https://github.com/blockframes/blockframes/issues/5269)** Sales Pitch video and synopsis sizes are not balanced
![image](https://user-images.githubusercontent.com/55785823/111511758-5600ef00-874f-11eb-9378-9e400b4b1b01.png)

- [x]  **dedicated [issue](https://github.com/blockframes/blockframes/issues/5269)** Video title display issue at the bottom of the page 
![image](https://user-images.githubusercontent.com/55785823/111511921-7b8df880-874f-11eb-819d-82cf6955aba7.png)

- [x]  **dedicated [issue](https://github.com/blockframes/blockframes/issues/5269)** Images and Videos are not aligned
![image](https://user-images.githubusercontent.com/55785823/111512683-4afa8e80-8750-11eb-922f-7b1e3b4a805a.png)

- [x] **dedicated [issue](https://github.com/blockframes/blockframes/issues/5269)** Behavior problem for the "To be determined" Running time status. There should be no value associated to it. the value itself is "To be determined" (or TBD). (ngIf issue)
![image](https://user-images.githubusercontent.com/55785823/111512878-82693b00-8750-11eb-96ef-bcd5b415b411.png)

- [x] **design [issue](https://github.com/blockframes/blockframes/issues/5083), won't be done for 2.3 release** we need an empty state for this component. This is not pretty 
![image](https://user-images.githubusercontent.com/55785823/111513456-1e934200-8751-11eb-89b1-59f84d31f666.png)

- [x] **dedicated [issue](https://github.com/blockframes/blockframes/issues/5271)** I think when a Review info is filled, Journal name should be mandatory. The left card makes no sense here: @Jackseed What's opinion on that ? (@SamirTouira)
![image](https://user-images.githubusercontent.com/55785823/111513546-366ac600-8751-11eb-9827-f63a5e2a02d7.png)

- [x] **dedicated [issue](https://github.com/blockframes/blockframes/issues/5269)** The two Review cards should have the same height regardless of the information provided (not sure it will be possible)
![image](https://user-images.githubusercontent.com/55785823/111513656-54382b00-8751-11eb-98d4-3c768c4ef32a.png)

- [x] **dedicated [issue](https://github.com/blockframes/blockframes/issues/5269)** Alignment issues for the reviews component (gets aligned on the left instead of centered when text is too long I guess)
![image](https://user-images.githubusercontent.com/55785823/111515203-ca895d00-8752-11eb-8d9c-4a3a8aed1819.png)

- [x] **dedicated [issue](https://github.com/blockframes/blockframes/issues/5269)** Height issue on the Review card. Text doesn't appear in full... (css text-overflow)
![image](https://user-images.githubusercontent.com/55785823/111515646-51d6d080-8753-11eb-9c24-db300b88221c.png)

- [x] **dedicated [issue](https://github.com/blockframes/blockframes/issues/5269)** Alignment issues for the festivals component (gets aligned on the left instead of centered when text is too long I guess) (not sure it will be possible)
![image](https://user-images.githubusercontent.com/55785823/111515148-bd6c6e00-8752-11eb-8eb6-3260d651843b.png)

- [x] I think when a Festival info is filled, Festival name should be mandatory. The bottom cards makes no sense here: @Jackseed What's opinion on that ?
![image](https://user-images.githubusercontent.com/55785823/111515385-0290a000-8753-11eb-8238-227babd50616.png)

- [x] General comment: when there's only one corresponding info, no "s", when there's several, add the "s". Here GENRE should be singular (i18n plural pipe)
![image](https://user-images.githubusercontent.com/55785823/111515078-acbbf800-8752-11eb-8c0e-a44ec002c5f5.png)

### DASHBOARD FILES 
- [x] Return to next line after "predetermined." (@pldespaigne)
![image](https://user-images.githubusercontent.com/55785823/111510520-26051c00-874e-11eb-8765-15d670dfac2f.png)

- [x] the files in each movie are ordered alphabetically. they should not, it does not make sense (@pldespaigne)
PL: This is low priority, also having a predefined/hardcoded order will be really hard or ugly

![image](https://user-images.githubusercontent.com/55785823/111510788-66649a00-874e-11eb-89a1-847e91a7d3ab.png)
I think it should be in more logical order:
- Poster
- Banner
- Images
- Screener
- Sales Pitch
- Other Videos
- Scenario 
- Presentation Deck
- Moodboard / Artistic Deck
- Notes & Statements
What do you think @Jackseed ?

- [x] But on the contrary, the movies should be ordered alphabetically in the File storage. We can't guess the logic here: (@pldespaigne)
PL: This is low priority, I think it's currently ordered by ID, probably possible with a sort function or an order clause in the query, this might have side effects though

![image](https://user-images.githubusercontent.com/55785823/111516184-e9d4ba00-8753-11eb-8100-ead8172d3be9.png)

### DASHBOARD MOVIE PAGE

- [x] Title list should be ordered alphabetically by default I think. We can't guess the logic here (@SamirTouira)
![image](https://user-images.githubusercontent.com/55785823/111515791-8054ab80-8753-11eb-8821-675105f01b4f.png)

**Comment by maltmayer** [comment]
### FIRST INVITATION

- [ ] Filled in every info but can't sign up I think the problem is in the Company field. 
My company obviously doesn't exist but it does not suggest me to create it. And since I didn't click on "create" the platform doesn't seem to register my company information. I'm stuck.
Actually I noticed it suggests to create the company when it finds matching companies. But when it doesn't, the list doesn't appear so the "create company" doesn't appear either. I put a video to explain better.
![image](https://user-images.githubusercontent.com/55785823/111517063-f1489300-8754-11eb-8ef7-76149e1b6b33.png)

https://user-images.githubusercontent.com/55785823/111517510-70d66200-8755-11eb-875d-54182021403c.mov



- [ ] Very unpleasant automated box appears. I figure it might be out of our control but if we could disable the automated suggestions, it would be GREAT as this is quite annoying:
![image](https://user-images.githubusercontent.com/55785823/111517180-14734280-8755-11eb-830c-85036ae20e4e.png)

- [ ] When I create a company and realize I made a mistake, I can't go back, I'm stuck with the company I initially created. Don't know what to do appart from refreshing and filling in again all the info... Not very pleasant

https://user-images.githubusercontent.com/55785823/111517665-98c5c580-8755-11eb-92ea-0efb15c35acb.mov


- [ ] the "CREATE th COMPANY" line should look different from the list of existing companies. Maybe in bold? maybe have a separation line?
- [ ] Also, there should be quotation marks around the company name. here it should say:  _CREATE "th" COMPANY_
![image](https://user-images.githubusercontent.com/55785823/111517985-f0643100-8755-11eb-83f2-94905e0236b2.png)

**Comment by Jackseed** [comment]
> * I think when a Festival info is filled, Festival name should be mandatory. The bottom cards makes no sense here: @Jackseed What's opinion on that ?
>   ![image](https://user-images.githubusercontent.com/55785823/111515385-0290a000-8753-11eb-8238-227babd50616.png)

@maltmayer that has already been changed but old festival are not been changed. It can only be done manually for pre-existing movie

**Comment by maltmayer** [comment]
### SIGN UP PAGE

- [ ] Choose your role information icon doesn't work: no hint on hover
- [ ] Also, "i" icon is too close 
- [ ] "*" should have a space before it like for other fields
- [ ] The select button Buyer / Sales Agent is too far from "Choose your role". "Choose your role" looks like the title of the password section.
![image](https://user-images.githubusercontent.com/55785823/111618852-26042b00-87e5-11eb-8dc6-70bf81c5092b.png)

- [ ] Change "Company's nationality" to "Company Country of Origin"
![image](https://user-images.githubusercontent.com/55785823/111618993-52b84280-87e5-11eb-92ad-db4818c40115.png)

### FIRST INVITATION PAGE

- [ ] There should be a sentence/hint somewhere saying "Your Company Information is pre-filled as we found an invitation matching your email address, associating you with an existing company."
![image](https://user-images.githubusercontent.com/55785823/111619351-bf334180-87e5-11eb-9e8d-2e78b56763fa.png)

- [ ] Change hint text from "Check up your invitation mail to get the invitation code." to "You can find your invitation code in your invitation email."
- [ ] Contact us should be clickable
- [ ] Wrong information displayed: here it autofilled as "Buyer" but I avec access to the Dashboard and Marketplace.
![image](https://user-images.githubusercontent.com/55785823/111617962-1a643480-87e4-11eb-8a90-c2c9afd46537.png)

### SIGN UP / "Thank you for joining us!"

### ORGANIZATION PAGE

- [ ] Change invalid email error text from "These mails are not valid email:" to "The following emails are invalid:"
![image](https://user-images.githubusercontent.com/55785823/111619866-58faee80-87e6-11eb-9f4f-e277ebb02ba7.png)

**Comment by phpgeekfr** [comment]
> Wrong information displayed: here it autofilled as "Buyer" but I avec access to the Dashboard and Marketplace.
we had to choose between one of the both when existing org already have access to dashboard & marketplace.

**Comment by maltmayer** [comment]
> > Wrong information displayed: here it autofilled as "Buyer" but I avec access to the Dashboard and Marketplace.
> > we had to choose between one of the both when existing org already have access to dashboard & marketplace.

Then it should be Sales Agent.

**Comment by phpgeekfr** [comment]
> > > Wrong information displayed: here it autofilled as "Buyer" but I avec access to the Dashboard and Marketplace.
> > > we had to choose between one of the both when existing org already have access to dashboard & marketplace.
> 
> Then it should be Sales Agent.

Ok I changed the default to Sales Agent

**Comment by phpgeekfr** [comment]
@maltmayer `Choose your role information icon doesn't work: no hint on hover` What should be the text please ?

**Comment by phpgeekfr** [comment]
>Contact us should be clickable
It is working on festival but not on MF. I'm looking for issue

**Comment by maltmayer** [comment]
### SIGN UP PAGE

- [ ] "Email" title is not aligned 
- [ ] Also email text is not centered vertically
- [ ] "First name" should be "First Name" (capital n)
- [ ] "Last name" should be "Last Name" (capital n)
- [ ] Company name hint text should be: "Join an existing company account or create a new one." (no please + "." at the end of a sentence)
![image](https://user-images.githubusercontent.com/55785823/111628169-34a40f80-87f0-11eb-93e5-947db0e80a2c.png)

- [ ] I think there's an extra space before "Terms and Conditions"
![image](https://user-images.githubusercontent.com/55785823/111628787-e2afb980-87f0-11eb-8018-e00a5e15edb5.png)

- [ ] Change second check box text to "I hereby accept the Processing of my Personal Data and declare to know the Conditions of such Processing and my rights under GDPR Regulation."
![image](https://user-images.githubusercontent.com/55785823/111628513-96fd1000-87f0-11eb-9b0a-8fbc6ea1b5b6.png)

**Comment by phpgeekfr** [comment]
> "Email" title is not aligned on the left

This is because of the mail icon, can't do anything about this,

**Comment by maltmayer** [comment]
### SIGN UP / "Thank you for joining us!"

- [ ] A snackbar showed up when I arrived on this page but didn't get the time to read it / screenshot. Should appear a bit longer.

- [ ] Change introduction text to:
"We care about security on the Cascade8 applications. Please validate your email to help us authenticate you. 
The ((app name)) Team will come back to you shortly concerning your Company Account creation request.
- [ ] Contact us should be underlined (I think) and clickable.
- [ ] There should be more space before all "i" information icons. There too close to the text.
- [ ] The refresh icons are confusing, we want to click on them to resend email. Or refresh page... They feel clickable. Could we have them clickable? If so, I think they should refresh the page.
- [ ] "Refresh your page" button should say "Refresh Page"
- [ ] "Refresh your page" button is too close to the Contact button (to me at least) 
![image](https://user-images.githubusercontent.com/55785823/111628957-125ec180-87f1-11eb-814c-b3da586e84f9.png)

- [ ] Change Profile Data tooltip to: "Fill in your Personal Information (First Name, Last Name...)"
![image](https://user-images.githubusercontent.com/55785823/111630075-438bc180-87f2-11eb-90dc-d20ed98e57d6.png)

- [ ] Change Organization Data tooltip to: "Fill in your Company Information (Activity, Country...)"
![image](https://user-images.githubusercontent.com/55785823/111630176-5ef6cc80-87f2-11eb-9972-5ba18bd0d323.png)

- [ ] Change Email Validation tooltip to: "Click the link provided in your verification email."
![image](https://user-images.githubusercontent.com/55785823/111630338-8baae400-87f2-11eb-86a2-e3d0befcfb22.png)

- [ ] Change Organization Approval tooltip to: "Please wait for the ((app name)) team to verify the company information you provided."
![image](https://user-images.githubusercontent.com/55785823/111630781-007e1e00-87f3-11eb-895c-69f953216aba.png)

**Comment by maltmayer** [comment]
Following a discussion with @Jackseed, we should change the notion of "Invitation code" to "Invitation Pass" for the "First Invitation page" meaning:

- [ ] Change "Invitation Code" to "Invitation Pass"
- [ ] Change hint text from "You can find your invitation code in your invitation email." to "Your Invitation Pass is the code you received in your invitation email."
![image](https://user-images.githubusercontent.com/55785823/111634223-9798a500-87f6-11eb-8d29-5b8b1d889b2c.png)

**Comment by phpgeekfr** [comment]
Please choose a text so we can stick to it ..
You already made changes to `Change hint text from "Check up your invitation mail to get the invitation code." to "You can find your invitation code in your invitation email."`

**Comment by maltmayer** [comment]
- [ ] Company Activity list is in alphabetical order. That's perfect, except for "Other" that should be the last value of this list if that's possible to make the exception
![image](https://user-images.githubusercontent.com/55785823/111636800-1c84be00-87f9-11eb-8c4c-ede36928af4a.png)

**Comment by pldespaigne** [comment]
> Some already existing films have image issues. This movie for example: 83mxbXLYfgzyRsfCcd9k. This one too: c8e3k3RhlE1oQK2RWMJ3 (need investigation @pldespaigne)

After some investigation I found that the db has images path that point to files that doesn't exists in the storage.
So it's perfectly normal that the app cannot display them.
This is either linked to an ops problem or a delete bug in prod.

What I would recommend is to run cleaning script to delete orphaned db ref.

**Comment by maltmayer** [comment]
> > Some already existing films have image issues. This movie for example: 83mxbXLYfgzyRsfCcd9k. This one too: c8e3k3RhlE1oQK2RWMJ3 (need investigation @pldespaigne)
> 
> After some investigation I found that the db has images path that point to files that doesn't exists in the storage.
> So it's perfectly normal that the app cannot display them.
> This is either linked to an ops problem or a delete bug in prod.
> 
> What I would recommend is to run cleaning script to delete orphaned db ref.

Hmm... It's definitely a delete bug as the images used to exist. Could we identify the deleted images to replace them?

**Comment by maltmayer** [comment]
### EMPTY DASHBOARD HOMEPAGE / TITLES

- [ ] Change Title from "You have no title yet." to "No title to display"
- [ ] Change the bulk import text to from Import you titles in bulk" to "Import titles in bulk"
- [ ] Change CTA text to: "Contact the ((app name)) team"

![image](https://user-images.githubusercontent.com/55785823/111637351-a0d74100-87f9-11eb-9403-4cf12d1b704d.png)

### EMPTY DASHBOARD TITLES

- [ ] Add CTA to match with Empty Dashboard Homepage.

**Comment by maltmayer** [comment]
### ORGANIZATION PAGE
- [ ] Country should stay mandatory once you're logged in (as it is when you sign up)
![image](https://user-images.githubusercontent.com/55785823/111638306-7cc82f80-87fa-11eb-85a4-d731fb09e1c5.png)

**Comment by phpgeekfr** [comment]
>     * [ ]  Company Activity list is in alphabetical order. That's perfect, except for "Other" that should be the last value of this list if that's possible to make the exception

@maltmayer like this with a divider ? 
![image](https://user-images.githubusercontent.com/1194344/111759592-0bda5380-889e-11eb-9571-a2d88ec8ef1d.png)

**Comment by maltmayer** [comment]
> > ```
> > * [ ]  Company Activity list is in alphabetical order. That's perfect, except for "Other" that should be the last value of this list if that's possible to make the exception
> > ```
> 
> @maltmayer like this with a divider ?
> ![image](https://user-images.githubusercontent.com/1194344/111759592-0bda5380-889e-11eb-9571-a2d88ec8ef1d.png)

Yes great but no divider please :)

**Comment by maltmayer** [comment]
### DASHBOARD HOMEPAGE
- [ ] I get an empty page for a few seconds before it loads:
![image](https://user-images.githubusercontent.com/55785823/111769812-ee12eb80-88a9-11eb-9ea9-e1582738b24d.png)

### ADD NEW EVENT

- [ ] There should be a bit more space between "All day" and "Accessible..." to show we're not talking about the same information
- [ ] If possible, even better to add a title for the privacy section: "Privacy"
- [ ] Change text from "Accessible only on invitation (private event)" to "PRIVATE EVENT - upon invitation only"
- [ ] Change text from "Do not show on Marketplace" to "SECRET EVENT - not listed on the Marketplace"
![image](https://user-images.githubusercontent.com/55785823/111770247-75f8f580-88aa-11eb-98b9-8c4f5d883998.png)

**Comment by maltmayer** [comment]
### DASHBOARD 

- [ ] Dashboard Homepage and Movie List loading component is not centered the same. Choose one and apply to all.

![image](https://user-images.githubusercontent.com/55785823/111771851-75615e80-88ac-11eb-9be5-995753c889d5.png)
![image](https://user-images.githubusercontent.com/55785823/111771876-7a261280-88ac-11eb-8948-5301d65c6acd.png)

**Comment by maltmayer** [comment]
### DASHBOARD EVENT FORM / SCREENING

- [ ] Why is there a "Video Call link" here? Actually it's a good thing to show a direct link for screenings too but 1. the link is not good (replace /lobby by /session) 2. Change text to "Direct link to Screening Room"

![image](https://user-images.githubusercontent.com/55785823/111772613-57482e00-88ad-11eb-8883-ec677c3290f2.png)

- [ ]  There should be a bit more space between "All day" and "Accessible..." to show we're not talking about the same information. If possible, even better to add a title for the privacy section: "Privacy Settings"
- [ ]  Change text from "Accessible only on invitation (private event)" to "PRIVATE - upon invitation only"
- [ ]  Change text from "Do not show on Marketplace" to "SECRET - not listed on the Marketplace"

![image](https://user-images.githubusercontent.com/55785823/111773387-65e31500-88ae-11eb-9471-f7552917b4a5.png)

- [ ] tooltip looks is too far from the icon
- [ ] should the "i" icon be aligned vertically with the text?
- [ ] I think it would be more logical if tooltip appear on the right, here, instead of under the icon.
- [ ] Change text from "Only users with a direct link will be able to access your event."

![image](https://user-images.githubusercontent.com/55785823/111773060-f3723500-88ad-11eb-8c32-fe446361eca4.png)

- [ ] Empty stats illustration display issue 

![image](https://user-images.githubusercontent.com/55785823/111773516-9165ff80-88ae-11eb-812c-9e210a566ee4.png)
