### ISSUE TITLE
Multi-org actions and states

### ISSUE THREAD

**Issue by 2amarkina** [blockframes/blockframes#5732]
This issue aims co cover all the possible cases when a title is owned by n+1 orgs. 

### Where exactly multi-org can be used? 

**General**

- How many Title owners can exist? 
- Can a new owner be added while a title already exists, can an old one be deleted? 
- Does it happen inside the app?
- Does it happen from app to app?
- Can the different owners have the same activity? (two Sales Agents, three Distributors etc...)

**Title Creation / Movie Title / Title Edit**
- How do we know that a title is owned by other organizations? 
- How could we check that other organizations have not already created a Title (which remains in Draft and not Published) ? 
_N.B. we need to avoid that a user learns that the title exists after filling in the Movie Title, which is pretty long and can lead to frustration._
- What should we do if N of other owners are not using any of the apps? 
- How do we inform other owners that a Title on their name was created?
- Do other owners need to give their confirmation for creation? 
- When should it happen: after the draft is created or title is published/submitted? 
- Do we need to inform other owners about the modifications made on the title?
- Same questions should be answered for the case when the titles are imported in bulk. 

**Dashboard View** 
- Do we need to add a column “Other owners” on the My Titles page to see who are the other eventual owners?
- Do we need to reflect this information on the Film Page? 

**Marketplace View**
- Org List: Do we show the same Title in the line-up of several organizations?
- Be able to show several organizations on the same line
- Think over what happens, if two many organizations? 

### Specific cases:

**Archipel Content**
- On the Avails page we propose a user to contact a Company if territory is not licensed. The click on the “Company Name” leads to the Company’s Page. 
- But what happens if there are many Companies to contact? 
- The best would be to regroup all of them and open mail clients, but (!) Will it mean for the design to change the style of the link and transform it into a button? (should be seen and discussed with link/button reflexion, as it opens the email client an anchor tag can be used). 
- Split of Rights what happens exactly when the Title Rights are sold? Can we say that a Title belongs to the organization who owns the rights? 

**Media Financiers**
- Same question, if there is an investor who has financed a film, will we show him as a second organization?

**Archipel Market**
- How to display many organizations on the Event Creation page? (Organized by) 
- How to display many organizations on the Event Page? 
- How to display many organizations on the Screening page?

**Comment by 2amarkina** [comment]
Wireframes for proposition of Title sharing is available [ here ](https://www.figma.com/file/HlvddDfmXibVkK5p6vPHfU/Multi-Organizations)

### Main rules
- Max number of organizations that can simultaneously share a title is set to 3. 
- As we said that there can be only 3 organizations that are shown. This should be also reflected in design. The rule can be: if user shared a title with two organizations, then do not show "share with Company" action
![Снимок экрана 2021-06-03 в 09.50.03.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/9dfdf220-0cb0-4a01-bf74-43fd7e3d7632)
- If user can add an owner org, user also needs to be able to delete one (if it was a mistake or if other organization is no longer an owner). Three versions are presented on wireframes. 
- Only the organizations that belong to the particular application can be shown. 


### Questions to discuss:
- [ ] do we need to add a supplementary column on Dashboard View - My Titles list ? 

As the situation of having more than one owner organization remains rare, would still propose to add this column, but deactivate it by default. If user needs to see it, s/he would activate it via filters. 

![Снимок экрана 2021-06-03 в 09.12.02.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/990274a1-d11f-452d-8a45-9cccc174f976)

- [ ] Find a synonym to "to share" 
Partake? 

- [ ] do we allow inviting other owner-organizations who are not on the platform? 
On the one hand, this could attract more people and we could have more users. On the other hand this process of waiting for a new owner to connect can take time and we should have supplementary flows describing this process.

**Comment by 2amarkina** [comment]
**After a dev check**
- [ ] Are we sure about 3 orgs? It's problematic and can break the structure. 
- [ ] Not sure about deleting an organisation from the owners. If this happens not so often, then not worth the effort to introduce this action.
