### ISSUE TITLE
General layout: header, footer, navbar,...

### ISSUE THREAD

**Issue by RemcoSimonides** [blockframes/blockframes#5910]

**Comment by phpgeekfr** [comment]
There is tiny shift on the "Schedule a demo" button depending on the app we are on:

![image.png](https://images.zenhubusercontent.com/5c6e955fdecd2e3c69b6c1d2/2d38f702-6dee-4463-a857-52e2c6c16dbd)
![image.png](https://images.zenhubusercontent.com/5c6e955fdecd2e3c69b6c1d2/40b44afa-5c29-4c0b-bfcc-ca8811f08978)
![image.png](https://images.zenhubusercontent.com/5c6e955fdecd2e3c69b6c1d2/534bb7a3-c223-4eca-9f2f-8f5c6a2fb68e)

**Comment by RemcoSimonides** [comment]
You have a good eye for details 🤣 I don't think this needs 'fixing' since users to have all three apps open at the same time and then care about this tiny UI difference

**Comment by SamirTouira** [comment]
Haha if an user find this tiny difference I let him my place and the beer is on me

**Comment by RemcoSimonides** [comment]
App logo, Footer & filled or stroke buttons
### Localization
- App name: Market
- Page: https://staging.archipelmarket.com/c/o/marketplace/home
- Url: https://staging.archipelmarket.com/c/o/dashboard/files

### Fix
- [ ] Logo (tag element app logo) should be 48px height instead of 60px.

<img width="502" alt="Capture d’écran 2021-06-02 à 11 05 05" src="https://user-images.githubusercontent.com/66258851/120452875-d3252300-c392-11eb-9c25-35a844467c82.png">
<img width="395" alt="Capture d’écran 2021-06-02 à 11 06 49" src="https://user-images.githubusercontent.com/66258851/120452889-d7514080-c392-11eb-995f-f5af7054fc05.png">

- [ ] Buttons need to be fixed sizes not fluid (just like before the material updates)
related doc for integration here

<img width="490" alt="Capture d’écran 2021-06-02 à 11 09 00" src="https://user-images.githubusercontent.com/66258851/120453257-2b5c2500-c393-11eb-9698-4f1b9d3efed0.png">
<img width="789" alt="Capture d’écran 2021-06-02 à 11 09 10" src="https://user-images.githubusercontent.com/66258851/120453276-30b96f80-c393-11eb-9597-5886149e2742.png">

- [ ] Footer. Reduce padding from 40px (top and bottom) to 24px.
App logo size in footer from 60px to 48px just like in the toolbar.

**Comment by RemcoSimonides** [comment]
- [ ] If time left before the release: https://github.com/blockframes/blockframes/issues/5228
This is a component for a button without padding left. Making the 'Move to wishlist' aligned to the left
![image](https://user-images.githubusercontent.com/27687382/120614075-2365b900-c457-11eb-926b-af680bdc9430.png)

**Comment by Jackseed** [comment]
/c/o/marketplace/privacy
/c/o/marketplace/terms
- [ ] Back button doesn't work on these 2 pages, maybe linked to #5743?

**Comment by Jackseed** [comment]
url: https://staging.archipelcontent.com/www.test.com
- [ ] @SamirTouira re #5666 the 404 page isn't exactly the same as @jdrns's design > text "Page not found / The page you're looking for cannot be found." should be inside the illustration and not above
see design
![image](https://user-images.githubusercontent.com/14964443/120645466-bebb5600-c478-11eb-9885-10a50ca425fe.png)
vs implementation
![image](https://user-images.githubusercontent.com/14964443/120645434-b6631b00-c478-11eb-9b36-36007cc86c67.png)

**Comment by Jackseed** [comment]
- [ ] Remove "Offers & Deals" in catalog sidenav 
![image](https://user-images.githubusercontent.com/14964443/120675471-634b9100-c495-11eb-9e09-ccbce08fe7f6.png)

**Comment by RemcoSimonides** [comment]
@SamirTouira 
full size for images, docs etc. doesn't work (maybe Safari only related)
![image](https://user-images.githubusercontent.com/27687382/121191597-687d5700-c86c-11eb-8718-123b0eee6987.png)

**Comment by phpgeekfr** [comment]
Alt on invitation icon :
![image](https://user-images.githubusercontent.com/1194344/121204993-9916be00-c877-11eb-87f7-1f70cbafd0e2.png)

**Comment by RemcoSimonides** [comment]
Create new issues for what's left:
#6007
#6008
