### ISSUE TITLE
[CRM] Archipel Content

### ISSUE THREAD

**Issue by GrandSchtroumpf** [blockframes/blockframes#5984]
[Zeplin](https://app.zeplin.io/project/6075614f83ab0350cbea888a)

## Pages

---
## IceBox (Do Not implement)
Contract List
- Query the list of contracts of an offer: `contractService.valueChanges(ref => ref.where('offerId', '==', offerId))`.
- Group everything related to the title (name, id, poster) in one column and use a pipe to query it in the template (@2amarkina approved).
- Use `<bf-table-filter>` (`libs\ui\src\lib\list\table-filter\table-filter.component.ts`) for the table.

---

# Already Done
## Pages
- [x] Contract Form (#6082) (@jeremie74)
[zeplin](https://app.zeplin.io/project/6075614f83ab0350cbea888a/screen/6081beb10b9148145de61fd6)

- [x] Offer View Page (#6072) **(@iPR0D1G1 )**
[zeplin](https://app.zeplin.io/project/6075614f83ab0350cbea888a/screen/6081be7f042d9a1c0d4856f3)

- [x] Shell Component (#6080)
- [x] Offer List page (#6070) **(@iPR0D1G1 )**
[zeplin](https://app.zeplin.io/project/6075614f83ab0350cbea888a/screen/6081be794300b91e99bf6ad4)
Use `<bf-table-filter>` (`libs\ui\src\lib\list\table-filter\table-filter.component.ts`) for the table.
- [x] Contract/Title View (#6081)
[zeplin](https://app.zeplin.io/project/6075614f83ab0350cbea888a/screen/6081be816b999f14b7d03718)

[Dialog Validation on delete](https://app.zeplin.io/project/6075614f83ab0350cbea888a/screen/6081be848d30082175f65245): 
- open dialog when clicking on delete action button
- [x] Offer View
  - use a `<ng-template>` in the template of the offer view instead of creating another component
- [x] Contract View
### Offer

- [x] Update the Offer interface in `libs\contract\src\lib\offer\+state\offer.model.ts` to have `buyerUserId` which should be userId that triggered the contract.
- [x] Update `libs\contract\src\lib\bucket\+state\bucket.service.ts` to add `specificity`, `buyerId` & `buyerUserId` also in the offer when we create it.

### Contract
- [x] Update the Offer interface in `libs\contract\src\lib\bucket\+state\bucket.model.ts` to have `buyerUserId` which should be userId that triggered the contract.
- [x] Update `libs\contract\src\lib\bucket\+state\bucket.service.ts` to add `specificity`, `buyerId` & `buyerUserId` also in the offer when we create it.
- [x] Extract the contract table on the terms from the selection page (`apps\catalog\catalog\src\app\marketplace\title\selection\selection.component.html`) into a `<contract-item>` component inside the `libs/contracts/lib/contracts/item` folder. It should look like that:
```html
<contract-item [contract]="contract">
  <contract-price>
    <!-- Can be a form or display -->
  </contract-price>
  <contract-actions>
    <!-- Action buttons for the contract -->
  </contact-actions>
  <ng-template termAction let-term let-index="index">
    <!-- Action buttons to display in the action cell per term -->
  </ng-template>
</contract-item>
```
