### ISSUE TITLE
Add email verified to Users' meta data

### ISSUE THREAD

**Issue by RemcoSimonides** [blockframes/blockframes#6089]
- [x] Email Verified should be updated once the User verified his email.
- [x] Add the field in CRM app
- [x] Show the 'Verify email' button if the user has not verified his email yet.
- [x] Get data from Firebase Authentication and add it to Users meta in migration. While you're at it, also add date created to the Users meta for the Users who don't have it yet. This is useful for Analytics.

**Comment by Jackseed** [comment]
@RemcoSimonides Verify button doesn't seem to work... 
I created a fresh new user and tried to verify his email through CRM but clicking on the button doesn't do a thing

If you want to give it a try on staging you can go here 
https://staging.crm.blockframes.io/c/o/admin/panel/user/6KfCviZH7OQubjSsSBko194bqi43
dev+heloise-kbl@blockframes.io

**Comment by RemcoSimonides** [comment]
@Jackseed did you refresh the page on CRM? or try to login with that account?
I can login and access the app with that account now so you did verify it's email

But I'll add some snackbar or something on CRM when you click the button so you see something happening

**Comment by Jackseed** [comment]
@RemcoSimonides oh sh*t I must have clicked on the email link.
I'll test again in an hour but the problem was not only the feedback (snackbar) but also that the value was still `false` after I clicked

**Comment by Jackseed** [comment]
@RemcoSimonides ok so my bad it does work but it definitely lacks a snackbar "Email verified." or similar.
+ if possible change the email verified value for an observable so we instantly see that it worked?
