### ISSUE TITLE
TODO : Improvements in Investor Email E2E Test

### ISSUE THREAD

**Issue by xmano** [blockframes/blockframes#6698]
Need to do some changes to the test that I have written.

- [ ] Check again if logic can be improved for detecting the email
- [ ] Add comment explaining the logic
- [ ] Keep code consistent - use camelCase for email_ready, test_info  
- [ ] See if more e-mail scenarios can be covered (if possible to do easily)

**Comment by xmano** [comment]
Got an idea - capture the old email address 💡  - should work.!
