### ISSUE TITLE
[CATALOG] Dashboard Sales Import page

### ISSUE THREAD

**Issue by pldespaigne** [blockframes/blockframes#6752]
_main issue #6709_

![image](https://user-images.githubusercontent.com/5858657/134940733-66522b58-b8c3-4f8d-9cfd-7972253e9c39.png)

[Figma > Import](https://www.figma.com/file/PYeqGtG6W6GgArp743bcQ1/[-Availabilities-])

---

- [ ] create new component called `catalog-sales-import` in `apps\catalog\catalog\src\app\dashboard\sales\import\import.component.ts`

- [ ] mount this component on the route `/c/o/dashboard/sales/import`

- [ ] let the user download a template excel file

- [ ] implement the excel import logic to create multiple sales in the db from a single excel file, the UI and the flow should look very similar to the title import in `/c/o/dashboard/import`

**TODO** : This issue is not very well defined, we need to add more detail when we will have more knowledge from the devs working on the excel import refactor (@iPR0D1G1, @GrandSchtroumpf, @phpgeekfr) and from de design team for the screens @2amarkina)
