### ISSUE TITLE
Events without login

### ISSUE THREAD

**Issue by phpgeekfr** [blockframes/blockframes#6756]
This epic will gather all the issues we need to tackle to allow users to create public events and access events without being logged in the platform.

The new kind of event "slate" #5397 is not covered by this epic but we should keep in mind that this will be done after so let's think about it when doing this epic.

Figma: https://www.figma.com/file/ZPn46rpEnjnIgQJpxt7smY/%5B-Connection-to-Event-%5D?node-id=104%3A923
Zeplin : https://zpl.io/29MX9gl

Related design issue #6361

- [x] data model update (from boolean to list for privacy settings) #6776
- [x] mails refactoring #6784 
- [x] short form update #6785
- [x] classic form update #6786
- [x] New ways to access events #6787
- [x] rules and routing (including redirections for events created before the release of this new feature) #6861
- [x] check for `#6756` in code
- [x] check / ask UX if a button 'resend email verfiy' is needed
- [ ] for invitation-only event, if user enter an email that belongs to a real account, redirect him to login page instead ?

before release, check current events planned :
 - [x] need to send an email to users ?
 - [x]  redirections for events created (and invitations sent) before the release of this new feature to new event links structure

**Comment by phpgeekfr** [comment]
First draft of time estimates ![image.png](https://images.zenhubusercontent.com/5c6e955fdecd2e3c69b6c1d2/f9e70455-ba1c-4018-a066-5b604ab624e8)

**Comment by phpgeekfr** [comment]
Some questions already answered or waiting for a response:

- wording : public, private, super-private . WIP can change
- if event is super-private, no need to display the "choose your role" screen => update #6787
- If event is public or private but user is logged in: if possible, would be great to add the top bar menu (notif, user menu...)
- for private event, if entered email belongs to an existing (and valid, with orgId) account : add a new email input for regular login.
- in public or private events, the CTA "invitation pass" will always be there
- for now, no need to display event list or calendar for non logged in users
- not possible to access a private event with email if I'm not invited to it

**Comment by phpgeekfr** [comment]
When this will be deployed in production: we will need to check with @Jackseed  how the coming events should be handled, especially the ones with `isPrivate = false`. Event links will maybe change (need a redirection ?), and the way that the events will be accessed will change also: guests will be allowed to attend events without invitation and without giving an `email`

**Comment by Jackseed** [comment]
Glad you mention it, I'll check with Marie but there is a 90% probability that the only incoming events at the time of the release will be private ones. 
Should we prepare for a change for pre-existing private events?

**Comment by phpgeekfr** [comment]
There might be an url change fo pre-existing private events and right now I think this will be the only change and  I think we can handle some redirections for this.
I'm also not 100% sure that everything will be ready for next release. We still have time but also a lot of work to perform. Lets hope :)

**Comment by Jackseed** [comment]
ok good to know, then maybe we shall rearrange things
cc @RemcoSimonides mb to discuss for next sprint
