### ISSUE TITLE
Fix existing falling E2E tests on each PR

### ISSUE THREAD

**Issue by phpgeekfr** [blockframes/blockframes#6757]
We need to fix following E2E Tests

https://github.com/blockframes/blockframes/issues/8220 :   Create Screening

https://github.com/blockframes/blockframes/issues/6954 :  Screening Invitation

https://github.com/blockframes/blockframes/issues/6951  :  Import Movies 

https://github.com/blockframes/blockframes/issues/6952  :  Create Bucket

**Comment by xmano** [comment]
Have analyzed the problem and testing possible fix here:
https://app.circleci.com/pipelines/github/blockframes/blockframes/20517/workflows/47a7ab51-d07c-4e80-8cce-7fed7a6d742d/jobs/31965

**Comment by xmano** [comment]
This issue will address failures with 2 tests:

- [ ] screening-invitations-2688.spec.ts
- [ ] create-screening-2687.spec.ts

**Comment by phpgeekfr** [comment]
- [ ] Fix the email test in festival (intermittent)
