### ISSUE TITLE
Release 3.6

### ISSUE THREAD

**Issue by RemcoSimonides** [blockframes/blockframes#7343]
**All fixed issues** for this release can be found [here](https://app.zenhub.com/workspaces/blockframes-60b0a31838e485001b3a619f/reports/release?release=Z2lkOi8vcmFwdG9yL1JlbGVhc2UvNjg1MzE&invite=true)

Of which the new **main features** are:
- [Export Catalogue to PDF](https://github.com/blockframes/blockframes/issues/7045)
- [Buyer Preferences](https://github.com/blockframes/blockframes/issues/6996)

Soon ready:
- [Archipel Content Landing page](https://github.com/blockframes/blockframes/issues/7269)

Link to [all test scenarios](https://www.notion.so/cascade8/All-Test-Scenarios-e4e937051d264f98abe65fe3190bfbe9)

**Comment by 2amarkina** [comment]
OS: Mac BigSur, 11.6
Browser:  15.0  

# App tested: ARCHIPEL MARKET

### Buying Preferences (modal)

- [ ]  Follow up the design remarks in [#7326 ](https://app.zenhub.com/workspaces/design---ui-60ab5f96c64ec50014c46754/issues/blockframes/blockframes/7326)

- [ ] In the field "Languages" we have "All languages" (this element we do not find neither in "Languages and versions" filter, nor in Movie Tunnel). I guess that all the languages are ordered alphabetically, but maybe it's possible to put it on the 1st place? ![Снимок экрана 2021-12-08 в 09.57.20.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/b389283e-d6dd-42da-b712-15b6b767bc9f)

### Buying Preferences (profile page)
- [ ] To keep the naming consistent, change the name of the tab from "Buyer Preferences" to "Buying Preferences", @maltmayer is it ok for you?

- [ ] As for the modal, remove the titles to have make the make less "heavy" 
![Снимок экрана 2021-12-08 в 10.10.57.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/02faf852-8112-493f-b70b-8443e0879f59)

- [ ] @Jackseed , @cams-goussale , @maltmayer if we use "all languages" logic, maybe need to introduce the "all genres" logic too, or maybe remove the "all languages" ? 

- [ ] Snackbar text proposition instead of "Preferences updated !" : "Buying preferences successfully updated", @maltmayer is ok for you? 
![Снимок экрана 2021-12-08 в 10.20.36.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/fbd760ba-c896-4e7f-9861-092946030252)

### Buying Preferences (modal + page)
- [ ] When a user clicks on "Save" or "Update" CTAs, Marie and Yuki should receive these informations by mail

**Comment by Jackseed** [comment]
> * [ ]  @Jackseed , @cams-goussale , @maltmayer if we use "all languages" logic, maybe need to introduce the "all genres" logic too, or maybe remove the "all languages" ?

- [ ] We should remove "All languages" and keep genre list as it is

> Buying Preferences (modal + page)
 When a user clicks on "Save" or "Update" CTAs, Marie and Yuki should receive these informations by mail

- [ ]  Emails will be too much / out of the scope of this release but indeed we need to be able to extract that data. Ideally we should add the 4 columns to user list in the crm and add these same columns to the csv export. 

> In the PDF we can see that all titles that are exported contain the link to the trailer (but it's not the case). If there is no trailer, we should keep only the "see title" button and center it, like in the example below, @Jackseed , @cams-goussale what do you think?
Снимок экрана 2021-12-08 в 10.38.32.png

- [ ] Yes ok for me

**Comment by RemcoSimonides** [comment]
Moved your comments to the sub issues :)
