### ISSUE TITLE
Release 4.0 - Avails

### ISSUE THREAD

**Issue by RemcoSimonides** [blockframes/blockframes#7982]

**Comment by RemcoSimonides** [comment]
Please also update the test scenarios if something new needs to be tested.

**Comment by cams-goussale** [comment]
@Poppe-A I have the final CGV. Do you need a pdf file or [google doc](https://docs.google.com/document/d/1TcAtiLh1ALF6Xp3V3wwI_97lqsDApY3e/edit)?
[TCs - Archipel Content.docx.pdf](https://github.com/blockframes/blockframes/files/8265240/TCs.-.Archipel.Content.docx.pdf)

The places where it needs to be added are:

- [ ] The auth page (this issue: #7938)
- [ ] Inside the modale of the Deal nego flow (this issue: #7743)
- [ ] In a couple of emails of this issue #7742 (template id: `d-c32f642c1c2d45f285aa926322518957` and `d-b928481ce938423dabb34e50c264d320`)

**Comment by cams-goussale** [comment]
- [ ] After discussions with @yspringfield and @GrandSchtroumpf we decided to remove this issue #7887 from the release and take more time to think over the logic. It's quite a localized piece of code so hopefully it does not impact too much the code.

**Comment by phpgeekfr** [comment]
- [ ] when clicked on "send your offer button"  ![image.png](https://images.zenhubusercontent.com/5c6e955fdecd2e3c69b6c1d2/437678be-3dc1-4e9e-933a-b193d0ac44b5) 
In the background I'm redirected to https://staging.archipelcontent.com/c/o/marketplace/selection but popin does not disappear and I have this error in console : 
```
TypeError: l is null
    l https://staging.archipelcontent.com/6575.529cdd80c1505b81cf9f.js:1
    c https://staging.archipelcontent.com/6575.529cdd80c1505b81cf9f.js:1
    c https://staging.archipelcontent.com/6575.529cdd80c1505b81cf9f.js:1
    a https://staging.archipelcontent.com/6575.529cdd80c1505b81cf9f.js:1
    value https://staging.archipelcontent.com/polyfills.d8563f0a7951ef3c12a9.js:1
    onInvoke https://staging.archipelcontent.com/main.e6dcec4c7ce508c5b805.js:1
```

**Comment by phpgeekfr** [comment]
- [ ] when looking at a specific offer, no title in array 
![image.png](https://images.zenhubusercontent.com/5c6e955fdecd2e3c69b6c1d2/9c454c24-37c4-4bf3-a0fb-34311efd0aa1)

**Comment by cams-goussale** [comment]
Some reviews related to the change of Terms & Conditions on Archipel Content.

- [ ] (A) These email templates have links to the T&C. I've put the variable `{{{pageUrl}}}` in Sendgrid. Should I add something else?
`d-c32f642c1c2d45f285aa926322518957`
`d-b928481ce938423dabb34e50c264d320`
![image](https://user-images.githubusercontent.com/93206363/159303109-b86a5f56-8114-4a10-80e6-d3ba54aa6036.png)


- [ ] (A) In these same templates, the `Reason` section had an if statement I think. It should only show if there is a message.


- [ ] (B) In this modale, when a user sends an offer, can we change some texts?
The checkbox for `I confirm that I have read and agree the Terms & Conditions that will applied to the offer.` with a link on `Terms & Conditions`
The text at the beginning for `Please indicate any specific conditions you'd like to request for this deal.`
![image](https://user-images.githubusercontent.com/93206363/159304228-2fa39da7-3061-45be-ab5d-b178cd4294d6.png)


- [ ] (B) On these 2 pages, are we able to change the button `See Standard Terms` to `See Terms & Conditions` and redirect to the T&C ?
`/c/o/dashboard/sales/[salesId]/view`
`/c/o/marketplace/sales/offer/[offerId]`
`/c/o/marketplace/sales/offer/[offerId]/[salesId]`
