### ISSUE TITLE
library refactoring

### ISSUE THREAD

**Issue by george43g** [blockframes/blockframes#8051]
There are still types held in other libraries

- [x] Please move the following dir into models:

`libs/utils/src/lib/static-model`

- [x] As well as this, the model lib should be in a shared folder

`libs/shared/model`

- [ ] and we should make a new one:

`libs/shared/util` - this lib should hold all pure js/ts functions that are not part of the data model, but that may be used by the model lib.

`libs/utils` is a mess of a lib - it holds both angular services and many shared pure js utility funcs. Please separate these out into either the shared/model lib or shared/util lib.

For the remainder of the `utils` that are angular/browser based code, these should be moved into an area that is meant for browser based code. Since multiple front-end apps share these functions, these should likely be in feature based libs. So there should be a dir like so:
libs/<dirName>/ui-animations - all animations shared by angular apps
libs/<dirName>/sendgrid/data-access
etc...

## Todo

- [ ] remove libs/firebase-utils/src/lib/queue.ts - not useful. refactor and test anonDb process after this

- [ ] libs/utils/src/lib/maintenance/index.ts - move this logic into shared/utils lib when created, move the consts into a const lib once created. 

### Proposed structure
libs/shared/{model|util|constants|env} - these will all be shared, pure TS libs. We will route all of our @env imports through a new env lib to be able to manage dependencies and see it on a dependency graph. We will also be able to add some simplifying logic into our env.ts code to reduce duplication, and programmatically access specific envs if needed.

**Comment by phpgeekfr** [comment]
@george43g please put here the architecture you want for this and how to use the nx tool to change library name

**Comment by phpgeekfr** [comment]
https://github.com/blockframes/blockframes/pull/8064

**Comment by phpgeekfr** [comment]
lets keep it for the record
