### ISSUE TITLE
Catalog app April fixes

### ISSUE THREAD

**Issue by cams-goussale** [blockframes/blockframes#8089]
Following the March release, we still notice some important changes necessary on catalog app.

- [x] https://github.com/blockframes/blockframes/issues/7830 : Bug
- [x] https://github.com/blockframes/blockframes/issues/7887 : needs discussion with Camille
- [x] https://github.com/blockframes/blockframes/issues/8075 : Camille will make a template proposal
