### ISSUE TITLE
Contract form or Mandate import for Users

### ISSUE THREAD

**Issue by cams-goussale** [blockframes/blockframes#8668]
Let's give the option to Sellers of Archipel Content to create their own Mandates (= availabilities).

As agreed with Francois, due to the limit of time, we shall reuse the form we already have (the rights card). I think the only difference that would appear on this form is the selection of the movie (a mandate is attached to a movie). If possible, we can draft 2 option:
- scenario 1: user clicks on Add mandate (or add avails) on the My Deals page and there is a drop down to select the movie
- scenario 2: user clicks on Add mandate on the movie page and there is only the rights card to fill in.

**Comment by 2amarkina** [comment]
**Work in progress started** [here](https://www.figma.com/file/ZqxoZKhfiKdOT6BUg8DAB0/Contract-form-or-Mandate-import-for-Users-(%238668)?node-id=0%3A1)

**TO DO:** 
- [ ] Finish the screens and scenarios
- [ ] Validate the feasibility / flows with Springfield and Vincent (and François if possible)
- [ ] Validate the texts with business team

**Comment by 2amarkina** [comment]
Last wireframes https://www.figma.com/file/ZqxoZKhfiKdOT6BUg8DAB0/Contract-form-or-Mandate-import-for-Users-(%238668)?node-id=55%3A33016

**Comment by cams-goussale** [comment]
@2amarkina @yspringfield @phpgeekfr could we also add to this issue the following:

Currently when going to the Contracts page on CRM, there is only the external sales showing. Could we show all created contracts type? (mandates + external sales)

![image](https://user-images.githubusercontent.com/93206363/176201277-ebcfc3ff-b380-46e7-9fa2-f410bdfa9d59.png)

**Comment by yspringfield** [comment]
Yes, will do that.

**Comment by cams-goussale** [comment]
# Review 08.07.22

### Creating new Terms

- [ ] When clicking the first time on the rights card to create a term, there is a jump and user must click on Add button after the jump. Console error `Cannot read properties of undefined (reading 'value')`
https://user-images.githubusercontent.com/93206363/177962746-25be9bb7-9954-4cb8-a454-fe9cc2bf629d.mp4

- [ ] When creating avails, the dates of the Rights card is prefilled. Can we have end date set to today + 1 year? Currently we have start date == end date. Can we also set Exclusivity parameter to `Exclusive` by default?
![image](https://user-images.githubusercontent.com/93206363/177963853-c5dc2c22-69cc-4396-bff5-b02a916b9fb5.png)


- [ ] Once terms are created, user should be redirected to My Avails page.

### Editing existing Terms

- [ ] When clicking on Edit Avails on the My Avails page, I get this error
`TypeError: Cannot read properties of undefined (reading 'value')`
![image](https://user-images.githubusercontent.com/93206363/177959671-1175cedc-b343-4bae-b945-4f5cccb38049.png)

- [ ] When clicking on the Edit button of the Term, could it anchor to the top of the page where the card can be edited?
https://user-images.githubusercontent.com/93206363/177960064-2a33993b-f5ac-4446-a6a2-b0c264547a6f.mp4


- [ ] When editing an existing term, there is a jump on the size of the card.
https://user-images.githubusercontent.com/93206363/177960539-46f0e779-0d60-4d16-9359-0c0a49d4ce43.mp4

- [ ] I edited termId `1ZtZEqSfKlNDkZKAxYrA` and removed 1 media of the list (`Pay Tv`) but it didn't reflect the change in db
![image](https://user-images.githubusercontent.com/93206363/177961588-20f29944-be67-4423-8e7f-8feb3a8940f4.png)
![image](https://user-images.githubusercontent.com/93206363/177961633-e97a5915-3df9-4279-8321-3f65f9cbf5ce.png)

- [ ] After Editing terms, the snackbar says `Terms created`. Ideally, it should say `Terms updated`.
