### ISSUE TITLE
Release 4.6.1

### ISSUE THREAD

**Issue by phpgeekfr** [blockframes/blockframes#9193]
This release will include small fixes but is mainly about circle env vars rotating and cleaning.

Changes:
- Small fixes see #9190
- Remove unused algolia indexes #9052
- Projet cleaning: unused firebase project, unused en vars on circleCI etc #8863

To test:
- [x] a newly created  or update movie is pushed/updated to algolia. If organization have no accepted movies, and if updated movie is accepted, org will be displayed in orgs list. When movie is submitted or accepted, notifications are sent to org #9190
- [x] `mailto` button on requested asking price email (catalog) does not contain parenthesis anymore #9190
- [x] when creator of a movie (createdBy) is deleted, CRM movie page header will display `(Deleted User)` instead of creating an error.  #9190
- [x] **Bruce** Check that algolia backend functions are working properly (staging PFT should be enough)  #8863
- [x] test Imgix including reading of a protected media on new subdomain `blockframes-protected01` ( staging & prod)  #8863
- [x] test search with algolia  ( staging & prod) #8863
- [x] test a meeting event with twilio & video sharing  ( staging & prod) #8863
- [x] test a screening event & check that screener is working  ( staging & prod) #8863
- [x] check that app is still able the send mails  ( staging & prod) #8863
- [x] test video upload: file is on storage bucket & available on jwPlayer ( staging & prod) #8863
- [x] test mailchimp, by registering to newsletter for example  ( staging & prod) #8863
- [x] **Bruce** check deploy process, updated way to authenticate against gcloud and Firebase ( staging & prod) #8863
- [x] on offer view, buyer and seller have same button behavior when price is not set (tooltip : You cannot accept a contract without a price and button is disabled)
- [x] on contract related pages, uniformized date formats to US `'MM/dd/yyyy'`
- [ ] test movie delete from CRM https://github.com/blockframes/blockframes/pull/9204

Several keys will have to be revoked just before release ( @phpgeekfr  ).

Waiting jwPlayer's support but maintenance mode may have to be set manually before release  ( @phpgeekfr  ).
If nothing change, jwPlayer delivery API secret for production will be rotated febuary 20th 11am.

See https://www.notion.so/cascade8/Release-troubleshooting-8085a54303de4019b0a129116d60fa13

**Comment by 2amarkina** [comment]
### Archipel Market
Not sure that we need to spend the time on this as the feature is not maintained, but just FYI : 
- the video sharing feature is ok, but when we want to pause video, the icon-button doesn't work
![Capture d’écran 2023-02-15 à 15.58.26.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/a406ae44-45a7-436f-b21d-e6c0ff80f072)

### Archipel Content
- [ ]  on offer view for the Buyer the tooltip doesn't work  
![Capture d’écran 2023-02-15 à 16.13.05.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/1293b04e-eddf-430f-b5af-8f213a5c4d69)![Capture d’écran 2023-02-15 à 16.14.48.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/843f50bf-85b1-483d-918d-77b56b95afe7)

**Comment by phpgeekfr** [comment]
- [ ] https://staging.archipelcontent.com/c/o/dashboard/sales page is broken with user `8XbRasGMsTZqCAyNyQTPik7nuUy1` `dev+layne-xud@blockframes.io` permission error

**Comment by phpgeekfr** [comment]
- [ ] There is some others bugs on meetings but since this feature is not used anymore I did not fix them:
 - when switching from video to PDF , videos controls can be placed on pdf controls, making PDF display impossible for the meeting 
![image.png](https://images.zenhubusercontent.com/5c6e955fdecd2e3c69b6c1d2/0c99e272-2ef1-4a6c-8b44-a3437f405378)
- to play a video, we must click on play, pause and play again (maybe something linked to auto-play). But if a guest arrive on a meeting with a video sharing already started, the video will start directly.
