### ISSUE TITLE
Release 4.6.2

### ISSUE THREAD

**Issue by phpgeekfr** [blockframes/blockframes#9258]
**Issues**
- Algolia search parameter expects string shorter than 512 bytes #9095
- Update to Angular14 & Cypress10 #9150
- Check if bigQuery backend functions can be deleted #9076
- Catalog - Remove "Contact XXX" on the marketplace movie view avails tab #9244
- Catalog - Small T&C text updates #9248
- Archipel Content (list of the rights improvement) #9216
- Update "Running Time" filter #9240
- Catalog - Commission to add #9246
- Filter "Country of Origin" #9253
- Release Year #9243 
- Marketplace title list - Add a search parameter select aside the searchbar #9064
- Searching behavior #9288
- Bug "Save preferences"#9298
- Territory Group Order #9309

**To test**
- [x] check emails with removed double `/` #9203
- [x] angular 14, quick check of everything, forms (movie form), upload, import/export, meetings, screenings, PDF, login/logout, sign-up, notif, invitations, animations, loader (ng-rive), org file Explorer, cms  ..
- [x] Data studio iframes on CRM should be gone #9076
- [x] New sentence `This amount includes the commission due to Archipel Content` during negotiation #9246
- [x] on avails map, org cannot be contacted directly #9244
- [x] on movie search, release Year, Running time & origin countries filters have changed (all apps). test url copy/paste, save/load search  etc  #9253 #9243  #9240 
- [x] some media labels have changed (`S-VOD` => `SVOD` for example) #9216
- [x] if algolia search is longer than 512 bytes, search string will be cropped #9095
- [x] errors pushed to sentry by a logged in user display uid & email on sentry's dashboard #9150
- [x] catalog app Small T&C & privacy policy text updates #9248
- [x] test new search parameters and config (title search, user search, org search etc) #9064 & #9288
- [x] test originCountries & avail territories (url, load/save search) on all apps #9298
- [x] test pdfExport (marketplace, dasboard) #9298
- [x] check analytics events (create new events) for saved search: title list, map & calendar search #9298
- [x] check that territories are ordered #9309

**Todo**

- [x] @Jackseed Manually remove savedSearch on production db before release

**Comment by 2amarkina** [comment]
A really mini correction on AM events part, necessary as we might re-use this element for Blockframes and would be good just to copy-paste this part : 

- [ ] Remove second "for" in the error text![text updates.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/95a2eb78-f7bf-4926-aed4-3bbecc51f709)

**Comment by 2amarkina** [comment]
Strange behavior while generating the Search Analytics .csv sur staging : 
- [ ] The file "Search Analytics" is blocked on the _Generating..._  state, but this process is never being finished. ![generating.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/e6205b03-4b8d-4427-9ab9-519c90bda05d)
