### ISSUE TITLE
Release 4.6.3

### ISSUE THREAD

**Issue by phpgeekfr** [blockframes/blockframes#9368]
**Issues:** 
- Algolia Question #9308
- Auth page: how to get org list before having a real user #6908
- My Movies List View / Grid View - Waterfall (and impact on Archipels) #9330
- upgradeAlgoliaMovies & upgradeAlgoliaOrgs could be improved to reduce API writes #9337
- Jump of the page (Cross-app) #9273
- Shell of the Movie Page - Waterfall #9333
- Update the Language list + Filtre #9286
- Update "Genre" Filter #9290
- Update "Festival" filter #9294
- language update needed on movies (all apps) #9359
- Cross-App UI changes (Blockframes, Archipel Content, Archipel Market) #9325
- Change bucket region for production and staging main buckets #9208
-  Update CMS Link #8655 
-  Excel templates (movies and contracts) should be updated with new languages list #9383
-  Update Medias in Excel templates #9409

**To test :** 
- [x] check that anonymous org page (accessible with QR code) are still ok. Same for public/protected events access  #6908 & #9308
- [x] check that, when creating account, form will be blocked if new org name already exists (#6908) and that existing orgs are still displayed in select (#9308)
- [x] check all pages with algolia #9308
- [x] (@phpgeekfr) during `upgrade` algolia data is still ok #9337
- [x] check that, from home or library pages, when clicking on org or title page, page is displayed from top #9273
- [x] check updated CTA on movie shell and edit button on the poster (cross app) #9333
- [x] check new "create movie" button that should be clickable entirely , removed logo in footer and other changes (cross app) #9325 
- [x] check List View / Grid View on dashboard (cross app) #9330
- [x] check new filters + saved search + copy/paste URL (cross app) #9286 #9290 #9294
- [x] test excel import (from apps & crm) & check corrected territories , languages & genres (db & algolia)  & check avails search is still giving accurate results & check avail form dashboard side #9359
- [x] check updated languages list in excel templates  #9383
- [x] check new languages list #9286
- [x] after deployment check that new bucket is ok (upload, imgix, jwplayer ..) #9208
- [x] check default date for "licence end date" when going directly to `/c/o/marketplace/title`  #8655 
- [x] test new keyword `nextYear` that can be used in CMS instead of "2024-12-30T23:00:00.000Z"  #8655
- [x]  check that media list in excel template is ok #9409

**Comment by phpgeekfr** [comment]
@Jackseed @2amarkina I did not include #9208 in this release but tell me if you want to

**Comment by Jackseed** [comment]
It can wait next one but since Ana is off a few days, mb we have time to integrate it? Depends if she already started testing

**Comment by phpgeekfr** [comment]
Ok, I don't think that she started already.  So let's do it ?

**Comment by Jackseed** [comment]
Yep let's go then!
