### ISSUE TITLE
Release 4.6.4

### ISSUE THREAD

**Issue by phpgeekfr** [blockframes/blockframes#9439]
Issues : 
- [ ] Be able to have multiple incomes per contract #9402
- [ ] New Header (Blockframes & Archipels) #9388
- [ ] sentry errors fixes #9444
- [ ] fix ng-rive #9450
- [ ] Avails Filter improvements #9375
- [ ] Show the countries selected - Territory Filter #9414
- [ ] Territory Filter Country bug - Avails #9376
- [ ] Be able to delete all the titles in Wishlist at the same time #9381
- [ ] Add "Has Avails" into the exported document #9400
- [ ] Cross-App - Capital Letters in Languages #9458
- [ ] Fill in the avails on the Film Page with the research on Library page #9384
- [ ] Increase the number of episodes - Movie Tunnel #9462

Change log :
- contracts can now have multiple incomes but contracts on catalog will still create only one income (blockframes features) but several bugs have been solved  (still several existing as this was never tester) and code cleaned. #9402
- fixed a bug when a member is removed from org but user is already deleted #9444
- New header for dashboard on all app #9388
- avails filters are now kept when going to a movie page on catalog  #9384
- ng-rive (custom loader) issue is now fixed #9450
- some avails filters and other movie list filters have been improved  (and preferences form) #9375 #9414 #9376
- All items from wishlist can now be deleted #9381
- Fixed a bug when a notification tries to display data from a removed contract #9444
- Number of episodes is now limited to 10 000 #9462
- Improved terms overlapping with other existing contracts check during import #9402
- Cleaned code for organization excel import #9402
- fixed a bug when 'centralOrg' was displayed instead of 'real' seller #9402
- fixed a sentry error that is  triggered when accessing a invalid movie on CRM #9444
- `has avails` column was added to excel import #9400
- fixed some languages labels #9458

To test : 
- [x]  test the whole avails => offer => negotiation => income displayed on front (front, notifications, seller buyer & admin emails, crm & csv export ) #9402
- [x] test to remove member from org (via crm & app) and check notifications #9444
- [x] test new header for dashboard on all app #9388
- [x] test that filters are kept when going to a movie page from movie list with valid avail filters  #9384
- [x] test that ng-rive issue is solved (warning on sentry should appear when loader is displayed on movie list) #9450 & #9444
- [x] test new filters , ability to copy/paste list, modal displaying selected items. Modal is also used elsewhere in apps, check if still working. Test preferences , request asking price & holdbacks forms  that now use new group-select #9375 #9414 #9376  
- [x] test to delete all items from wishlist #9381
- [x] check notifications about contracts (and maybe try to remove a contract that already have a notification to check how it is displayed, a sentry error should be triggered) #9444
- [x] check if number of episodes can be set to more than 1000 #9462
- [x] test contract import (should be less bugger than before) including terms overlapping & test quickly avails map #9402
- [x] test organization excel import #9402
- [x] check that 'real' seller is displayed on front instead of 'centralOrg' #9402
- [x] test to access a movie page on CRM with an invalid Id, should redirect to movie list #9444
- [x] test new `has avails` column on movies export CRM #9400
- [x] try to update income of an existing offer , to delete a term from a negotiation and to remove a right from a offer package on CRM #9402
- [x] check new languages labels #9458

To Do : 
- [x] on **staging** and then on **prod** db, correct manually the 2 new incomes :  add `contractId` & rename `termsId` to `termId` #9402

**Comment by 2amarkina** [comment]
- [ ] Change the wording from "see list" to "see details" in the case when we have Select Rights or Select Territories [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdDg3IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--6609a84fe79e04fab14f48cd5e1625790104ee08/see%20list.png)

**Comment by 2amarkina** [comment]
- [ ] verify the number of episodes, we still can put the number more than 1000. Let's increase it to 10.000
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaWs4IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--4d3d3a4eedb9f2c1de1c748fc7ea2b06bbf45e81/episodes.png)

**Comment by 2amarkina** [comment]
- [ ] CRM notification - user has been deleted from the org, but any notification was sent

**Comment by 2amarkina** [comment]
While testing the new "see list" feature on the "Request Asking price flow" on the FESTIVAL, we can see that there is a bug 

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdmxCIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--fe0372e53970ae7a5fed09baf0211a05e70f050a/AM_Request.png)

**Comment by 2amarkina** [comment]
for @phpgeekfr check for the error ng-riv sentry

**Comment by 2amarkina** [comment]
- [ ] mini-typo while redirecting to the movie list, if movie id is invalid : **This movie does not exist** (without "s" near exist)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaTVDIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--db06c9e03f5c7d1c6e9608b0941cbffc6428644f/typo%20.png)

**Comment by 2amarkina** [comment]
- [ ] Errors with Import Organizations via template CRM 

1. I created two orgs : a new one "New Company" and already existing one. No errors for the new one and error for the company that already exists - OK. 
2. While importing the New Company I got a snackbar "Could not import all organizations 1/1" 
3. Still I received the mail that everything is ok
4. The New Company is not listed in the OrgList
5. I've tried to import it one more time, but got an error that it already exists, but still it doesn't appear on the OrgList
6. I could connect to the platform with admin email of New Company, but i was directed to the Sign Up page and Company Name was my email address and New Company doesn't appear on the list (not orglist and not company dropdown on the sign up page)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBalpJIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--7eb3a808bb31b8120d3fc0374e453aeaa5d6ae86/sigh%20up.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBamRJIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--2aea1f3ba2702061ed8640abc1dfeeac2a50ac1c/snackbar.png)

**Comment by phpgeekfr** [comment]
@2amarkina regarding your last comment, there was an error when country was not specified that was blocking org creation

**Comment by 2amarkina** [comment]
Bug new rights select (ok for territories).

- [ ] When I start typing Pay TV with keyboard, my group TV is shown and I can't choose open it or manipulate it

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdGxJIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--4962b2318d1ff7329bd8e6098806171cd7760726/select%20tv.png)

**Comment by phpgeekfr** [comment]
- [x] added title column on contract excel import table

**Comment by phpgeekfr** [comment]
- [ ] @n-germain-work In territory select of group-multiselect component, if I type 'usa' in the input, united state of america should be displayed

**Comment by phpgeekfr** [comment]
@2amarkina regarding `CRM notification - user has been deleted from the org, but any notification was sent. If deleted from app - no problem, notification is received.` : When user is removed from org (via apps or CRM), a notification is created. This is not the case when an user is actually deleted (via CRM only), in that case, no notification is sent.
