### ISSUE TITLE
App review

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#9586]
Browser: brave
App version: 22/12/23 (modif arbitraire)
☕ Means it's to be done only if it's coffee time

## General UI
- [x] @2amarkina we need a favicon!
<img width="154" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMDZCQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2282e8001ba0728a90b6d681da7e4cfd58b6af0f/image.png" alt="image.png" />

 - [ ]  ☕ In different places we display the page before data is loaded so it creates a little spike. I guess that's not the time but would be great to have a loader before data is loaded and then display the page
 (example on statement form)
<img width="640" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBelNDQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--73e477e4cdf7c3eb40360cead231edd07f4d5d99/Dec-22-2023%2014-31-40.gif" alt="Dec-22-2023 14-31-40.gif" />

## Manage right holders
<img width="1875" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMGlCQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--294bf1d6b2f97c3f149cd0068544b5e5f20bec38/image.png" alt="image.png" />

- [x] Add the Movie name below the page title, cf [design](https://www.figma.com/file/s0qk9gGKVSJl8zXTPuNipr/UI---Blockframes?type=design&node-id=1813-32568&mode=design&t=MiQU6yV15MpPFGHq-4)
<img width="590" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMUNCQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--865c42679438f56c6a0f17df04e866d2b08bbf15/image.png" alt="image.png" />

- [x] Delete button: is this really ok to delete a fake org? I think we should add the same restriction as what should come with delete a right (if not in place for Berlin, best to hide this button)
- [x] Update the subtitle: "Please add the companies that will be involved into the waterfall. Changes are saved automatically."

### Documents
- [ ] Fake org name are saved lowercase, we should keep the capital letters instead
- [ ] Add Document name in the template

### Statements
- [ ] Expense type: accept string (so `frais_indie_sales` can be `Frais IndieSales`)

## Movie creation
- [x] My org wasn't added as the "can manage" org of my fake org created by default on the waterfall, creating permission errors.
~~- [ ] Add `Currency` select ([design](https://www.figma.com/file/s0qk9gGKVSJl8zXTPuNipr/UI---Blockframes?type=design&node-id=1687-18969&mode=design&t=5JwDqst9afGoo3Fo-4)) => #9422~~

## Waterfall Graph
⚠️ Permission issue prevent me to test the form really deeply 😔
### Graph view (left side)
- [x] Add a padding top between the graph container and the first line of objects
- [x] When creating a new right through the default instructions it appears top right below sources. I guess it's hard to find a correct position anyway but better to put rights above the sources
<img width="435" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNjJCQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5a6a11c48e4ff02deadbf6a883cade35ea1ca72f/image.png" alt="image.png" />
 
- [x] I clicked on the + below a source, the right appears but quickly disappeared and now I can't create a new one nor see the one created
I got this error in the console `Error: org.eclipse.elk.graph.json.JsonImportException: Referenced shape does not exist: z-right-0cv1euxad`
(maybe related to my permission issue..)
<img width="1909" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMlNCQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4c8979b99eadab3e601325a4abdef0e9922038f7/image.png" alt="image.png" />

- [ ] Group collision on Gaspard at the wedding ([graph](https://waterfall-blockframes-bruce.web.app/c/o/dashboard/title/UOAxqGsWmON1YhWO88H4/waterfall) on Bruce's env or [excels](https://drive.google.com/drive/u/2/folders/1qj6-fiymi2nBP_0C-sYfn4byaSzmVAFb) for import)
<img width="1493" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd1NDQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7dcf5182133db74754b4a05eaceb7714bdcf13d8/image.png" alt="image.png" />

### Graph form (right side)
<img width="956" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN3lCQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c62c0cbf3e659bc67892169ea58c755eb7b29c04/image.png" alt="image.png" />

- [x] Add a modale on click on the delete button for source and right "Are you sure you want to delete this?" + Confirm | Cancel buttons
- [x] Right types are:
- Expenses Recoupment
- Commission
- Royalties
- MG Recoupment
- Producer's Net Participation
- Investment Recoupment
- Better to have an empty string as default

- [x] Add a select to associate a contract to the right (see [design](https://www.figma.com/file/s0qk9gGKVSJl8zXTPuNipr/UI---Blockframes?type=design&node-id=1688-14185&mode=design&t=z5Jay1nkznlXrRvs-4)). This select should appear only once the org name is selected and it should be default on a contract related to the org. It can be empty (so it should be an option) and the rest of the list is all the movie contracts. 
Name of the field is `Related Contract` 

- [x] ☕ Name should be dynamically set with `{Org name} - {Right type}` unless it's modified by user
- [ ] "Receipt Sources" select:
- Rename it `Parent Revenue Element(s)`
- Label "Source Name" becomes `Parent Name(s)`
- Hint: `Choose parent revenue elements from which this Receipt Share draw funds. You can add as many parents as you want.`

### Default form (right side)
<img width="953" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNDZCQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f8fbe7867b812371cc5c24ed2185036ed0fe555e/image.png" alt="image.png" />

- [x] Change text:
- Title: Instructions
- Body:

**Title Waterfall Creation Guide**
Welcome to the section dedicated to crafting the revenue distribution (waterfall) for your film or series (Title). Please adhere to the following structured guidelines to ensure an accurate and efficient setup:

**Understanding the Waterfall Schema:**
This schema illustrates the revenue flow, systematically channeling funds from the top tier downwards.

**Identifying Receipt Sources:**
These are the origins of your revenue. Typically, they encompass various media and geographical territories.

**Allocating Receipt Shares:**
Receipt Shares represent the entitlements granted to each stakeholder, allowing them to claim a portion of the earnings. This may include commission fees, recoupment of expenses, the producer’s net revenue share, or other rights afforded to stakeholders.

**Step-by-Step Waterfall Creation:**
1. **Individual Stakeholder Focus:** Tackle the waterfall creation one stakeholder at a time. It’s advisable to start with the sales agent and main distributor’s mandates.
2. **Establish Receipt Sources:** For each stakeholder, identify and list all the Receipt Sources from which they derive revenue.
3. **Structure Receipt Shares:** Begin by allocating Receipt Shares that draw from the initial earnings ('first euros'). Subsequently, establish subsequent shares in a sequential manner.

- [x] Ask for Help should open Intercom (if it comes with the app setup?)
- [x] Change the text on the buttons: `+ Create new Receipt Sources`, `+ Create new Receipt Rights`

## Contract form
- [x] Add a snackbar on save "Contract saved"
- [x] Add the warning modale when leaving a dirty form that is not saved "beware you will lose your work.." (already exist in the project)
- [x] Remove the "Add amendment button" since it won't be live for Berlin
- [x] See the [issue about relation with roles](https://github.com/blockframes/blockframes/issues/9577) (and the last comment)
- [x] "Investment / Minimum Guaranteed" > rename it `Investment | Minimum Guarantee` 
- [x] "Right Assigned" should be visible only on contracts that have specific fields `Territories` and `Medias` on this table

<img width="860" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNEdCQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--982de32794d9a3ad378b46fc74e12a1d4c4b258f/image.png" alt="image.png" />

- [ ] ☕ Sticky header on the form (for this component wherever it is)
- [x] ☕ When I enlarge then shrink, the shrink version is longer than before
<img width="1656" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMzJCQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--670c47eb2f3b6639fae44c93b6641f507b248b86/image.png" alt="image.png" />

### Statement form
<img width="1659" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBenFDQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f191810f7dd69051810b8adbf478137e0382f905/image.png" alt="image.png" />

**Header**
- [x] Change title for: `[Distributor name] Statement #X`
- [x] Replace Movie with `Title:`
- [x] Update Contract value with `[Contract name] ([Contract source 1], [Contract source 2],..)`
- [x] Remove Distributor line
- [x] Covered Period & Statement period From / To have 2 different formats (first European, second American). Best would be both to follow browser values but if we have to choose let's go for European and if it would also change on Archipel then go both on American.
- [x] Change "Please provide us with the following information so we can calculate the waterfall" for `Please indicate the period covered by this report.` 

**Receipt form**
- [ ] Don't know if there is a logical reason but receipts are by default saved on an empty line. Instead could we have the form open without the table (see below screenshots) and ofc best would be to have the [Table + form component ](https://github.com/blockframes/blockframes/issues/9587)
_Current default_
<img width="1876" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMXlDQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--19d9f19c625b834f73ab4767a8214747e662002f/image.png" alt="image.png" />
_Change asked_
<img width="1880" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMXVDQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2dd0fdc2771e82cd10311e7a04f08652f27cc75b/image.png" alt="image.png" />

- [ ] Not completely sure of this solution ( @2amarkina please confirm or propose something else) but I think the "Save Receipt" button is not visible enough > change it for a blue button ? If so, maybe we can move the buttons Continue / Saved & Come back later to top right of the page? 
- [x] Rename Price column `Amount` and Action `Actions`
~~- [ ] Remove Currency input, it will be the waterfall currency by default~~
- [x] "You can personalise your receipts using the following elements." Changed for `Please declare below the gross receipts that will be used for waterfall calculation.`
- [x] Rename "Continue ->" button `Calculate split` 
- [x] Save & Come back later > remove `!`  from snackbar message and redirect to statement list

**Expense form**
<img width="1888" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM1dDQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8e51ef8ee81d97750d5d1b65c4f802d1b9e0cdd1/image.png" alt="image.png" />
- [x] Remove `Please note, only the capped sums will be used for the calculation.`
- [x] Cap summary:
- Rename "[Expense type] CAP": `Total capped expenses declared` 
- Then the number should be total prior capped expenses + current declaration capped expenses (so the user can see in real time where is the cap), update real time
- Finally rename "max X" with `cap: X`; the colour of this should be black when 80% or less from the cap, orange on the last 20% and red when equal or above the cap.
- [x] Rename "Nature": `Expenses name`; "Price" `Amount`; "Action" `Actions`
- [x] Capped value inside the table: show `Yes` or `No` instead of the toggle
- [ ] Remove the * on "Nature" input (renamed Expenses name)
~~- [ ] Remove Currency input, it will be the waterfall currency by default~~
- [x] Add "Is capped?" before the cap toggle
 

### Statement summary
- [x] Remove "Here is the Summary of your Statement. Please verify the information below." (it will be shared to stakeholders)

### Statement list
<img width="1914" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeHVDQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bb67490d9a4903349376081ea31dd5428b444692/image.png" alt="image.png" />

**Right Holder selection**
- [x] Change "Right Holder" with `Distributor` (best would be to have `Distributor` on Main Distributor and `Sales Agent` on Sales Agent but ok to have `Distributor` on both)
- [x] Right Holder name is displayed with capitalized letters on each word but instead it should be the plain string of the fake org name (so "UFO Distribution" is displayed correctly)
- [ ] Either remove the "See Contracts" button or add a link to the actual document (if we have the document list going)

**New statement button**
- [ ] I think this is not visible enough, @2amarkina do we have something in between so it's not main CTA but not invisible?
- [x] Text is too long, I would go for `+ Add Statement ([contract name])`

**Statement table**
- [x] Remove "Notify right holder" button
- [x] View Statement button shouldn't open a new tab
- [x] Rename "Reported" column `Status`
- [x] Add delete button on drafts

**Add New Main Distributor button**
 - [x] Rename this button `+ Add Statement for another Distributor`  (/ `+ Add Statement for another Sales Agent`)

**Comment by 2amarkina** [comment]
### General
- [ ] 404 page should lead to the Dashboard Movie List instead of Marketplace
- [ ] [Link to favicon](https://drive.google.com/file/d/1TssFu-Q37BbsmBMkXv36y5C33KkA5pf_/view?usp=drive_link)

@Jackseed  As the CTA "Save ..." is here because of the component we use for the Archipels (edit & save lists) i would propose to keep it like this for the moment, as we would change the whole component for the editable table. 

### Movie List 
- [ ] On the poster view : remove the "heart" to add to wishlist (as has no sense on the dashboard). 

### Graph form (left side)
- [ ] Add margin-left and margin-bottom to the Version CTA (about 20px). 
<img width="1203" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBejRQQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--74ccd4a5d30d37ead41a65050cd3b50fb0466903/Capture%20d%E2%80%99e%CC%81cran%202024-01-30%20a%CC%80%2014.34.11.png" alt="Capture d’écran 2024-01-30 à 14.34.11.png" />

- [ ] Add the tooltip with description of the Waterfall version (@2amarkina will provide the text)
<img width="389" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMHdQQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f638789d2fc4f3c7d831598da3846a133107d405/Capture%20d%E2%80%99e%CC%81cran%202024-01-30%20a%CC%80%2014.48.41.png" alt="Capture d’écran 2024-01-30 à 14.48.41.png" />

- [ ] Add margins for the "body" of the Waterfall (about 20px)
- [ ] ☕️ Also add some space inside on the left the waterfall Scheme Surface and more space between "Please provide the condition" and the scheme itself
<img width="1571" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMkFQQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a9b0fa7d1ef9932cbe14c7dca271373aee5ed699/Capture%20d%E2%80%99e%CC%81cran%202024-01-30%20a%CC%80%2014.50.23.png" alt="Capture d’écran 2024-01-30 à 14.50.23.png" />

### Graph form (right side)
- [ ] When create an n+1 source, there is a very strange source name that appears. It will be better to refill with something user-friendly like « New source » 
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMlFQQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f957fb3cfaa1d2fdaf04794b27292f361689f73e/strange%20source%20name.png" alt="strange source name.png" />

- [ ] If a user clicks away from the Graph's right Form and there is no saved RS, the modal should show "before we begin" text. 
- [ ] If a user clicks away from the Graph's right form and there are n+1 RS, then the modal should show the RS list. 
- [ ] If we change the name of the Receipt Share Name, the change should be automatically applied in the conditions. 
- [ ] We need to have more user-friendly investment IDs, see together what are our options. 
<img width="1282" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOVlQQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a3a8c6f44962d6ce12eb81fb9e64fb8d54193153/lisibilite%CC%81%20investments%20id%20conditions.png" alt="lisibilité investments id conditions.png" />

### Statements
- [ ] When there is a modal to Choose a distributor for a first time, the link "add new contract" page should be opened in the new tab
<img width="854" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOWtQQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a05576d379de14eb8faeda360c1162f622ea371e/Capture%20d%E2%80%99e%CC%81cran%202024-01-30%20a%CC%80%2015.54.50.png" alt="Capture d’écran 2024-01-30 à 15.54.50.png" />

- [ ] If we are watching the previous statement, all the fields should be disabled (user can't edit the already reported statement). If possible, change color to disabled ---> verify the possible color selection together
- [ ] When the Statement is reported, then the "comment" part should be adapted to this situation as in the example below 
<img width="404" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL2NQQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4d1f41e8f201fca9035cb6ff20be227055932c21/Capture%20d%E2%80%99e%CC%81cran%202024-01-30%20a%CC%80%2016.14.02.png" alt="Capture d’écran 2024-01-30 à 16.14.02.png" />

- [ ] ☕️ The CTAs "rapport" & "save" CTA are disabled on the reported statement (and that's great!) but as we do not need them, it might be better to hide them? (if easy to do)
- [ ] We need to replace the "Unknown" on the arbitrary modifications by Gross Receipts 
<img width="684" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeFVRQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--19a0f49df9fb130b0a1f86e2421ae8d0d7a0c8f5/Capture%20d%E2%80%99e%CC%81cran%202024-01-30%20a%CC%80%2016.23.11.png" alt="Capture d’écran 2024-01-30 à 16.23.11.png" />
 
### Payment 
- [ ] There is a strange bug : after declaring a payment we can observe a strange jump of the lines
<img width="600" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBek1RQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ba5f07d12fcd3762b1ae566b04da40e656e708fe/jump.gif" alt="jump.gif" />

### Revenue Summary 
- [ ] Add a tooltip "see contract"
- [ ] The action should lead to the particular contract 
<img width="1454" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBejRRQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d17a6e0de55dce1e4db6c83e28cdc6e3940240b9/Capture%20d%E2%80%99e%CC%81cran%202024-01-30%20a%CC%80%2015.05.17.png" alt="Capture d’écran 2024-01-30 à 15.05.17.png" />

**Comment by phpgeekfr** [comment]
- [ ] When editing a contract, licensor role is not the good one, in this example it should be producer. Saving as is will change licensor status.
<img width="1402" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNWNWQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e4af66a110d62a365238e133227750027171406b/image.png" alt="image.png" />

- [ ] on the rightholder tab, if I remove producer from roles and save, and come back to rightholder tab : form cannot be saved to put back producer.
<img width="578" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNTBWQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9284bc4cd8fab60cd07e56003cee400a24597a1b/image.png" alt="image.png" />

- [ ] still on same tab, when clicking on "save & come back later" the modal is displayed instead of saving and redirect
<img width="977" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNkFWQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4933267648b1ade7cd5fd4c5f6557cfa60c50d96/image.png" alt="image.png" />

**Comment by phpgeekfr** [comment]
- [ ] on dashboard page, Revenue Summary table : implement or hide "Export in .CSV" button
- [ ] on dashboard page, Revenue Summary table, action column: add link to contract

**Comment by phpgeekfr** [comment]
- [ ] add link to document in statements ( outgoing), statement list etc ...

**Comment by phpgeekfr** [comment]
@2amarkina can you provide more information for `If we are watching the previous statement, all the fields should be disabled (user can't edit the already reported statement). If possible, change color to disabled ---> verify the possible color selection together` for me it is already the case

**Comment by phpgeekfr** [comment]
@2amarkina same for `On the poster view : remove the "heart" to add to wishlist (as has no sense on the dashboard).`

**Comment by phpgeekfr** [comment]
- [ ] re-activate standalone statements for distributors  / directSales

**Comment by phpgeekfr** [comment]
- [ ] configure sendgrid template ID : d-7a07c39d8c104674ad278669c9ce787a (BF - STATEMENT - Share statement)

**Comment by 2amarkina** [comment]
- [ ] Text proposition for the tooltip to describe the Waterfall's version
`The waterfall version refers to the specific configuration or distribution plan used to allocate revenues among different right holders or stakeholders involved in a film project.`

**Comment by phpgeekfr** [comment]
- [ ] statement period: end date should not be after end date of contract (or amendments)

**Comment by 2amarkina** [comment]
- [ ] When creating the Waterfall, I was filling in the infos about the right holders and clicked on "Save and come back later". There was a modal about leaving the page. Instead of this modal after clicking on CTA "Save & come back later" we need to show a snackbar "Waterfall is saved" and user should be redirected to the Waterfall tab.

**Comment by 2amarkina** [comment]
- [ ] As for the moment we do not manage the amendments, let's hide this "+" for the moment <img width="917" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBLzhqQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b1ab169ff9c5a1043fb14478e1252b36fdf444cb/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202024-02-02%20%D0%B2%2015.43.36.png" alt="Снимок экрана 2024-02-02 в 15.43.36.png" />

**Comment by 2amarkina** [comment]
- [ ] If possible during the creation of the waterfall, it would be better to add the name of the right holder in brackets. It's needed to distinguish the Reciept Shares with the same names
<img width="1433" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeDBrQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e4f71999c603f3d694a323c95848eae3d4faa693/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202024-02-02%20%D0%B2%2015.59.14.png" alt="Снимок экрана 2024-02-02 в 15.59.14.png" />

**Comment by 2amarkina** [comment]
- [ ] If we have already entered the signature start and end date, and then we change the first date and play with duration number and duration period, the end date remains related to the previous date and not the new one
<img width="1262" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM1FrQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ffb1fda00e750184bcaf62601f198cb9af801cd9/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202024-02-02%20%D0%B2%2016.41.53.png" alt="Снимок экрана 2024-02-02 в 16.41.53.png" />

**Comment by 2amarkina** [comment]
> * [ ]  configure sendgrid template ID : d-7a07c39d8c104674ad278669c9ce787a (BF - STATEMENT - Share statement)

I would like to change the text from this `Hi, Please find enclosed a statement for "{{ waterfall.title }}" generated on {{app.name}}` to that `Hi, {{ userSubject.firstName }} {{ userSubject.lastName }} from {{ org.name }} sends you the statement for {{ waterfall.title }}. Please find the statement in the attached file.` 

and also put this picture
![Property 1=Illustrations_380px_feature_key1_light](https://github.com/blockframes/blockframes/assets/55499036/de579427-32fc-4f97-8ed9-45b867c3353e)

 @Jackseed  what do you think?

**Comment by phpgeekfr** [comment]
@2amarkina right now you will not have access to ` {{ org.name }}` in this email.

You can use 
```
user.firstName
user.lastName
user.email
waterfall.title
app.description
app.logo
app.name
app.url 
```

Also, check that app.description works as it was bugged and didn't check it

**Comment by phpgeekfr** [comment]
- [ ] add `{{ org.name }} {{statement.receiverOrgName}}   {{statement.from}}   {{statement.to}}` in email data

**Comment by 2amarkina** [comment]
- [ ] ☕️ micro-thing: on the statements list we need to have "edit" icon and then "delete" icon. 
<img width="538" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeUU1QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--773e34787dfe5ecea7c557c086d746fabf2115c5/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202024-02-07%20%D0%B2%2015.27.29.png" alt="Снимок экрана 2024-02-07 в 15.27.29.png" />

- [ ] @pldespaigne, @Jackseed  I've created a separate[ issue #9647](https://app.zenhub.com/workspaces/blockframes-60b0a31838e485001b3a619f/issues/gh/blockframes/blockframes/9647) for the trackpad gestures

**Comment by 2amarkina** [comment]
- [ ] Change the text inside the Statement period : `You can modify the issue date, which is particularly useful for older films.`
<img width="1616" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNGc1QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5efe07e53e458f5b4838b080a869ba08a1c6ddc7/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202024-02-07%20%D0%B2%2016.16.57.png" alt="Снимок экрана 2024-02-07 в 16.16.57.png" />

**Comment by phpgeekfr** [comment]
- [ ] rightholder should be a simple select, it should not be possible to enter a not existing rightholder as we don't create it.
<img width="1828" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN1k1QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--417c04066a8c9fca1922d70a33a5a6b3ff83cb49/image.png" alt="image.png" />

**Comment by phpgeekfr** [comment]
for better readability, I moved what is left to #9657 . Please add new issues to #9657
