### ISSUE TITLE
Sources & Rights update & delete

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#9588]
## Context
Right update & delete are super sensitive since it may mess up with already made statements & payements. Though users may certainly need to update & delete while creating the waterfall. We must be super careful in here.

## Todo
A complicated approach would be to check what are the impact of the changes and block if there are. 
I guess now that we brought the "publish" status of the waterfall we can start easy and rely on this:
- [ ] Accept updates & delete while waterfall is draft
- [ ] Hide the buttons if waterfall is published

**Comment by 2amarkina** [comment]
If the waterfall is not published yet we should be able to delete a Receipt Share. We should still inform user about the consequences of this delete (even if waterfall has not been published yet).

- [ ] Be able to delete a RS directly inside the editor mode
<img width="555" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNnlIQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7f711a1a4c19cf621157d5ff16c16b14221d9713/RS_Build.png" alt="RS_Build.png" />

- [ ] Also the delete option can be found when we open the share list. 
<img width="710" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN0tIQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--82cc1bd4a5ec6bc660e6c55232cf9d149ae10f99/Waterfall.png" alt="Waterfall.png" />

- [ ] In the share list the click on the "edit" should lead to the default RS editor. 

- [ ] When we delete an RS we prevent a user about the consequences
<img width="764" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN1dIQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bbe1dcbb9bef79b55197e1d8cd748da7421d5940/Waterfall%20%281%29.png" alt="Waterfall (1).png" />

- [ ] When an RS is deleted, we need to show a snackbar "[Receipt Share Name] is successfully deleted."
<img width="710" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN2FIQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7b01fa122bcc2d406ff04b68dbbd6876d49be227/Waterfall%20%282%29.png" alt="Waterfall (2).png" />
