### ISSUE TITLE
Changelog release 5.0.4 

### ISSUE THREAD

**Issue by phpgeekfr** [blockframes/blockframes#9700]
Issues:
- Collaboration step 2 - Stakeholder invitation #9585
- Allow distributors / sales agents to create statements #9689
- Files Manager Update - Waterfall #9429
- waterfall graph Sidebar #9693
- Movie count on catalog missmatch between movies.length and movies.nbHits #9709
- Change Text / Hide Mail #9684
- Uniformize date format on all apps #9642
- Urgent bugs & Important for demo #9703
- Important improvements for the demo #9704

Changelog / To test: 
- [x] Waterfall admin can manage other organization on waterfall and create/cancel invitations #9585
- [x] When invited to waterfall, user is assigned a rightholder (fake org) and a level (viewer/editor)  #9585
- [x] When invited to waterfall, user receive an email to join app (no account yet) or an email to join waterfall  #9585
- [x] If multiple users from the same org are invited to waterfall, once one invitation is accepted, other invitations are dismiss and it is not possible to invite another user of the same org again  #9585
- [x] admin users can manage org: change lockedVersion, change associated rightholder, change access level, manage rightholder and remove organizations. #9585
- [x] non-admin (or non-editor) user associated to a  fake org with distributor/sales agent role can now produce their own statements. Once statement is reported, producer is notified in app & by email for approval. If refused, statement is back to draft and creator is notified. If accepted, statement is committed to waterfall and creator is notified. #9689
- [x] an icon indicates that a statement review is pending. producers can accept or reject a statement on the statement page. #9689
- [x] When a statement is submitted for approval, blockframes admins also receive an email #9689
- [x] non admin user can only see statements related to them: statements associated to the rightholder and potential parent statements used to generate an outgoing statements. #9689
- [x] admin users can now upload financingPlan & Budget pdf. Non-admin users can only read them (same for contracts). #9429
- [x] test PDF sharing  & download #9689
- [x] when a contract is deleted, associated statements (& incomes, expenses) are also deleted  #9689
- [x] when a producer/direct sales statement is deleted, related outgoing statements are also deleted  #9689
- [x] on CRM side, financing plan, budget & contract are listed in document tab. They can be viewed or deleted. #9429
- [x] reworked CRM permissions tab #9585
- [x] updated rules & unit tests to allow non admin to create incomes & expenses for their statements #9689
- [x] added a guard to prevent non admin to access page they are not allowed to see #9585
- [x] createdBy & updatedBy (uid) is now saved on statement document  #9689
- [x] updated snackbar messages on dashboard, graph & statements pages to allow more understanding of the issue and redirect user to the correct page if allowed ( if not, opens intercom) #9585
- [x] waterfall tabs are displayed or not depending of the access level of the user and the waterfall state (ready or not)   #9585
- [x] left sidebar is now displayed on the waterfall graph view page. It allows to change from actual values (statements) to calculated values (live data), to highlight, hide rightholders, to view waterfall data in time (statement dates) and to display rightholder data #9693
- [x] waterfall graph zoom issue is fixed #9693
- [x] improved dates checks when creating/editing a contract #9585
- [x] fixed an issue that was preventing a contract to be edited even if all fields where filled ( terms duration issue) #9585
- [x] when a statement is reported by an admin it is committed to waterfall directly. when a statement is reported to an admin, it is not included into waterfall calculus until it is approved by an admin  #9689
- [x] fixed a bug when accessing an outgoing statement in readonly mode with interests details #9689
- [x] simulated waterfall only include the current draft statement to calculated current income repartitions #9689
- [x] when a non admin users wants to create a statement, if no contract is displayed on the modal, user can ask for help via intercom #9689
- [x] cannot generate payments for a reported statement made by a non admin that is not reviewed/accepted
- [x] refactored waterfall library folders
- [x] check on catalog movie list that number of movie displayed is always accurate, with or without avails search form filled. #9709
- [x] check Change Text / Hide Mail #9684
- [x] check that date format displayed and used in various date pickers is the one belonging to current browser settings. Check this on waterfall app but not other. use `console.log(navigator.language)` in browser console to get your current `locale` #9642
- [x] check that screen theme is removed #9703
- [x] check dates in PDF statements

TODO:
 - [x] review and update 3 new email templates for statement review  #9689
```
requested: 'd-ea179c323afd4c23bf268bc075895840',
approved: 'd-ccb2291df83248a68a3ef4ff1b5e3aad',
declined: 'd-7645e94c275741b4989eb5f71df1ce07'
```
- [x] review the template for invitations #9585
- [x] check what is left to do for Trackpad actions for the Graph #9647

**Comment by 2amarkina** [comment]
> If multiple users from the same org are invited to waterfall, once one invitation is accepted, other invitations are dismiss and it is not possible to invite another user of the same org again #9585

Is it correct that when I invite the second user for the same fake and representative org I got this message? If yes, is it possible to change this text to: "This organization has already been invited to the waterfall" <img width="1362" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOVQ4QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a729ccc8c83167a02ef4b3e0e79c8ea268074088/email.png" alt="email.png" />

**Comment by 2amarkina** [comment]
- [ ] When a distributor has finished creation of his statement and the snackbar about review appears, he should be redirected to the list of list of statements

**Comment by 2amarkina** [comment]
> non-admin (or non-editor) user associated to a fake org with distributor/sales agent role can now produce their own statements. Once statement is reported, producer is notified in app & by email for approval. If refused, statement is back to draft and creator is notified. If accepted, statement is committed to waterfall and creator is notified.

- [ ] At the moment the user is redirected to the Summary page of the statement and needs to scroll to the "back" btn ant the end of the page, let's redirect him directly to the edit page and remove this supplementary back click ?

**Comment by 2amarkina** [comment]
> non admin user can only see statements related to them: statements associated to the rightholder and potential parent statements used to generate an outgoing statements.

- [ ] Is it possible to hide the chip and the page if there is nothing in it like here?
<img width="1967" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK244QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--def4a5dc05cfe26c6fa61d99d8c6c43e8e97f527/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202024-03-21%20%D0%B2%2014.47.31.png" alt="Снимок экрана 2024-03-21 в 14.47.31.png" />

**Comment by 2amarkina** [comment]
> admin users can now upload financingPlan & Budget pdf. Non-admin users can only read them (same for contracts).
Let's check together, to me the last discussion was that non-admin can't have access to these documents for security reasons and we add the "personal sharing" function later. Is this correct? 

At the moment this logic is implemented on the app, the editor has access to the contracts, but not the viewer.

**Comment by phpgeekfr** [comment]
last minute debugs :
- [ ] fixed statement date in PDF and email
- [ ] fixed date issue in mat-date-picker inputs
- [ ] fixed placeholder in  mat-date-picker inputs
- [ ] redirect user (admin or viewer) to statement list when statement is reported/asked for review
- [ ] fixed typo "There are no statistics available here yet."
- [ ] fixed error when deleting date from time-picker (used in contract form)
- [ ] prevent user to leave contract form (click on mat-stepper, continue button on switch to another contract type) by displayin a modal
- [ ] changed snackbar message "This organization has already been invited to the waterfall."
- [ ] waterfall graph sidebar not displayed until there are reported statements and only show reported statements
- [ ] fixed bug on org/fake orgs table when fake orgs are deleted.
