### ISSUE TITLE
Release 5.4 changelog 

### ISSUE THREAD

**Issue by phpgeekfr** [blockframes/blockframes#9935]
**changelog**

- updated intercom lib from `ng-intercom` to `@supy-io/ngx-intercom` (fork that works with `ivy`) 
- removed `angular-idle-preload` library (not compatible with `ivy`)
- fixed invitation display bug (Review Release 5.3 #9905)
- updated `ngx-image-cropper` to latest for `ivy` compatibility 
- improved internationalization #9870 
- fixed various CSS bugs and other minors bugs
- added new toolbar in graph builder #9897
- added revenue Simulation inside waterfall builder #9894
- fixed bugs with `expenseTypes` (creation & update in conditions) when on a duplicated or standalone version
- fixed Pupille bugs #9907
- improved e2e tests reliability 
- improved right holder list and contracts on builder 
- fixed bugs when creating or removing steps (vertical)
- `EUR` is now default currency when creating a movie
- updated `angular-calendar` library for `ivy` compatibility 
- internationalization setup in sendgrid emails #9870
- Integrated new legal documents #9943

**TO TEST**

- [x] test intercom
- [x] test invitations display and how they are displayed on various app depending of their type (joinOrg, event, joinWaterfall)  #9905
- [x] test image cropper
- [x] test group select (medias, territories) for internationalization, including modal to copy list #9870 
- [x] test toolbar #9897
- [x] test revenue simulation #9894
- [x] test `expenseTypes` in conditions for all types of waterfall version (including internationalization in modal)
- [x] test pupille bug #9907
- [x] test right creation on builder (rightholder & contracts)
- [x] test vertical group creation & deletion on builder
- [ ] test sendgrid emails and signup, invitation (join org, event, join waterfall) flows, create org from CRM 
- [ ] check new legal documents #9943

**TODO**
- [ ] update sendgrid templates to use internationalization (see https://www.notion.so/cascade8/Sendgrid-translations-f2a83ae8d73246d7b61944f2ca37ec48)

**Comment by phpgeekfr** [comment]
> When I copy the list of rights or countries inside the modals, they are copied in English instead of Spanish or French

Yes, when we copy, this is the `key` that is copied so we can paste copied data into input.

**Comment by 2amarkina** [comment]
**Revenue Simulation**

- [ ] For me the "Clear existing data" toggle is not explicit enough, we do not understand at a gglance what the toggle does, what data are we talking about. Let's find a better solution / wording together 
- [ ] Need to add more space after the divider. 
Proposition: 
`mat-divider.mat-divider.mat-divider-horizontal {margin-bottom: 20px;}`

- [ ] Let's put the CTA "Simulate the revenue" on the right as the main / primary action that we want user to do 
- [ ] I propose to put "Exist Simulation" in more neutral color and not into the accent one. Even if the red color is associate with cancelling an action, in our case it's mostly used to attract the attention. The red takes to much attention to the action that is not the main one. 
- [ ] I do not see the simulation results, i've got only the white space 
<img width="2047" alt="Снимок экрана 2024-07-18 в 14 04 31" src="https://github.com/user-attachments/assets/27708f97-aad5-43fe-b3a0-f874feaf7265">

- [ ] When i click on "start new simulation" I am waiting that the previous numbers are automatically removed. 
- [ ] When i'm inside the Simulation mode and click on the receipt share nothing happens. That might be frustrating. Solution: Make the RS clickable and show modal "you're going to exist the simulation mode, are you sure? Pay attention, if you exist the simulation mode you are going to loose the simulation data. "

**Comment by 2amarkina** [comment]
- [ ] Need Help no space 
<img width="217" alt="Снимок экрана 2024-07-18 в 14 35 40" src="https://github.com/user-attachments/assets/3e085344-c4a6-445e-851d-dbb36f1beb7b">

**Comment by 2amarkina** [comment]
Following the discussion about this _"When I copy the list of rights or countries inside the modals, they are copied in English instead of Spanish or French"_ , we are coping the values. 

If we copy - paste the list inside the field, it takes the concerned language. if we copy paste to separate document - then it pastes values, that are in english. Might take take to update this, so for the moment let's keep as it is.

**Comment by 2amarkina** [comment]
Following the discussion about clearing data focntion - it is used only when there are already statements issued. So, need to be more explicit with the user about this fonction. 

Design will be proposed.

**Comment by 2amarkina** [comment]
Simulation results are well shown on Safari, Mozilla, **but are not shown on Chrome**

Also, on mozilla and safari the field of gross receipts is not visible enough, on safari the fields are messed up. 

**Mozilla**
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOXJ6QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--05fa45b9570ea335c80dec12692648e60e7a7aad/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202024-07-19%20%D0%B2%2011.35.56.png" alt="Снимок экрана 2024-07-19 в 11.35.56.png" />

**Safari**
<img width="1366" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOXp6QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4e01a0ff2b3905d452f20281b08be3ad0087083c/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202024-07-19%20%D0%B2%2011.37.23.png" alt="Снимок экрана 2024-07-19 в 11.37.23.png" />

**Comment by 2amarkina** [comment]
design proposition <img width="465" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeEQwQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--024cc9f7a8be2c637286ed29dfcacdd0e02ae70b/Simulation.png" alt="Simulation.png" />

**Comment by 2amarkina** [comment]
WIP for the sendgrid templates. 
Proposition: integrate new legal texts for this release. 
[Issue created here ](https://app.zenhub.com/workspaces/blockframes-60b0a31838e485001b3a619f/issues/gh/blockframes/blockframes/9943)
